# golangci-lint configuration for Personal CRM
version: "2"

run:
  timeout: 5m

linters:
  enable:
    - forbidigo  # Forbid specific function calls
    - gofmt      # Go formatting
    - goimports  # Imports formatting
    - govet      # Go vet
    - errcheck   # Check error handling
  settings:
    forbidigo:
      forbid:
        - pattern: 'time\.Now\(\)'
          msg: 'use accelerated.GetCurrentTime() instead of time.Now() for time acceleration support'
      # Legitimate exceptions use inline //nolint:forbidigo comments:
      # - backend/internal/accelerated/time.go (wrapper implementation)
      # - backend/internal/api/middleware.go (latency measurement)
      # - backend/internal/api/handlers/system.go:83 (TIME_BASE setting)
