// PayloadShapingTests pins the JSON wire shape produced by Swift
// against the Pi-side RawMessageReceivedPayload Go struct. Drift
// between the two sides silently breaks the ingest pipeline.
//
// The golden fixture at Fixtures/raw_message_received_golden.json is
// regenerated by a Go-side helper command
// (backend/internal/events/cmd/dump-raw-message-fixture) that marshals
// a fixed sample struct via json.Marshal — the same encoder the Pi
// uses. The fixture_parity_test.go runs the helper and compares its
// output byte-for-byte against the golden so any Pi-side struct change
// trips a Go-side test even on Pi-only PRs.
import XCTest
@testable import CRMMacMessagesSource

final class PayloadShapingTests: XCTestCase {
    /// Sample host UUID used in the golden fixture. MUST match the
    /// constant in the Go-side dump helper or the byte-for-byte
    /// comparison fails.
    private let sampleHostID = UUID(uuidString: "11111111-2222-3333-4444-555555555555")!

    private func fixturePayload() -> RawMessagePayload {
        // Sample date matching the Go helper: 2026-05-13T15:42:18Z.
        // Unix timestamp 1778686938 = 2026-05-13T15:42:18+00:00.
        let sentAt = Date(timeIntervalSince1970: 1_778_686_938)
        let replyTo = "00000000-1111-2222-3333-444444444444"
        return RawMessagePayload(
            version: 1,
            hostID: sampleHostID,
            source: "messages",
            guid: "abcdef12-3456-7890-abcd-ef1234567890",
            chatID: "iMessage;-;+15551234567",
            peerHandle: "+15551234567",
            peerName: nil, // omitempty -> absent from JSON
            text: "hello",
            messageType: .text,
            isGroup: false,
            sentAt: sentAt,
            replyToGuid: replyTo,
            attachments: []) // empty -> absent from JSON (omitempty)
    }

    // MARK: - shape() direction + bucketing

    func testInboundShapesAsReceived() {
        let row = ChatDBMessage(
            rowID: 1, guid: "g", chatGUID: "c",
            peerHandleRaw: "+15551234567",
            text: "hi", isFromMe: false, isGroup: false,
            sentAt: Date(), replyToGUID: nil,
            primaryAttachmentUTI: nil,
            primaryAttachmentMimeType: nil,
            primaryAttachmentTransferName: nil,
            primaryAttachmentTotalBytes: nil)
        let (kind, p) = PayloadShaping.shape(
            row: row, peerHandle: "+15551234567", hostID: sampleHostID)
        XCTAssertEqual(kind, .received)
        XCTAssertEqual(p.peerHandle, "+15551234567")
        XCTAssertEqual(p.messageType, .text)
    }

    func testOutboundShapesAsSent() {
        let row = ChatDBMessage(
            rowID: 1, guid: "g", chatGUID: "c",
            peerHandleRaw: "",
            text: "out", isFromMe: true, isGroup: false,
            sentAt: Date(), replyToGUID: nil,
            primaryAttachmentUTI: nil,
            primaryAttachmentMimeType: nil,
            primaryAttachmentTransferName: nil,
            primaryAttachmentTotalBytes: nil)
        let (kind, p) = PayloadShaping.shape(
            row: row, peerHandle: "resolved-peer", hostID: sampleHostID)
        XCTAssertEqual(kind, .sent)
        XCTAssertEqual(p.peerHandle, "resolved-peer")
    }

    func testAttachmentBucketing() {
        let row = ChatDBMessage(
            rowID: 1, guid: "g", chatGUID: "c",
            peerHandleRaw: "+1",
            text: nil, isFromMe: false, isGroup: false,
            sentAt: Date(), replyToGUID: nil,
            primaryAttachmentUTI: "public.jpeg",
            primaryAttachmentMimeType: "image/jpeg",
            primaryAttachmentTransferName: "p.jpg",
            primaryAttachmentTotalBytes: 100)
        let (_, p) = PayloadShaping.shape(
            row: row, peerHandle: "+1", hostID: sampleHostID)
        XCTAssertEqual(p.messageType, .photo)
    }

    // MARK: - JSON wire shape

    /// Verifies the encoded JSON contains the snake_case wire keys
    /// the Pi expects. (Byte-for-byte golden comparison lives in the
    /// dedicated test below; this is a quick contract spot-check.)
    func testJSONHasSnakeCaseKeys() throws {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        encoder.outputFormatting = [.sortedKeys]
        let payload = fixturePayload()
        let data = try encoder.encode(payload)
        let json = String(decoding: data, as: UTF8.self)

        XCTAssertTrue(json.contains("\"host_id\""))
        XCTAssertTrue(json.contains("\"chat_id\""))
        XCTAssertTrue(json.contains("\"peer_handle\""))
        XCTAssertTrue(json.contains("\"message_type\""))
        XCTAssertTrue(json.contains("\"is_group\""))
        XCTAssertTrue(json.contains("\"sent_at\""))
        XCTAssertTrue(json.contains("\"reply_to_guid\""))
        // omitempty fields with no value MUST be absent from the JSON.
        XCTAssertFalse(json.contains("\"peer_name\""),
                       "peer_name nil -> absent from JSON")
        XCTAssertFalse(json.contains("\"attachments\""),
                       "attachments empty -> absent from JSON")
    }

    func testTextOmitemptyWhenAbsent() throws {
        let payload = RawMessagePayload(
            hostID: sampleHostID,
            guid: "g", chatID: "c", peerHandle: "p",
            text: nil,
            messageType: .photo, isGroup: false,
            sentAt: Date(timeIntervalSince1970: 0))
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        let data = try encoder.encode(payload)
        let json = String(decoding: data, as: UTF8.self)
        XCTAssertFalse(json.contains("\"text\""),
                       "text nil -> absent from JSON (omitempty parity)")
    }

    func testReplyToGuidOmitemptyWhenAbsent() throws {
        let payload = RawMessagePayload(
            hostID: sampleHostID,
            guid: "g", chatID: "c", peerHandle: "p",
            text: "x",
            messageType: .text, isGroup: false,
            sentAt: Date(timeIntervalSince1970: 0))
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        let data = try encoder.encode(payload)
        let json = String(decoding: data, as: UTF8.self)
        XCTAssertFalse(json.contains("\"reply_to_guid\""))
    }

    // MARK: - byte-for-byte golden

    /// Loads Fixtures/raw_message_received_golden.json (the Go-side
    /// dump output) and compares it byte-for-byte with the Swift
    /// encoder's output for the same fixture struct.
    ///
    /// On drift: the failing assertion prints both representations
    /// and the regenerate command.  Either side may need a fixup
    /// (Go-side struct change + golden regenerate, or Swift-side
    /// encoder bug).
    func testByteForByteGoldenParity() throws {
        guard let goldenURL = Bundle.module.url(forResource: "raw_message_received_golden",
                                                  withExtension: "json",
                                                  subdirectory: "Fixtures") else {
            throw XCTSkip("golden fixture not found in test bundle")
        }
        let goldenData = try Data(contentsOf: goldenURL)
        // Trim trailing newline (some editors add one); the Go-side
        // helper writes without trailing newline so this is defense
        // in depth.
        let goldenString = String(decoding: goldenData, as: UTF8.self)
            .trimmingCharacters(in: .whitespacesAndNewlines)

        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        encoder.outputFormatting = [.sortedKeys, .withoutEscapingSlashes]
        let swiftData = try encoder.encode(fixturePayload())
        let swiftString = String(decoding: swiftData, as: UTF8.self)
            .trimmingCharacters(in: .whitespacesAndNewlines)

        XCTAssertEqual(
            swiftString, goldenString,
            """
            Wire-shape drift between Swift encoder and Pi-side Go encoder.
            Swift produced:
            \(swiftString)
            Go golden:
            \(goldenString)
            Regenerate the golden:
              go run ./backend/internal/events/cmd/dump-raw-message-fixture \\
                > mac-daemon/Tests/CRMMacMessagesSourceTests/Fixtures/raw_message_received_golden.json
            """)
    }
}
