// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assertion_provenance.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const DeleteProvenanceLocator = `-- name: DeleteProvenanceLocator :exec
DELETE FROM assertion_provenance
WHERE assertion_id = $1 AND locator_hash = $2
`

type DeleteProvenanceLocatorParams struct {
	AssertionID uuid.UUID `json:"assertion_id"`
	LocatorHash string    `json:"locator_hash"`
}

// Re-extraction retirement (a later layer): drop a single locator. When the last
// locator is removed the write API retracts the assertion.
func (q *Queries) DeleteProvenanceLocator(ctx context.Context, arg DeleteProvenanceLocatorParams) error {
	_, err := q.db.Exec(ctx, DeleteProvenanceLocator, arg.AssertionID, arg.LocatorHash)
	return err
}

const ExistsCalendarEvent = `-- name: ExistsCalendarEvent :one
SELECT EXISTS(SELECT 1 FROM calendar_event WHERE id = $1)
`

func (q *Queries) ExistsCalendarEvent(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, ExistsCalendarEvent, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ExistsCommsMessage = `-- name: ExistsCommsMessage :one
SELECT EXISTS(SELECT 1 FROM comms_message WHERE id = $1 AND deleted_at IS NULL)
`

// Write-time existence validation: confirm a content source row exists before
// accepting a provenance locator that references it. One tiny query per content
// table; source_id is parsed to UUID by the caller. The four soft-deletable
// content tables filter deleted_at so an already-tombstoned source row does not
// pass write-time validation (a NEW assertion may not be grounded in a dead
// source; a source deleted AFTER the assertion degrades gracefully via the
// preserved quote/input_hash). calendar_event/phone_call have no deleted_at.
func (q *Queries) ExistsCommsMessage(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, ExistsCommsMessage, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ExistsMeetingNote = `-- name: ExistsMeetingNote :one
SELECT EXISTS(SELECT 1 FROM meeting_note WHERE id = $1 AND deleted_at IS NULL)
`

func (q *Queries) ExistsMeetingNote(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, ExistsMeetingNote, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ExistsMessagesMessage = `-- name: ExistsMessagesMessage :one
SELECT EXISTS(SELECT 1 FROM messages_message WHERE id = $1 AND deleted_at IS NULL)
`

func (q *Queries) ExistsMessagesMessage(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, ExistsMessagesMessage, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ExistsPhoneCall = `-- name: ExistsPhoneCall :one
SELECT EXISTS(SELECT 1 FROM phone_call WHERE id = $1)
`

func (q *Queries) ExistsPhoneCall(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, ExistsPhoneCall, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ExistsTelegramMessage = `-- name: ExistsTelegramMessage :one
SELECT EXISTS(SELECT 1 FROM telegram_message WHERE id = $1 AND deleted_at IS NULL)
`

func (q *Queries) ExistsTelegramMessage(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, ExistsTelegramMessage, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const InsertProvenance = `-- name: InsertProvenance :execrows

INSERT INTO assertion_provenance (
    assertion_id, locator_hash, source_kind, source_id,
    producer_kind, producer_version, field,
    start_offset, end_offset, chunk_id, input_hash, quote
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (assertion_id, locator_hash) DO NOTHING
`

type InsertProvenanceParams struct {
	AssertionID     uuid.UUID `json:"assertion_id"`
	LocatorHash     string    `json:"locator_hash"`
	SourceKind      string    `json:"source_kind"`
	SourceID        string    `json:"source_id"`
	ProducerKind    string    `json:"producer_kind"`
	ProducerVersion string    `json:"producer_version"`
	Field           *string   `json:"field"`
	StartOffset     *int32    `json:"start_offset"`
	EndOffset       *int32    `json:"end_offset"`
	ChunkID         *string   `json:"chunk_id"`
	InputHash       string    `json:"input_hash"`
	Quote           *string   `json:"quote"`
}

// Assertion provenance queries (graph foundation).
//
// Provenance carries the corroborating source locators for an assertion. The
// write API computes locator_hash from the full locator identity; the
// (assertion_id, locator_hash) PK makes a same-locator re-emit a no-op while a
// genuinely different span/version inserts a new corroborating row.
// Appends a corroborating locator. ON CONFLICT (assertion_id, locator_hash) DO
// NOTHING makes a same-locator re-emit a no-op; :execrows returns the rows
// affected (1 = inserted, 0 = duplicate) so the write API knows whether to emit
// a provenance_added event.
func (q *Queries) InsertProvenance(ctx context.Context, arg InsertProvenanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, InsertProvenance,
		arg.AssertionID,
		arg.LocatorHash,
		arg.SourceKind,
		arg.SourceID,
		arg.ProducerKind,
		arg.ProducerVersion,
		arg.Field,
		arg.StartOffset,
		arg.EndOffset,
		arg.ChunkID,
		arg.InputHash,
		arg.Quote,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ListProvenance = `-- name: ListProvenance :many
SELECT assertion_id, locator_hash, source_kind, source_id, producer_kind, producer_version, field, start_offset, end_offset, chunk_id, input_hash, quote, created_at FROM assertion_provenance
WHERE assertion_id = $1
ORDER BY created_at
`

// All locators for an assertion, oldest first.
func (q *Queries) ListProvenance(ctx context.Context, assertionID uuid.UUID) ([]*AssertionProvenance, error) {
	rows, err := q.db.Query(ctx, ListProvenance, assertionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*AssertionProvenance{}
	for rows.Next() {
		var i AssertionProvenance
		if err := rows.Scan(
			&i.AssertionID,
			&i.LocatorHash,
			&i.SourceKind,
			&i.SourceID,
			&i.ProducerKind,
			&i.ProducerVersion,
			&i.Field,
			&i.StartOffset,
			&i.EndOffset,
			&i.ChunkID,
			&i.InputHash,
			&i.Quote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListProvenanceBySource = `-- name: ListProvenanceBySource :many
SELECT assertion_id, locator_hash, source_kind, source_id, producer_kind, producer_version, field, start_offset, end_offset, chunk_id, input_hash, quote, created_at FROM assertion_provenance
WHERE source_kind = $1 AND source_id = $2
ORDER BY created_at
`

type ListProvenanceBySourceParams struct {
	SourceKind string `json:"source_kind"`
	SourceID   string `json:"source_id"`
}

// Reverse lookup: every provenance locator a given source produced ("what did
// this source say"), via the (source_kind, source_id) index. Backs the
// source-row-deletion sweep (when a content row is hard-deleted, find the
// locators that referenced it).
func (q *Queries) ListProvenanceBySource(ctx context.Context, arg ListProvenanceBySourceParams) ([]*AssertionProvenance, error) {
	rows, err := q.db.Query(ctx, ListProvenanceBySource, arg.SourceKind, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*AssertionProvenance{}
	for rows.Next() {
		var i AssertionProvenance
		if err := rows.Scan(
			&i.AssertionID,
			&i.LocatorHash,
			&i.SourceKind,
			&i.SourceID,
			&i.ProducerKind,
			&i.ProducerVersion,
			&i.Field,
			&i.StartOffset,
			&i.EndOffset,
			&i.ChunkID,
			&i.InputHash,
			&i.Quote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
