// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comms_message.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ApplyCommsMessageEditByExternalID = `-- name: ApplyCommsMessageEditByExternalID :execrows

UPDATE comms_message
SET body = $1,
    snippet = $2,
    source_metadata = jsonb_set(
        jsonb_set(
            jsonb_set(
                source_metadata,
                '{previous_bodies}',
                (
                    SELECT COALESCE(jsonb_agg(prior_body), '[]'::jsonb)
                    FROM (
                        SELECT prior_body
                        FROM jsonb_array_elements(
                            CASE
                                WHEN comms_message.body IS NULL THEN
                                    COALESCE(source_metadata->'previous_bodies', '[]'::jsonb)
                                ELSE
                                    to_jsonb(ARRAY[comms_message.body])
                                        || COALESCE(source_metadata->'previous_bodies', '[]'::jsonb)
                            END
                        ) AS prior_body
                        LIMIT 3
                    ) AS capped
                ),
                TRUE
            ),
            '{edited_at}',
            to_jsonb($3::text),
            TRUE
        ),
        '{last_update_time}',
        to_jsonb($4::text),
        TRUE
    )
WHERE source = $5
  AND external_id = $6
  AND deleted_at IS NULL
  AND COALESCE(
        NULLIF(source_metadata->>'last_update_time', '')::timestamptz,
        '-infinity'::timestamptz
      ) < ($4::text)::timestamptz
`

type ApplyCommsMessageEditByExternalIDParams struct {
	Body           pgtype.Text `json:"body"`
	Snippet        pgtype.Text `json:"snippet"`
	EditedAt       string      `json:"edited_at"`
	LastUpdateTime string      `json:"last_update_time"`
	Source         string      `json:"source"`
	ExternalID     string      `json:"external_id"`
}

// =====================================================================
// GChat edit/delete reconciliation queries. Scoped by (source,
// external_id) so they hit ALL fanned-out rows for one upstream message
// (a message qualifying N contacts has N rows sharing external_id). All
// scope deleted_at IS NULL.
// =====================================================================
// Apply an upstream message edit to every stored row for (source, external_id).
// Updates body + snippet, pushes the row's prior body onto
// source_metadata.previous_bodies[] (newest-first, capped at the last 3), and
// records the edit's last_update_time + edited_at. processed_at, interaction_id,
// and deleted_at are deliberately left untouched: the aggregation engine skips
// rows with processed_at set, so a content edit never reprocesses the derived
// interaction.
//
// RECENCY + IDEMPOTENCY GUARD: the WHERE clause compares the stored
// last_update_time against @last_update_time as a TIMESTAMPTZ, not as a string.
// RFC-3339 is NOT lexicographically ordered when fractional-second precision
// varies (e.g. "...10:00:00Z" sorts after "...10:00:00.001Z" yet is earlier),
// so a string compare would silently reject a legitimate newer edit. Casting
// both sides to timestamptz compares real instants regardless of precision or
// offset. NULLIF(...,”)::timestamptz handles never-edited rows (absent/empty
// key -> NULL -> '-infinity' floor, so the first edit always passes). Because
// only the first writer advances last_update_time, two connected accounts
// observing the same edit in concurrent sweeps each attempt the UPDATE but only
// one pushes previous_bodies[] — the second's predicate is false (0 rows).
//
// previous_bodies[] cap: prepend the row's CURRENT body (the soon-to-be-prior
// value), then keep the first 3 elements (newest-first). A NULL current body is
// not pushed (nothing to preserve).
func (q *Queries) ApplyCommsMessageEditByExternalID(ctx context.Context, arg ApplyCommsMessageEditByExternalIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, ApplyCommsMessageEditByExternalID,
		arg.Body,
		arg.Snippet,
		arg.EditedAt,
		arg.LastUpdateTime,
		arg.Source,
		arg.ExternalID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const BackdateCommsMessageClaim = `-- name: BackdateCommsMessageClaim :exec
UPDATE comms_message
SET claimed_at = NOW() - INTERVAL '10 minutes'
WHERE id = ANY($1::uuid[])
`

// Test-only helper: ages the claim past the 5-minute TTL so a fresh
// aggregate pass can re-claim a stale claim. Mirror of
// BackdateMessagesMessageClaim. Production code MUST NOT call this.
func (q *Queries) BackdateCommsMessageClaim(ctx context.Context, messageIds []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, BackdateCommsMessageClaim, messageIds)
	return err
}

const BackfillCommsMessageParticipantNames = `-- name: BackfillCommsMessageParticipantNames :execrows
UPDATE comms_message
SET source_metadata = jsonb_set(
    jsonb_set(
        jsonb_set(
            jsonb_set(
                source_metadata,
                '{from_name}',
                to_jsonb($1::text),
                TRUE
            ),
            '{to_names}',
            $2::jsonb,
            TRUE
        ),
        '{cc_names}',
        $3::jsonb,
        TRUE
    ),
    '{bcc_names}',
    $4::jsonb,
    TRUE
)
WHERE id = $5
  AND deleted_at IS NULL
  AND NOT (source_metadata ? 'from_name')
`

type BackfillCommsMessageParticipantNamesParams struct {
	FromName string      `json:"from_name"`
	ToNames  []byte      `json:"to_names"`
	CcNames  []byte      `json:"cc_names"`
	BccNames []byte      `json:"bcc_names"`
	ID       pgtype.UUID `json:"id"`
}

// Additively merge the four display-name keys onto an EXISTING row's stored
// source_metadata, preserving every existing content key (from/to/cc/bcc/
// subject/html/attachments/labels) and the provenance keys (observed_accounts/
// account_gmail_ids). A nested jsonb_set chain (create_missing=true per key) —
// NOT a wholesale replace, which would destroy provenance + content. The caller
// passes non-NULL JSON arrays ([] when empty) for *_names so jsonb_set never
// writes a JSON null. Guarded by NOT (? 'from_name') so a row already
// re-derived (or concurrently re-ingested with names) is a no-op (0 rows) —
// idempotent across runs.
func (q *Queries) BackfillCommsMessageParticipantNames(ctx context.Context, arg BackfillCommsMessageParticipantNamesParams) (int64, error) {
	result, err := q.db.Exec(ctx, BackfillCommsMessageParticipantNames,
		arg.FromName,
		arg.ToNames,
		arg.CcNames,
		arg.BccNames,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ClaimCommsMessages = `-- name: ClaimCommsMessages :many
UPDATE comms_message
SET claimed_at = NOW(),
    claimed_session_ref = $1
WHERE id = ANY($2::uuid[])
  AND processed_at IS NULL
  AND (claimed_at IS NULL OR claimed_at < NOW() - INTERVAL '5 minutes')
  AND deleted_at IS NULL
RETURNING id
`

type ClaimCommsMessagesParams struct {
	SessionRef pgtype.Text   `json:"session_ref"`
	MessageIds []pgtype.UUID `json:"message_ids"`
}

// Race-safe conditional claim — mirror of ClaimMessagesMessages. No @source
// filter needed: id is the PK and globally unique; the caller already scoped to
// source when it listed the rows. Returns the IDs actually claimed so the engine
// can detect partial claims.
func (q *Queries) ClaimCommsMessages(ctx context.Context, arg ClaimCommsMessagesParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, ClaimCommsMessages, arg.SessionRef, arg.MessageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ClearStaleCommsClaim = `-- name: ClearStaleCommsClaim :exec
UPDATE comms_message
SET claimed_at = NULL,
    claimed_session_ref = NULL
WHERE id = ANY($1::uuid[])
  AND claimed_session_ref = $2
  AND processed_at IS NULL
  AND deleted_at IS NULL
`

type ClearStaleCommsClaimParams struct {
	MessageIds         []pgtype.UUID `json:"message_ids"`
	ExpectedSessionRef pgtype.Text   `json:"expected_session_ref"`
}

// Defensive recovery branch: clears claim columns for rows still carrying the
// expected stale session_ref. Mirror of ClearMessagesMessageStaleClaim. Used
// when the engine detected a recovery pass but FindEventBySource returned no
// row.
func (q *Queries) ClearStaleCommsClaim(ctx context.Context, arg ClearStaleCommsClaimParams) error {
	_, err := q.db.Exec(ctx, ClearStaleCommsClaim, arg.MessageIds, arg.ExpectedSessionRef)
	return err
}

const GetCommsMessage = `-- name: GetCommsMessage :one
SELECT id, source, external_id, thread_id, subject, body, snippet, peer_handle, peer_normalized, direction, sent_at, account_id, source_metadata, matched_contact_id, interaction_id, claimed_at, claimed_session_ref, processed_at, deleted_at, created_at FROM comms_message
WHERE source = $1
  AND external_id = $2
  AND matched_contact_id = $3
  AND deleted_at IS NULL
`

type GetCommsMessageParams struct {
	Source           string      `json:"source"`
	ExternalID       string      `json:"external_id"`
	MatchedContactID pgtype.UUID `json:"matched_contact_id"`
}

// Natural-key lookup used by the email interaction consumer to locate the
// content row for a (source, external_id, contact) tuple. deleted_at filtered.
func (q *Queries) GetCommsMessage(ctx context.Context, arg GetCommsMessageParams) (*CommsMessage, error) {
	row := q.db.QueryRow(ctx, GetCommsMessage, arg.Source, arg.ExternalID, arg.MatchedContactID)
	var i CommsMessage
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.ThreadID,
		&i.Subject,
		&i.Body,
		&i.Snippet,
		&i.PeerHandle,
		&i.PeerNormalized,
		&i.Direction,
		&i.SentAt,
		&i.AccountID,
		&i.SourceMetadata,
		&i.MatchedContactID,
		&i.InteractionID,
		&i.ClaimedAt,
		&i.ClaimedSessionRef,
		&i.ProcessedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const GetCommsMessageByID = `-- name: GetCommsMessageByID :one
SELECT id, source, external_id, thread_id, subject, body, snippet, peer_handle, peer_normalized, direction, sent_at, account_id, source_metadata, matched_contact_id, interaction_id, claimed_at, claimed_session_ref, processed_at, deleted_at, created_at FROM comms_message
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetCommsMessageByID(ctx context.Context, id pgtype.UUID) (*CommsMessage, error) {
	row := q.db.QueryRow(ctx, GetCommsMessageByID, id)
	var i CommsMessage
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.ThreadID,
		&i.Subject,
		&i.Body,
		&i.Snippet,
		&i.PeerHandle,
		&i.PeerNormalized,
		&i.Direction,
		&i.SentAt,
		&i.AccountID,
		&i.SourceMetadata,
		&i.MatchedContactID,
		&i.InteractionID,
		&i.ClaimedAt,
		&i.ClaimedSessionRef,
		&i.ProcessedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const GetCommsMessageByReplyTarget = `-- name: GetCommsMessageByReplyTarget :one
SELECT id, source, external_id, thread_id, subject, body, snippet, peer_handle, peer_normalized, direction, sent_at, account_id, source_metadata, matched_contact_id, interaction_id, claimed_at, claimed_session_ref, processed_at, deleted_at, created_at FROM comms_message
WHERE source = $1
  AND matched_contact_id = $2
  AND thread_id = $3
  AND external_id = $4
  AND deleted_at IS NULL
`

type GetCommsMessageByReplyTargetParams struct {
	Source           string      `json:"source"`
	MatchedContactID pgtype.UUID `json:"matched_contact_id"`
	ThreadID         pgtype.Text `json:"thread_id"`
	ReplyTargetID    string      `json:"reply_target_id"`
}

// Resolves the row a reply points at. comms_message has NO reply_to column;
// the reply target is itself a stored message, looked up by its own external_id
// within the same (source, contact, thread/chat) scope. Used by the
// aggregator's explicit-reply-bridge path. Scoping to matched_contact_id is
// load-bearing: comms_message is per-contact (a shared address fans out to one
// row per matched contact), so an unscoped lookup could return a DIFFERENT
// contact's row, whose interaction_id points at that other contact's
// interaction — which the bridge would then wrongly promote to mutual.
// Intentionally does NOT filter processed_at — a reply can target an
// already-processed message (the whole point of bridging).
func (q *Queries) GetCommsMessageByReplyTarget(ctx context.Context, arg GetCommsMessageByReplyTargetParams) (*CommsMessage, error) {
	row := q.db.QueryRow(ctx, GetCommsMessageByReplyTarget,
		arg.Source,
		arg.MatchedContactID,
		arg.ThreadID,
		arg.ReplyTargetID,
	)
	var i CommsMessage
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.ThreadID,
		&i.Subject,
		&i.Body,
		&i.Snippet,
		&i.PeerHandle,
		&i.PeerNormalized,
		&i.Direction,
		&i.SentAt,
		&i.AccountID,
		&i.SourceMetadata,
		&i.MatchedContactID,
		&i.InteractionID,
		&i.ClaimedAt,
		&i.ClaimedSessionRef,
		&i.ProcessedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const GetCommsMessageContainer = `-- name: GetCommsMessageContainer :one
SELECT source, thread_id
FROM comms_message
WHERE id = $1
`

type GetCommsMessageContainerRow struct {
	Source   string      `json:"source"`
	ThreadID pgtype.Text `json:"thread_id"`
}

// Returns the venue-container key (source + thread_id) for a staging row by its
// UUID. Used by the live interaction recorder to resolve the gchat venue (email
// resolves its venue from the EmailInteractionConsumer's comms row directly).
// The thread is consistent across all messages in one aggregated session, so
// reading the first id is sufficient.
func (q *Queries) GetCommsMessageContainer(ctx context.Context, id pgtype.UUID) (*GetCommsMessageContainerRow, error) {
	row := q.db.QueryRow(ctx, GetCommsMessageContainer, id)
	var i GetCommsMessageContainerRow
	err := row.Scan(&i.Source, &i.ThreadID)
	return &i, err
}

const GetCommsMessageLatestByExternalID = `-- name: GetCommsMessageLatestByExternalID :one
SELECT id, source, external_id, thread_id, subject, body, snippet, peer_handle, peer_normalized, direction, sent_at, account_id, source_metadata, matched_contact_id, interaction_id, claimed_at, claimed_session_ref, processed_at, deleted_at, created_at FROM comms_message
WHERE source = $1
  AND external_id = $2
  AND deleted_at IS NULL
ORDER BY sent_at DESC, id
LIMIT 1
`

type GetCommsMessageLatestByExternalIDParams struct {
	Source     string `json:"source"`
	ExternalID string `json:"external_id"`
}

// Read one stored row for (source, external_id), newest first, to supply the
// current body for the provider's bodyDiffers no-op-avoidance pre-check. Fanned-
// out rows share content, so any one row suffices. Used ONLY for body
// comparison — NEVER for a Go-side timestamp/recency comparison (recency is the
// SQL ::timestamptz guard in ApplyCommsMessageEditByExternalID).
func (q *Queries) GetCommsMessageLatestByExternalID(ctx context.Context, arg GetCommsMessageLatestByExternalIDParams) (*CommsMessage, error) {
	row := q.db.QueryRow(ctx, GetCommsMessageLatestByExternalID, arg.Source, arg.ExternalID)
	var i CommsMessage
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.ThreadID,
		&i.Subject,
		&i.Body,
		&i.Snippet,
		&i.PeerHandle,
		&i.PeerNormalized,
		&i.Direction,
		&i.SentAt,
		&i.AccountID,
		&i.SourceMetadata,
		&i.MatchedContactID,
		&i.InteractionID,
		&i.ClaimedAt,
		&i.ClaimedSessionRef,
		&i.ProcessedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const HardDeleteCommsMessagesByContact = `-- name: HardDeleteCommsMessagesByContact :exec
DELETE FROM comms_message
WHERE matched_contact_id = $1
`

// Test-only cleanup helper (scoped by matched_contact_id). Hard delete because
// the upsert does not clear deleted_at on conflict, so soft-deleted rows would
// resurrect across shared-DB test runs (gotcha table). Production code MUST NOT
// call this.
func (q *Queries) HardDeleteCommsMessagesByContact(ctx context.Context, matchedContactID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, HardDeleteCommsMessagesByContact, matchedContactID)
	return err
}

const ListCommsMessagesByContact = `-- name: ListCommsMessagesByContact :many
SELECT id, source, external_id, thread_id, subject, body, snippet, peer_handle, peer_normalized, direction, sent_at, account_id, source_metadata, matched_contact_id, interaction_id, claimed_at, claimed_session_ref, processed_at, deleted_at, created_at FROM comms_message
WHERE matched_contact_id = $1
  AND deleted_at IS NULL
ORDER BY sent_at DESC, id
`

// Per-contact content, newest first (backs idx_comms_message_contact_sent).
func (q *Queries) ListCommsMessagesByContact(ctx context.Context, matchedContactID pgtype.UUID) ([]*CommsMessage, error) {
	rows, err := q.db.Query(ctx, ListCommsMessagesByContact, matchedContactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*CommsMessage{}
	for rows.Next() {
		var i CommsMessage
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.ThreadID,
			&i.Subject,
			&i.Body,
			&i.Snippet,
			&i.PeerHandle,
			&i.PeerNormalized,
			&i.Direction,
			&i.SentAt,
			&i.AccountID,
			&i.SourceMetadata,
			&i.MatchedContactID,
			&i.InteractionID,
			&i.ClaimedAt,
			&i.ClaimedSessionRef,
			&i.ProcessedAt,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListCommsMessagesMissingParticipantNames = `-- name: ListCommsMessagesMissingParticipantNames :many
SELECT cm.id, cm.account_id, cm.source_metadata
FROM comms_message cm
JOIN contact c ON c.id = cm.matched_contact_id AND c.deleted_at IS NULL
WHERE cm.source = 'email'
  AND cm.deleted_at IS NULL
  AND cm.sent_at >= $1
  AND cm.id > $2
  AND NOT (cm.source_metadata ? 'from_name')
ORDER BY cm.id
LIMIT $3
`

type ListCommsMessagesMissingParticipantNamesParams struct {
	Since     pgtype.Timestamptz `json:"since"`
	AfterID   pgtype.UUID        `json:"after_id"`
	BatchSize int32              `json:"batch_size"`
}

type ListCommsMessagesMissingParticipantNamesRow struct {
	ID             pgtype.UUID `json:"id"`
	AccountID      pgtype.Text `json:"account_id"`
	SourceMetadata []byte      `json:"source_metadata"`
}

// Keyset-paged rows for the one-time historical display-name re-derivation
// (crm-admin --rederive-correspondence-names). Returns email rows at/after
// @since that lack the from_name key (i.e. ingested before display-name
// capture shipped), paged by id > @after_id so the runner advances the cursor
// regardless of per-row outcome — a skipped/failed row never blocks later rows
// (livelock avoidance). account_id + source_metadata.account_gmail_ids together
// locate the per-mailbox gmail id to re-fetch. The INNER JOIN on a live contact
// drops rows whose matched contact was soft-deleted (soft-delete does not cascade
// to comms_message), so the re-derivation never spends Gmail quota re-fetching
// mail for a deleted contact.
func (q *Queries) ListCommsMessagesMissingParticipantNames(ctx context.Context, arg ListCommsMessagesMissingParticipantNamesParams) ([]*ListCommsMessagesMissingParticipantNamesRow, error) {
	rows, err := q.db.Query(ctx, ListCommsMessagesMissingParticipantNames, arg.Since, arg.AfterID, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListCommsMessagesMissingParticipantNamesRow{}
	for rows.Next() {
		var i ListCommsMessagesMissingParticipantNamesRow
		if err := rows.Scan(&i.ID, &i.AccountID, &i.SourceMetadata); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUnprocessedCommsByContact = `-- name: ListUnprocessedCommsByContact :many
SELECT id, source, external_id, thread_id, subject, body, snippet, peer_handle, peer_normalized, direction, sent_at, account_id, source_metadata, matched_contact_id, interaction_id, claimed_at, claimed_session_ref, processed_at, deleted_at, created_at FROM comms_message
WHERE source = $1
  AND matched_contact_id = $2
  AND processed_at IS NULL
  AND (claimed_at IS NULL OR claimed_at < NOW() - INTERVAL '5 minutes')
  AND deleted_at IS NULL
ORDER BY thread_id, sent_at
`

type ListUnprocessedCommsByContactParams struct {
	Source           string      `json:"source"`
	MatchedContactID pgtype.UUID `json:"matched_contact_id"`
}

// Eligible rows for a contact within one source. Orders by thread_id then
// sent_at — thread_id carries the chat scope, mirroring messages' ORDER BY
// chat_guid, sent_at.
func (q *Queries) ListUnprocessedCommsByContact(ctx context.Context, arg ListUnprocessedCommsByContactParams) ([]*CommsMessage, error) {
	rows, err := q.db.Query(ctx, ListUnprocessedCommsByContact, arg.Source, arg.MatchedContactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*CommsMessage{}
	for rows.Next() {
		var i CommsMessage
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.ThreadID,
			&i.Subject,
			&i.Body,
			&i.Snippet,
			&i.PeerHandle,
			&i.PeerNormalized,
			&i.Direction,
			&i.SentAt,
			&i.AccountID,
			&i.SourceMetadata,
			&i.MatchedContactID,
			&i.InteractionID,
			&i.ClaimedAt,
			&i.ClaimedSessionRef,
			&i.ProcessedAt,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUnprocessedCommsByContactAndChat = `-- name: ListUnprocessedCommsByContactAndChat :many
SELECT id, source, external_id, thread_id, subject, body, snippet, peer_handle, peer_normalized, direction, sent_at, account_id, source_metadata, matched_contact_id, interaction_id, claimed_at, claimed_session_ref, processed_at, deleted_at, created_at FROM comms_message
WHERE source = $1
  AND matched_contact_id = $2
  AND thread_id = $3
  AND processed_at IS NULL
  AND (claimed_at IS NULL OR claimed_at < NOW() - INTERVAL '5 minutes')
  AND deleted_at IS NULL
ORDER BY sent_at
`

type ListUnprocessedCommsByContactAndChatParams struct {
	Source           string      `json:"source"`
	MatchedContactID pgtype.UUID `json:"matched_contact_id"`
	ThreadID         pgtype.Text `json:"thread_id"`
}

// Eligible rows for a (contact, thread/chat) pair within one source.
// @thread_id is the chat scope (the GChat space resource name).
func (q *Queries) ListUnprocessedCommsByContactAndChat(ctx context.Context, arg ListUnprocessedCommsByContactAndChatParams) ([]*CommsMessage, error) {
	rows, err := q.db.Query(ctx, ListUnprocessedCommsByContactAndChat, arg.Source, arg.MatchedContactID, arg.ThreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*CommsMessage{}
	for rows.Next() {
		var i CommsMessage
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.ThreadID,
			&i.Subject,
			&i.Body,
			&i.Snippet,
			&i.PeerHandle,
			&i.PeerNormalized,
			&i.Direction,
			&i.SentAt,
			&i.AccountID,
			&i.SourceMetadata,
			&i.MatchedContactID,
			&i.InteractionID,
			&i.ClaimedAt,
			&i.ClaimedSessionRef,
			&i.ProcessedAt,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUnprocessedCommsChatsByContact = `-- name: ListUnprocessedCommsChatsByContact :many
SELECT DISTINCT thread_id
FROM comms_message
WHERE source = $1
  AND matched_contact_id = $2
  AND processed_at IS NULL
  AND (claimed_at IS NULL OR claimed_at < NOW() - INTERVAL '5 minutes')
  AND deleted_at IS NULL
ORDER BY thread_id ASC
`

type ListUnprocessedCommsChatsByContactParams struct {
	Source           string      `json:"source"`
	MatchedContactID pgtype.UUID `json:"matched_contact_id"`
}

// Distinct thread_id (chat scope) values for a contact with at least one
// eligible row within one source. Backs the PerSourceChatListerRegistry entry
// (the worker's per-chat loop), mirroring ListUnprocessedMessagesChatsByContact.
// NOT a MessageStore interface method. thread_id is nullable on comms_message;
// the Go wrapper filters NULLs defensively (chat sources always write it
// non-null).
func (q *Queries) ListUnprocessedCommsChatsByContact(ctx context.Context, arg ListUnprocessedCommsChatsByContactParams) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, ListUnprocessedCommsChatsByContact, arg.Source, arg.MatchedContactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var thread_id pgtype.Text
		if err := rows.Scan(&thread_id); err != nil {
			return nil, err
		}
		items = append(items, thread_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUnprocessedCommsContactIDs = `-- name: ListUnprocessedCommsContactIDs :many

SELECT DISTINCT matched_contact_id
FROM comms_message
WHERE source = $1
  AND matched_contact_id IS NOT NULL
  AND processed_at IS NULL
  AND (claimed_at IS NULL OR claimed_at < NOW() - INTERVAL '5 minutes')
  AND deleted_at IS NULL
`

// =====================================================================
// Source-parameterized aggregation-engine queries (GChat is the first
// chat source on comms_message; Telegram/Messages migrate onto these
// later). Every query takes @source so the shared comms_message table
// isolates rows by source. Predicate shapes mirror messages_message.sql
// verbatim; the only structural difference is the @source filter and the
// thread_id column (vs. messages' chat_guid). All scope deleted_at IS NULL.
// =====================================================================
// Claim-aware filter — same predicate shape as ListUnprocessedMessagesContactIDs,
// plus the @source scope. matched_contact_id is NOT NULL on comms_message;
// the IS NOT NULL guard is retained for parity/safety (harmless).
func (q *Queries) ListUnprocessedCommsContactIDs(ctx context.Context, source string) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, ListUnprocessedCommsContactIDs, source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var matched_contact_id pgtype.UUID
		if err := rows.Scan(&matched_contact_id); err != nil {
			return nil, err
		}
		items = append(items, matched_contact_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkCommsMessagesProcessed = `-- name: MarkCommsMessagesProcessed :execrows
UPDATE comms_message
SET processed_at = NOW(),
    interaction_id = $1,
    claimed_at = NULL,
    claimed_session_ref = NULL
WHERE id = ANY($2::uuid[])
  AND processed_at IS NULL
  AND deleted_at IS NULL
`

type MarkCommsMessagesProcessedParams struct {
	InteractionID pgtype.UUID   `json:"interaction_id"`
	MessageIds    []pgtype.UUID `json:"message_ids"`
}

// Link content rows to the aggregated interaction + set processed_at, AND
// clear claim columns. Two callers:
//   - email path (CommsStagingProcessor, tx-bound, via the email consumer):
//     email never claims rows, so the claim-clear is a provable NULL → NULL
//     no-op for email rows. There is NO session-scope predicate here (unlike
//     messages_message): the @session_ref arg is part of the shared
//     StagingProcessor signature but intentionally unused in the email path.
//   - chat non-tx engine path (commsMessageStoreAdapter.MarkProcessed, used by
//     the engine's extend/promote/bridge paths): those paths do not claim rows
//     or publish events, so the claim-clear keeps any leftover claim from a
//     prior pass from re-blocking the row. Mirrors MarkMessagesMessagesProcessed.
//
// Idempotent: a replay finds rows already processed (processed_at IS NOT NULL)
// and affects 0 rows, which the consumer treats as the expected replay case.
func (q *Queries) MarkCommsMessagesProcessed(ctx context.Context, arg MarkCommsMessagesProcessedParams) (int64, error) {
	result, err := q.db.Exec(ctx, MarkCommsMessagesProcessed, arg.InteractionID, arg.MessageIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const MarkCommsMessagesProcessedForSession = `-- name: MarkCommsMessagesProcessedForSession :execrows
UPDATE comms_message
SET processed_at = NOW(),
    interaction_id = $1,
    claimed_at = NULL,
    claimed_session_ref = NULL
WHERE id = ANY($2::uuid[])
  AND (claimed_session_ref = $3 OR claimed_session_ref IS NULL)
  AND processed_at IS NULL
  AND deleted_at IS NULL
`

type MarkCommsMessagesProcessedForSessionParams struct {
	InteractionID pgtype.UUID   `json:"interaction_id"`
	MessageIds    []pgtype.UUID `json:"message_ids"`
	SessionRef    pgtype.Text   `json:"session_ref"`
}

// Tx-bound, session-scoped variant for the chat create-path. Mirror of
// MarkMessagesMessagesProcessedForSession — used by the InteractionRecorder
// consumer (via CommsSessionStagingProcessor) when processing a create-path
// event. The (claimed_session_ref = @session_ref OR IS NULL) predicate is the
// boundary-shift defense the recorder's zero-rows-affected rollback depends on:
// it rejects rows claimed for a DIFFERENT session while accepting rows the
// non-tx publish path left unclaimed. This is SEPARATE from the email
// MarkCommsMessagesProcessed (which has no session predicate — email never
// claims, so scoping by session would wrongly reject email rows).
//
// Returns rows affected. The consumer distinguishes three cases:
//   - affected == len(message_ids): happy path.
//   - affected == 0 on a fresh write: predicate filtered everything out
//     (boundary-shift race). Caller MUST roll back the tx.
//   - affected == 0 on a replay: expected; rows already linked on the
//     original attempt.
func (q *Queries) MarkCommsMessagesProcessedForSession(ctx context.Context, arg MarkCommsMessagesProcessedForSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, MarkCommsMessagesProcessedForSession, arg.InteractionID, arg.MessageIds, arg.SessionRef)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SoftDeleteCommsMessageByID = `-- name: SoftDeleteCommsMessageByID :exec
UPDATE comms_message
SET deleted_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

// Test-only helper: soft-deletes a single comms_message row by id, simulating
// the upstream delete a chat provider would observe. Used by the delete-no-op
// aggregation test. There is no production chat delete path yet.
func (q *Queries) SoftDeleteCommsMessageByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, SoftDeleteCommsMessageByID, id)
	return err
}

const SoftDeleteCommsMessagesByExternalID = `-- name: SoftDeleteCommsMessagesByExternalID :execrows
UPDATE comms_message
SET deleted_at = $1
WHERE source = $2
  AND external_id = $3
  AND deleted_at IS NULL
`

type SoftDeleteCommsMessagesByExternalIDParams struct {
	Now        pgtype.Timestamptz `json:"now"`
	Source     string             `json:"source"`
	ExternalID string             `json:"external_id"`
}

// Soft-delete every stored row for (source, external_id) — the production chat
// delete path. Scoped by (source, external_id) so all fanned-out contacts'
// rows drop out of future aggregation. Idempotent: an already-deleted message
// affects 0 rows.
func (q *Queries) SoftDeleteCommsMessagesByExternalID(ctx context.Context, arg SoftDeleteCommsMessagesByExternalIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, SoftDeleteCommsMessagesByExternalID, arg.Now, arg.Source, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const TestInsertCommsMessageLinked = `-- name: TestInsertCommsMessageLinked :one
INSERT INTO comms_message (
    source, external_id, thread_id, direction, sent_at, matched_contact_id, interaction_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, source, external_id, thread_id, subject, body, snippet, peer_handle, peer_normalized, direction, sent_at, account_id, source_metadata, matched_contact_id, interaction_id, claimed_at, claimed_session_ref, processed_at, deleted_at, created_at
`

type TestInsertCommsMessageLinkedParams struct {
	Source           string             `json:"source"`
	ExternalID       string             `json:"external_id"`
	ThreadID         pgtype.Text        `json:"thread_id"`
	Direction        string             `json:"direction"`
	SentAt           pgtype.Timestamptz `json:"sent_at"`
	MatchedContactID pgtype.UUID        `json:"matched_contact_id"`
	InteractionID    pgtype.UUID        `json:"interaction_id"`
}

// Test-only: inserts a comms_message already linked to an interaction. Used by
// the venue backfill test to seed an email/gchat thread container row.
// Production code MUST NOT call this.
func (q *Queries) TestInsertCommsMessageLinked(ctx context.Context, arg TestInsertCommsMessageLinkedParams) (*CommsMessage, error) {
	row := q.db.QueryRow(ctx, TestInsertCommsMessageLinked,
		arg.Source,
		arg.ExternalID,
		arg.ThreadID,
		arg.Direction,
		arg.SentAt,
		arg.MatchedContactID,
		arg.InteractionID,
	)
	var i CommsMessage
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.ThreadID,
		&i.Subject,
		&i.Body,
		&i.Snippet,
		&i.PeerHandle,
		&i.PeerNormalized,
		&i.Direction,
		&i.SentAt,
		&i.AccountID,
		&i.SourceMetadata,
		&i.MatchedContactID,
		&i.InteractionID,
		&i.ClaimedAt,
		&i.ClaimedSessionRef,
		&i.ProcessedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const UpsertCommsMessage = `-- name: UpsertCommsMessage :one
INSERT INTO comms_message (
    source, external_id, thread_id, subject, body, snippet,
    peer_handle, peer_normalized, direction, sent_at, account_id,
    source_metadata, matched_contact_id
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    -- LEVEL 3 (outermost): set the per-account gmail id under
    -- account_gmail_ids.<account_id>. Lands only because LEVEL 2 seeded the
    -- parent object first (jsonb_set does NOT create intermediate parents).
    jsonb_set(
        -- LEVEL 2: SEED the account_gmail_ids parent to its existing value (or
        -- '{}'). REQUIRED — without it, level 3's nested-path set is a silent
        -- no-op and the gmail-id map is dropped.
        jsonb_set(
            -- LEVEL 1 (innermost): union observed_accounts[] into the caller's
            -- metadata (add @account_id only if absent).
            jsonb_set(
                $12::jsonb,
                '{observed_accounts}',
                CASE
                    WHEN $11::text IS NULL THEN
                        COALESCE($12::jsonb->'observed_accounts', '[]'::jsonb)
                    WHEN COALESCE($12::jsonb->'observed_accounts', '[]'::jsonb)
                         @> to_jsonb(ARRAY[$11::text]) THEN
                        COALESCE($12::jsonb->'observed_accounts', '[]'::jsonb)
                    ELSE
                        COALESCE($12::jsonb->'observed_accounts', '[]'::jsonb)
                            || to_jsonb(ARRAY[$11::text])
                END,
                TRUE
            ),
            '{account_gmail_ids}',
            COALESCE($12::jsonb->'account_gmail_ids', '{}'::jsonb),
            TRUE
        ),
        ARRAY['account_gmail_ids', COALESCE($11::text, '__unknown__')],
        to_jsonb($13::text),
        TRUE
    ),
    $14
)
ON CONFLICT (source, external_id, matched_contact_id) WHERE deleted_at IS NULL
DO UPDATE SET
    -- Identical three-level merge, applied to the STORED metadata so the
    -- conflicting account's provenance is unioned in without disturbing the
    -- first writer's content keys.
    source_metadata = jsonb_set(
        jsonb_set(
            jsonb_set(
                comms_message.source_metadata,
                '{observed_accounts}',
                CASE
                    WHEN $11::text IS NULL THEN
                        COALESCE(comms_message.source_metadata->'observed_accounts', '[]'::jsonb)
                    WHEN COALESCE(comms_message.source_metadata->'observed_accounts', '[]'::jsonb)
                         @> to_jsonb(ARRAY[$11::text]) THEN
                        COALESCE(comms_message.source_metadata->'observed_accounts', '[]'::jsonb)
                    ELSE
                        COALESCE(comms_message.source_metadata->'observed_accounts', '[]'::jsonb)
                            || to_jsonb(ARRAY[$11::text])
                END,
                TRUE
            ),
            '{account_gmail_ids}',
            COALESCE(comms_message.source_metadata->'account_gmail_ids', '{}'::jsonb),
            TRUE
        ),
        ARRAY['account_gmail_ids', COALESCE($11::text, '__unknown__')],
        to_jsonb($13::text),
        TRUE
    )
WHERE comms_message.deleted_at IS NULL
RETURNING id, source, external_id, thread_id, subject, body, snippet, peer_handle, peer_normalized, direction, sent_at, account_id, source_metadata, matched_contact_id, interaction_id, claimed_at, claimed_session_ref, processed_at, deleted_at, created_at
`

type UpsertCommsMessageParams struct {
	Source           string             `json:"source"`
	ExternalID       string             `json:"external_id"`
	ThreadID         pgtype.Text        `json:"thread_id"`
	Subject          pgtype.Text        `json:"subject"`
	Body             pgtype.Text        `json:"body"`
	Snippet          pgtype.Text        `json:"snippet"`
	PeerHandle       pgtype.Text        `json:"peer_handle"`
	PeerNormalized   pgtype.Text        `json:"peer_normalized"`
	Direction        string             `json:"direction"`
	SentAt           pgtype.Timestamptz `json:"sent_at"`
	AccountID        pgtype.Text        `json:"account_id"`
	SourceMetadata   []byte             `json:"source_metadata"`
	GmailMessageID   string             `json:"gmail_message_id"`
	MatchedContactID pgtype.UUID        `json:"matched_contact_id"`
}

// Insert-or-merge by the partial unique (source, external_id, matched_contact_id)
// WHERE deleted_at IS NULL. Content fields are IMMUTABLE on conflict (first
// writer wins). Provenance is merged by SET-UNION on BOTH the insert and the
// conflict paths, so the observing account is recorded regardless of what
// @source_metadata the caller passes (even '{}' or NULL):
//   - add @account_id to source_metadata.observed_accounts[] only if absent
//   - record this account's per-mailbox gmail id under
//     source_metadata.account_gmail_ids.<account_id> (or '__unknown__' when the
//     account is NULL — the nomsgid/missing-account edge)
//
// The same three-level jsonb_set expression is applied to the caller's metadata
// on insert and to the stored metadata on conflict; non-provenance keys the
// caller supplies (html body, attachments[], labels, to/cc/bcc) are preserved.
// The merge is idempotent: a same-account cursor-overlap replay re-runs this
// upsert and neither grows observed_accounts[] (already present) nor changes
// the gmail-id (stable per account). The ON CONFLICT clause MUST name the
// partial index's WHERE predicate so Postgres infers the partial unique index.
func (q *Queries) UpsertCommsMessage(ctx context.Context, arg UpsertCommsMessageParams) (*CommsMessage, error) {
	row := q.db.QueryRow(ctx, UpsertCommsMessage,
		arg.Source,
		arg.ExternalID,
		arg.ThreadID,
		arg.Subject,
		arg.Body,
		arg.Snippet,
		arg.PeerHandle,
		arg.PeerNormalized,
		arg.Direction,
		arg.SentAt,
		arg.AccountID,
		arg.SourceMetadata,
		arg.GmailMessageID,
		arg.MatchedContactID,
	)
	var i CommsMessage
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.ThreadID,
		&i.Subject,
		&i.Body,
		&i.Snippet,
		&i.PeerHandle,
		&i.PeerNormalized,
		&i.Direction,
		&i.SentAt,
		&i.AccountID,
		&i.SourceMetadata,
		&i.MatchedContactID,
		&i.InteractionID,
		&i.ClaimedAt,
		&i.ClaimedSessionRef,
		&i.ProcessedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return &i, err
}
