// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contact_merge.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountMergeCalendarEvents = `-- name: CountMergeCalendarEvents :one
SELECT COUNT(*) FROM calendar_event
WHERE $1::uuid = ANY(matched_contact_ids)
`

// Count calendar events involving a contact (for merge preview)
func (q *Queries) CountMergeCalendarEvents(ctx context.Context, dollar_1 pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, CountMergeCalendarEvents, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountMergeContactMethods = `-- name: CountMergeContactMethods :one
SELECT COUNT(*) FROM contact_method
WHERE contact_id = $1
`

// Count contact methods for a contact (for merge preview)
func (q *Queries) CountMergeContactMethods(ctx context.Context, contactID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, CountMergeContactMethods, contactID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountMergeInteractions = `-- name: CountMergeInteractions :one
SELECT COUNT(*) FROM interaction
WHERE contact_id = $1
`

// Count interactions for a contact (for merge preview)
func (q *Queries) CountMergeInteractions(ctx context.Context, contactID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, CountMergeInteractions, contactID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountMergeNotes = `-- name: CountMergeNotes :one
SELECT COUNT(*) FROM note
WHERE contact_id = $1
`

// Count notes for a contact (for merge preview)
func (q *Queries) CountMergeNotes(ctx context.Context, contactID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, CountMergeNotes, contactID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const DeduplicateCalendarEventContacts = `-- name: DeduplicateCalendarEventContacts :exec
UPDATE calendar_event
SET matched_contact_ids = (
    SELECT array_agg(DISTINCT contact_id)
    FROM unnest(matched_contact_ids) AS contact_id
),
    updated_at = NOW()
WHERE $1::uuid = ANY(matched_contact_ids)
  AND (
    SELECT COUNT(*) FROM unnest(matched_contact_ids) AS cid WHERE cid = $1::uuid
  ) > 1
`

// Remove duplicate contact IDs that may result from merge
// Uses subquery with DISTINCT to rebuild the array without duplicates
func (q *Queries) DeduplicateCalendarEventContacts(ctx context.Context, targetContactID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeduplicateCalendarEventContacts, targetContactID)
	return err
}

const DeleteDuplicateConnections = `-- name: DeleteDuplicateConnections :exec
DELETE FROM connection
WHERE (contact_a_id = $1 AND contact_b_id = $2)
   OR (contact_a_id = $2 AND contact_b_id = $1)
`

type DeleteDuplicateConnectionsParams struct {
	SourceContactID pgtype.UUID `json:"source_contact_id"`
	TargetContactID pgtype.UUID `json:"target_contact_id"`
}

// Delete connections that would become duplicates after merge
// (connections between source and target, or connections that now point same way)
func (q *Queries) DeleteDuplicateConnections(ctx context.Context, arg DeleteDuplicateConnectionsParams) error {
	_, err := q.db.Exec(ctx, DeleteDuplicateConnections, arg.SourceContactID, arg.TargetContactID)
	return err
}

const DeleteDuplicateContactMethods = `-- name: DeleteDuplicateContactMethods :exec
DELETE FROM contact_method cm_source
WHERE cm_source.contact_id = $1
  AND EXISTS (
    SELECT 1 FROM contact_method cm_target
    WHERE cm_target.contact_id = $2
      AND cm_target.value_normalized = cm_source.value_normalized
      AND cm_target.type = cm_source.type
  )
`

type DeleteDuplicateContactMethodsParams struct {
	SourceContactID pgtype.UUID `json:"source_contact_id"`
	TargetContactID pgtype.UUID `json:"target_contact_id"`
}

// Delete contact methods from source that already exist in target (by normalized value and type)
func (q *Queries) DeleteDuplicateContactMethods(ctx context.Context, arg DeleteDuplicateContactMethodsParams) error {
	_, err := q.db.Exec(ctx, DeleteDuplicateContactMethods, arg.SourceContactID, arg.TargetContactID)
	return err
}

const DeleteDuplicateThirdPartyConnectionsA = `-- name: DeleteDuplicateThirdPartyConnectionsA :exec
DELETE FROM connection conn_source
WHERE conn_source.contact_a_id = $1
  AND conn_source.contact_b_id IN (
    SELECT conn_target.contact_b_id FROM connection conn_target
    WHERE conn_target.contact_a_id = $2
  )
`

type DeleteDuplicateThirdPartyConnectionsAParams struct {
	SourceContactID pgtype.UUID `json:"source_contact_id"`
	TargetContactID pgtype.UUID `json:"target_contact_id"`
}

// Delete source's connections (as contact_a) where target already connects to the same contact_b
// Prevents duplicate (target, X) rows after transfer
func (q *Queries) DeleteDuplicateThirdPartyConnectionsA(ctx context.Context, arg DeleteDuplicateThirdPartyConnectionsAParams) error {
	_, err := q.db.Exec(ctx, DeleteDuplicateThirdPartyConnectionsA, arg.SourceContactID, arg.TargetContactID)
	return err
}

const DeleteDuplicateThirdPartyConnectionsB = `-- name: DeleteDuplicateThirdPartyConnectionsB :exec
DELETE FROM connection conn_source
WHERE conn_source.contact_b_id = $1
  AND conn_source.contact_a_id IN (
    SELECT conn_target.contact_a_id FROM connection conn_target
    WHERE conn_target.contact_b_id = $2
  )
`

type DeleteDuplicateThirdPartyConnectionsBParams struct {
	SourceContactID pgtype.UUID `json:"source_contact_id"`
	TargetContactID pgtype.UUID `json:"target_contact_id"`
}

// Delete source's connections (as contact_b) where target already connects to the same contact_a
// Prevents duplicate (X, target) rows after transfer
func (q *Queries) DeleteDuplicateThirdPartyConnectionsB(ctx context.Context, arg DeleteDuplicateThirdPartyConnectionsBParams) error {
	_, err := q.db.Exec(ctx, DeleteDuplicateThirdPartyConnectionsB, arg.SourceContactID, arg.TargetContactID)
	return err
}

const DemoteSourcePrimaryMethods = `-- name: DemoteSourcePrimaryMethods :exec
UPDATE contact_method cm_source
SET is_primary = false,
    updated_at = NOW()
WHERE cm_source.contact_id = $1
  AND cm_source.is_primary = true
  AND cm_source.type IN (
    SELECT cm_target.type FROM contact_method cm_target
    WHERE cm_target.contact_id = $2
      AND cm_target.is_primary = true
  )
`

type DemoteSourcePrimaryMethodsParams struct {
	SourceContactID pgtype.UUID `json:"source_contact_id"`
	TargetContactID pgtype.UUID `json:"target_contact_id"`
}

// Demote source's primary contact methods when target already has a primary for that type
// This prevents violation of the unique partial index on (contact_id, type) WHERE is_primary = true
func (q *Queries) DemoteSourcePrimaryMethods(ctx context.Context, arg DemoteSourcePrimaryMethodsParams) error {
	_, err := q.db.Exec(ctx, DemoteSourcePrimaryMethods, arg.SourceContactID, arg.TargetContactID)
	return err
}

const FindDuplicateContactMethods = `-- name: FindDuplicateContactMethods :many
SELECT cm_source.value, cm_source.type
FROM contact_method cm_source
INNER JOIN contact_method cm_target
  ON cm_source.value_normalized = cm_target.value_normalized
  AND cm_source.type = cm_target.type
WHERE cm_source.contact_id = $1
  AND cm_target.contact_id = $2
`

type FindDuplicateContactMethodsParams struct {
	SourceContactID pgtype.UUID `json:"source_contact_id"`
	TargetContactID pgtype.UUID `json:"target_contact_id"`
}

type FindDuplicateContactMethodsRow struct {
	Value string `json:"value"`
	Type  string `json:"type"`
}

// Find contact methods that exist in both source and target
// Used to identify duplicates that will be skipped during merge
func (q *Queries) FindDuplicateContactMethods(ctx context.Context, arg FindDuplicateContactMethodsParams) ([]*FindDuplicateContactMethodsRow, error) {
	rows, err := q.db.Query(ctx, FindDuplicateContactMethods, arg.SourceContactID, arg.TargetContactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FindDuplicateContactMethodsRow{}
	for rows.Next() {
		var i FindDuplicateContactMethodsRow
		if err := rows.Scan(&i.Value, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ReplaceContactInCalendarEvents = `-- name: ReplaceContactInCalendarEvents :exec
UPDATE calendar_event
SET matched_contact_ids = array_replace(matched_contact_ids, $1::uuid, $2::uuid),
    updated_at = NOW()
WHERE $1::uuid = ANY(matched_contact_ids)
`

type ReplaceContactInCalendarEventsParams struct {
	SourceContactID pgtype.UUID `json:"source_contact_id"`
	TargetContactID pgtype.UUID `json:"target_contact_id"`
}

// Replace source contact ID with target contact ID in calendar event matched_contact_ids array
// Uses array_replace for efficient in-place replacement
func (q *Queries) ReplaceContactInCalendarEvents(ctx context.Context, arg ReplaceContactInCalendarEventsParams) error {
	_, err := q.db.Exec(ctx, ReplaceContactInCalendarEvents, arg.SourceContactID, arg.TargetContactID)
	return err
}

const TransferConnectionsAsContactA = `-- name: TransferConnectionsAsContactA :exec
UPDATE connection
SET contact_a_id = $1
WHERE contact_a_id = $2
  AND contact_b_id != $1
`

type TransferConnectionsAsContactAParams struct {
	TargetContactID pgtype.UUID `json:"target_contact_id"`
	SourceContactID pgtype.UUID `json:"source_contact_id"`
}

// Transfer connections where source is contact_a to use target instead
// This handles the bidirectional relationship table
func (q *Queries) TransferConnectionsAsContactA(ctx context.Context, arg TransferConnectionsAsContactAParams) error {
	_, err := q.db.Exec(ctx, TransferConnectionsAsContactA, arg.TargetContactID, arg.SourceContactID)
	return err
}

const TransferConnectionsAsContactB = `-- name: TransferConnectionsAsContactB :exec
UPDATE connection
SET contact_b_id = $1
WHERE contact_b_id = $2
  AND contact_a_id != $1
`

type TransferConnectionsAsContactBParams struct {
	TargetContactID pgtype.UUID `json:"target_contact_id"`
	SourceContactID pgtype.UUID `json:"source_contact_id"`
}

// Transfer connections where source is contact_b to use target instead
func (q *Queries) TransferConnectionsAsContactB(ctx context.Context, arg TransferConnectionsAsContactBParams) error {
	_, err := q.db.Exec(ctx, TransferConnectionsAsContactB, arg.TargetContactID, arg.SourceContactID)
	return err
}

const TransferContactMethods = `-- name: TransferContactMethods :exec

UPDATE contact_method
SET contact_id = $1,
    updated_at = NOW()
WHERE contact_id = $2
`

type TransferContactMethodsParams struct {
	TargetContactID pgtype.UUID `json:"target_contact_id"`
	SourceContactID pgtype.UUID `json:"source_contact_id"`
}

// Contact merge queries
// These queries support merging one contact (source) into another (target)
// Transfer contact methods from source to target contact
func (q *Queries) TransferContactMethods(ctx context.Context, arg TransferContactMethodsParams) error {
	_, err := q.db.Exec(ctx, TransferContactMethods, arg.TargetContactID, arg.SourceContactID)
	return err
}

const TransferInteractions = `-- name: TransferInteractions :exec
UPDATE interaction
SET contact_id = $1
WHERE contact_id = $2
`

type TransferInteractionsParams struct {
	TargetContactID pgtype.UUID `json:"target_contact_id"`
	SourceContactID pgtype.UUID `json:"source_contact_id"`
}

// Transfer interactions from source to target contact
func (q *Queries) TransferInteractions(ctx context.Context, arg TransferInteractionsParams) error {
	_, err := q.db.Exec(ctx, TransferInteractions, arg.TargetContactID, arg.SourceContactID)
	return err
}

const TransferNotes = `-- name: TransferNotes :exec
UPDATE note
SET contact_id = $1,
    updated_at = NOW()
WHERE contact_id = $2
`

type TransferNotesParams struct {
	TargetContactID pgtype.UUID `json:"target_contact_id"`
	SourceContactID pgtype.UUID `json:"source_contact_id"`
}

// Transfer notes from source to target contact
func (q *Queries) TransferNotes(ctx context.Context, arg TransferNotesParams) error {
	_, err := q.db.Exec(ctx, TransferNotes, arg.TargetContactID, arg.SourceContactID)
	return err
}
