// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contact.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountContacts = `-- name: CountContacts :one
SELECT COUNT(*) FROM contact
WHERE deleted_at IS NULL
  AND ($1 = '' OR
       ($1 = 'has_cadence' AND cadence IS NOT NULL AND cadence != '') OR
       ($1 = 'no_cadence' AND (cadence IS NULL OR cadence = '')))
  AND ($2 = '' OR
       ($2 = 'has_followup' AND EXISTS(SELECT 1 FROM contact_task WHERE contact_task.contact_id = contact.id AND contact_task.kind = 'follow_up' AND contact_task.state = 'managed')) OR
       ($2 = 'no_followup' AND NOT EXISTS(SELECT 1 FROM contact_task WHERE contact_task.contact_id = contact.id AND contact_task.kind = 'follow_up' AND contact_task.state = 'managed')))
`

type CountContactsParams struct {
	CadenceFilter  interface{} `json:"cadence_filter"`
	FollowupFilter interface{} `json:"followup_filter"`
}

func (q *Queries) CountContacts(ctx context.Context, arg CountContactsParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountContacts, arg.CadenceFilter, arg.FollowupFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountSearchContacts = `-- name: CountSearchContacts :one
SELECT COUNT(*) FROM contact c
LEFT JOIN (
  SELECT contact_id, string_agg(value, ' ') AS method_values
  FROM contact_method
  GROUP BY contact_id
) cm ON cm.contact_id = c.id
WHERE c.deleted_at IS NULL
  AND ($1 = '' OR
       ($1 = 'has_cadence' AND c.cadence IS NOT NULL AND c.cadence != '') OR
       ($1 = 'no_cadence' AND (c.cadence IS NULL OR c.cadence = '')))
  AND ($2 = '' OR
       ($2 = 'has_followup' AND EXISTS(SELECT 1 FROM contact_task WHERE contact_task.contact_id = c.id AND contact_task.kind = 'follow_up' AND contact_task.state = 'managed')) OR
       ($2 = 'no_followup' AND NOT EXISTS(SELECT 1 FROM contact_task WHERE contact_task.contact_id = c.id AND contact_task.kind = 'follow_up' AND contact_task.state = 'managed')))
  AND to_tsvector('english', c.full_name || ' ' || COALESCE(cm.method_values, '')) @@ plainto_tsquery('english', $3)
`

type CountSearchContactsParams struct {
	CadenceFilter  interface{} `json:"cadence_filter"`
	FollowupFilter interface{} `json:"followup_filter"`
	SearchQuery    string      `json:"search_query"`
}

func (q *Queries) CountSearchContacts(ctx context.Context, arg CountSearchContactsParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountSearchContacts, arg.CadenceFilter, arg.FollowupFilter, arg.SearchQuery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateContact = `-- name: CreateContact :one
INSERT INTO contact (
  full_name, location, birthday, how_met, cadence, last_contacted, profile_photo, created_at, contact_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, full_name, location, birthday, how_met, cadence, last_contacted, profile_photo, deleted_at, created_at, updated_at, contact_by, last_interaction_at, last_outreach_at, last_response_at
`

type CreateContactParams struct {
	FullName      string             `json:"full_name"`
	Location      pgtype.Text        `json:"location"`
	Birthday      pgtype.Date        `json:"birthday"`
	HowMet        pgtype.Text        `json:"how_met"`
	Cadence       pgtype.Text        `json:"cadence"`
	LastContacted pgtype.Timestamptz `json:"last_contacted"`
	ProfilePhoto  pgtype.Text        `json:"profile_photo"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ContactBy     pgtype.Date        `json:"contact_by"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (*Contact, error) {
	row := q.db.QueryRow(ctx, CreateContact,
		arg.FullName,
		arg.Location,
		arg.Birthday,
		arg.HowMet,
		arg.Cadence,
		arg.LastContacted,
		arg.ProfilePhoto,
		arg.CreatedAt,
		arg.ContactBy,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Location,
		&i.Birthday,
		&i.HowMet,
		&i.Cadence,
		&i.LastContacted,
		&i.ProfilePhoto,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContactBy,
		&i.LastInteractionAt,
		&i.LastOutreachAt,
		&i.LastResponseAt,
	)
	return &i, err
}

const FindSimilarContacts = `-- name: FindSimilarContacts :many
SELECT
  c.id,
  c.full_name,
  similarity(c.full_name, $1::text) as name_similarity,
  COALESCE(
    json_agg(
      json_build_object(
        'type', cm.type,
        'value', cm.value
      )
    ) FILTER (WHERE cm.id IS NOT NULL),
    '[]'
  )::jsonb as methods_json
FROM contact c
LEFT JOIN contact_method cm ON c.id = cm.contact_id
WHERE c.deleted_at IS NULL
  AND similarity(c.full_name, $1::text) > $2::real
GROUP BY c.id, c.full_name
ORDER BY similarity(c.full_name, $1::text) DESC
LIMIT $3
`

type FindSimilarContactsParams struct {
	SearchName  string  `json:"search_name"`
	Threshold   float32 `json:"threshold"`
	ResultLimit int32   `json:"result_limit"`
}

type FindSimilarContactsRow struct {
	ID             pgtype.UUID `json:"id"`
	FullName       string      `json:"full_name"`
	NameSimilarity float32     `json:"name_similarity"`
	MethodsJson    []byte      `json:"methods_json"`
}

func (q *Queries) FindSimilarContacts(ctx context.Context, arg FindSimilarContactsParams) ([]*FindSimilarContactsRow, error) {
	rows, err := q.db.Query(ctx, FindSimilarContacts, arg.SearchName, arg.Threshold, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FindSimilarContactsRow{}
	for rows.Next() {
		var i FindSimilarContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.NameSimilarity,
			&i.MethodsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const FindSimilarContactsBatch = `-- name: FindSimilarContactsBatch :many
WITH candidate_names AS (
  SELECT
    unnest($3::text[])::text as candidate_name,
    unnest($4::text[])::text as candidate_id
)
SELECT
  cn.candidate_id::text as candidate_id,
  cn.candidate_name::text as candidate_name,
  c.id as contact_id,
  c.full_name as contact_name,
  similarity(c.full_name, cn.candidate_name) as name_similarity,
  COALESCE(
    json_agg(
      json_build_object(
        'type', cm.type,
        'value', cm.value
      )
    ) FILTER (WHERE cm.id IS NOT NULL),
    '[]'
  )::jsonb as methods_json
FROM candidate_names cn
CROSS JOIN LATERAL (
  SELECT c.id, c.full_name
  FROM contact c
  WHERE c.deleted_at IS NULL
    AND similarity(c.full_name, cn.candidate_name) > $1::real
  ORDER BY similarity(c.full_name, cn.candidate_name) DESC
  LIMIT $2
) c
LEFT JOIN contact_method cm ON c.id = cm.contact_id
GROUP BY cn.candidate_id, cn.candidate_name, c.id, c.full_name
ORDER BY cn.candidate_id, similarity(c.full_name, cn.candidate_name) DESC
`

type FindSimilarContactsBatchParams struct {
	Threshold         float32  `json:"threshold"`
	LimitPerCandidate int32    `json:"limit_per_candidate"`
	CandidateNames    []string `json:"candidate_names"`
	CandidateIds      []string `json:"candidate_ids"`
}

type FindSimilarContactsBatchRow struct {
	CandidateID    string      `json:"candidate_id"`
	CandidateName  string      `json:"candidate_name"`
	ContactID      pgtype.UUID `json:"contact_id"`
	ContactName    string      `json:"contact_name"`
	NameSimilarity float32     `json:"name_similarity"`
	MethodsJson    []byte      `json:"methods_json"`
}

// Finds similar contacts for multiple candidate names in a single batch query.
// Uses UNNEST to expand input arrays and LATERAL join to find matches per candidate.
// Returns results grouped by candidate_id with matches ordered by similarity.
func (q *Queries) FindSimilarContactsBatch(ctx context.Context, arg FindSimilarContactsBatchParams) ([]*FindSimilarContactsBatchRow, error) {
	rows, err := q.db.Query(ctx, FindSimilarContactsBatch,
		arg.Threshold,
		arg.LimitPerCandidate,
		arg.CandidateNames,
		arg.CandidateIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FindSimilarContactsBatchRow{}
	for rows.Next() {
		var i FindSimilarContactsBatchRow
		if err := rows.Scan(
			&i.CandidateID,
			&i.CandidateName,
			&i.ContactID,
			&i.ContactName,
			&i.NameSimilarity,
			&i.MethodsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetContact = `-- name: GetContact :one

SELECT id, full_name, location, birthday, how_met, cadence, last_contacted, profile_photo, deleted_at, created_at, updated_at, contact_by, last_interaction_at, last_outreach_at, last_response_at FROM contact
WHERE id = $1 AND deleted_at IS NULL
`

// Contact queries
func (q *Queries) GetContact(ctx context.Context, id pgtype.UUID) (*Contact, error) {
	row := q.db.QueryRow(ctx, GetContact, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Location,
		&i.Birthday,
		&i.HowMet,
		&i.Cadence,
		&i.LastContacted,
		&i.ProfilePhoto,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContactBy,
		&i.LastInteractionAt,
		&i.LastOutreachAt,
		&i.LastResponseAt,
	)
	return &i, err
}

const HardDeleteContact = `-- name: HardDeleteContact :exec
DELETE FROM contact WHERE id = $1
`

func (q *Queries) HardDeleteContact(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, HardDeleteContact, id)
	return err
}

const ListContactIDs = `-- name: ListContactIDs :many
SELECT id FROM contact
WHERE deleted_at IS NULL
  AND ($1 = '' OR
       ($1 = 'has_cadence' AND cadence IS NOT NULL AND cadence != '') OR
       ($1 = 'no_cadence' AND (cadence IS NULL OR cadence = '')))
  AND ($2 = '' OR
       ($2 = 'has_followup' AND EXISTS(SELECT 1 FROM contact_task WHERE contact_task.contact_id = contact.id AND contact_task.kind = 'follow_up' AND contact_task.state = 'managed')) OR
       ($2 = 'no_followup' AND NOT EXISTS(SELECT 1 FROM contact_task WHERE contact_task.contact_id = contact.id AND contact_task.kind = 'follow_up' AND contact_task.state = 'managed')))
`

type ListContactIDsParams struct {
	CadenceFilter  interface{} `json:"cadence_filter"`
	FollowupFilter interface{} `json:"followup_filter"`
}

// Lightweight query returning only IDs for navigation
func (q *Queries) ListContactIDs(ctx context.Context, arg ListContactIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, ListContactIDs, arg.CadenceFilter, arg.FollowupFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListContactIDsSorted = `-- name: ListContactIDsSorted :many
SELECT id FROM contact
WHERE deleted_at IS NULL
  AND ($1 = '' OR
       ($1 = 'has_cadence' AND cadence IS NOT NULL AND cadence != '') OR
       ($1 = 'no_cadence' AND (cadence IS NULL OR cadence = '')))
  AND ($2 = '' OR
       ($2 = 'has_followup' AND EXISTS(SELECT 1 FROM contact_task WHERE contact_task.contact_id = contact.id AND contact_task.kind = 'follow_up' AND contact_task.state = 'managed')) OR
       ($2 = 'no_followup' AND NOT EXISTS(SELECT 1 FROM contact_task WHERE contact_task.contact_id = contact.id AND contact_task.kind = 'follow_up' AND contact_task.state = 'managed')))
ORDER BY
  CASE WHEN $3 = 'name' AND $4 = 'asc' THEN full_name END ASC,
  CASE WHEN $3 = 'name' AND $4 = 'desc' THEN full_name END DESC,
  CASE WHEN $3 = 'location' AND $4 = 'asc' THEN COALESCE(location, '') END ASC,
  CASE WHEN $3 = 'location' AND $4 = 'desc' THEN COALESCE(location, '') END DESC,
  CASE WHEN $3 = 'birthday' AND $4 = 'asc' THEN birthday END ASC NULLS LAST,
  CASE WHEN $3 = 'birthday' AND $4 = 'desc' THEN birthday END DESC NULLS LAST,
  CASE WHEN $3 = 'last_contacted' AND $4 = 'asc' THEN last_contacted END ASC NULLS LAST,
  CASE WHEN $3 = 'last_contacted' AND $4 = 'desc' THEN last_contacted END DESC NULLS LAST,
  CASE WHEN $3 = 'contact_by' AND $4 = 'asc' THEN contact_by END ASC NULLS LAST,
  CASE WHEN $3 = 'contact_by' AND $4 = 'desc' THEN contact_by END DESC NULLS LAST,
  -- Cadence sort by frequency: weekly=1 (most frequent) to annual=6 (least frequent), null=7
  CASE WHEN $3 = 'cadence' AND $4 = 'desc' THEN
    CASE cadence WHEN 'weekly' THEN 1 WHEN 'biweekly' THEN 2 WHEN 'monthly' THEN 3 WHEN 'quarterly' THEN 4 WHEN 'biannual' THEN 5 WHEN 'annual' THEN 6 ELSE 7 END
  END ASC,
  CASE WHEN $3 = 'cadence' AND $4 = 'asc' THEN
    CASE cadence WHEN 'weekly' THEN 1 WHEN 'biweekly' THEN 2 WHEN 'monthly' THEN 3 WHEN 'quarterly' THEN 4 WHEN 'biannual' THEN 5 WHEN 'annual' THEN 6 ELSE 7 END
  END DESC,
  -- Secondary sort by name for cadence sorting
  CASE WHEN $3 = 'cadence' THEN full_name END ASC
`

type ListContactIDsSortedParams struct {
	CadenceFilter  interface{} `json:"cadence_filter"`
	FollowupFilter interface{} `json:"followup_filter"`
	SortField      interface{} `json:"sort_field"`
	SortOrder      interface{} `json:"sort_order"`
}

// Lightweight query returning only IDs with sorting for navigation
func (q *Queries) ListContactIDsSorted(ctx context.Context, arg ListContactIDsSortedParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, ListContactIDsSorted,
		arg.CadenceFilter,
		arg.FollowupFilter,
		arg.SortField,
		arg.SortOrder,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListContacts = `-- name: ListContacts :many
SELECT id, full_name, location, birthday, how_met, cadence, last_contacted, profile_photo, deleted_at, created_at, updated_at, contact_by, last_interaction_at, last_outreach_at, last_response_at FROM contact
WHERE deleted_at IS NULL
  AND ($1 = '' OR
       ($1 = 'has_cadence' AND cadence IS NOT NULL AND cadence != '') OR
       ($1 = 'no_cadence' AND (cadence IS NULL OR cadence = '')))
  AND ($2 = '' OR
       ($2 = 'has_followup' AND EXISTS(SELECT 1 FROM contact_task WHERE contact_task.contact_id = contact.id AND contact_task.kind = 'follow_up' AND contact_task.state = 'managed')) OR
       ($2 = 'no_followup' AND NOT EXISTS(SELECT 1 FROM contact_task WHERE contact_task.contact_id = contact.id AND contact_task.kind = 'follow_up' AND contact_task.state = 'managed')))
LIMIT $4 OFFSET $3
`

type ListContactsParams struct {
	CadenceFilter  interface{} `json:"cadence_filter"`
	FollowupFilter interface{} `json:"followup_filter"`
	PageOffset     int32       `json:"page_offset"`
	PageLimit      int32       `json:"page_limit"`
}

// cadence_filter: ” = no filter (Go zero value), 'has_cadence' = non-empty cadence,
// 'no_cadence' = NULL or empty string (defensive; CHECK constraint prevents empty strings)
// followup_filter: ” = no filter, 'has_followup' = pending follow-up exists, 'no_followup' = no pending follow-up
func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]*Contact, error) {
	rows, err := q.db.Query(ctx, ListContacts,
		arg.CadenceFilter,
		arg.FollowupFilter,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Location,
			&i.Birthday,
			&i.HowMet,
			&i.Cadence,
			&i.LastContacted,
			&i.ProfilePhoto,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContactBy,
			&i.LastInteractionAt,
			&i.LastOutreachAt,
			&i.LastResponseAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListContactsSorted = `-- name: ListContactsSorted :many
SELECT id, full_name, location, birthday, how_met, cadence, last_contacted, profile_photo, deleted_at, created_at, updated_at, contact_by, last_interaction_at, last_outreach_at, last_response_at FROM contact
WHERE deleted_at IS NULL
  AND ($1 = '' OR
       ($1 = 'has_cadence' AND cadence IS NOT NULL AND cadence != '') OR
       ($1 = 'no_cadence' AND (cadence IS NULL OR cadence = '')))
  AND ($2 = '' OR
       ($2 = 'has_followup' AND EXISTS(SELECT 1 FROM contact_task WHERE contact_task.contact_id = contact.id AND contact_task.kind = 'follow_up' AND contact_task.state = 'managed')) OR
       ($2 = 'no_followup' AND NOT EXISTS(SELECT 1 FROM contact_task WHERE contact_task.contact_id = contact.id AND contact_task.kind = 'follow_up' AND contact_task.state = 'managed')))
ORDER BY
  CASE WHEN $3 = 'name' AND $4 = 'asc' THEN full_name END ASC,
  CASE WHEN $3 = 'name' AND $4 = 'desc' THEN full_name END DESC,
  CASE WHEN $3 = 'location' AND $4 = 'asc' THEN COALESCE(location, '') END ASC,
  CASE WHEN $3 = 'location' AND $4 = 'desc' THEN COALESCE(location, '') END DESC,
  CASE WHEN $3 = 'birthday' AND $4 = 'asc' THEN birthday END ASC NULLS LAST,
  CASE WHEN $3 = 'birthday' AND $4 = 'desc' THEN birthday END DESC NULLS LAST,
  CASE WHEN $3 = 'last_contacted' AND $4 = 'asc' THEN last_contacted END ASC NULLS LAST,
  CASE WHEN $3 = 'last_contacted' AND $4 = 'desc' THEN last_contacted END DESC NULLS LAST,
  CASE WHEN $3 = 'contact_by' AND $4 = 'asc' THEN contact_by END ASC NULLS LAST,
  CASE WHEN $3 = 'contact_by' AND $4 = 'desc' THEN contact_by END DESC NULLS LAST,
  -- Cadence sort by frequency: weekly=1 (most frequent) to annual=6 (least frequent), null=7
  -- 'desc' = most frequent first (ASC on number), 'asc' = least frequent first (DESC on number)
  CASE WHEN $3 = 'cadence' AND $4 = 'desc' THEN
    CASE cadence WHEN 'weekly' THEN 1 WHEN 'biweekly' THEN 2 WHEN 'monthly' THEN 3 WHEN 'quarterly' THEN 4 WHEN 'biannual' THEN 5 WHEN 'annual' THEN 6 ELSE 7 END
  END ASC,
  CASE WHEN $3 = 'cadence' AND $4 = 'asc' THEN
    CASE cadence WHEN 'weekly' THEN 1 WHEN 'biweekly' THEN 2 WHEN 'monthly' THEN 3 WHEN 'quarterly' THEN 4 WHEN 'biannual' THEN 5 WHEN 'annual' THEN 6 ELSE 7 END
  END DESC,
  -- Secondary sort by name for cadence sorting
  CASE WHEN $3 = 'cadence' THEN full_name END ASC
LIMIT $6 OFFSET $5
`

type ListContactsSortedParams struct {
	CadenceFilter  interface{} `json:"cadence_filter"`
	FollowupFilter interface{} `json:"followup_filter"`
	SortField      interface{} `json:"sort_field"`
	SortOrder      interface{} `json:"sort_order"`
	PageOffset     int32       `json:"page_offset"`
	PageLimit      int32       `json:"page_limit"`
}

func (q *Queries) ListContactsSorted(ctx context.Context, arg ListContactsSortedParams) ([]*Contact, error) {
	rows, err := q.db.Query(ctx, ListContactsSorted,
		arg.CadenceFilter,
		arg.FollowupFilter,
		arg.SortField,
		arg.SortOrder,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Location,
			&i.Birthday,
			&i.HowMet,
			&i.Cadence,
			&i.LastContacted,
			&i.ProfilePhoto,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContactBy,
			&i.LastInteractionAt,
			&i.LastOutreachAt,
			&i.LastResponseAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListContactsWithCadence = `-- name: ListContactsWithCadence :many
SELECT id, full_name, location, birthday, how_met, cadence, last_contacted, profile_photo, deleted_at, created_at, updated_at, contact_by, last_interaction_at, last_outreach_at, last_response_at FROM contact
WHERE deleted_at IS NULL
  AND cadence IS NOT NULL
  AND cadence != ''
ORDER BY full_name ASC
LIMIT $1
`

// Lists contacts that have a cadence set (used for Todoist sync reconciliation).
func (q *Queries) ListContactsWithCadence(ctx context.Context, limit int32) ([]*Contact, error) {
	rows, err := q.db.Query(ctx, ListContactsWithCadence, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Location,
			&i.Birthday,
			&i.HowMet,
			&i.Cadence,
			&i.LastContacted,
			&i.ProfilePhoto,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContactBy,
			&i.LastInteractionAt,
			&i.LastOutreachAt,
			&i.LastResponseAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListContactsWithContactBy = `-- name: ListContactsWithContactBy :many
SELECT id, full_name, location, birthday, how_met, cadence, last_contacted, profile_photo, deleted_at, created_at, updated_at, contact_by, last_interaction_at, last_outreach_at, last_response_at FROM contact
WHERE deleted_at IS NULL
  AND contact_by IS NOT NULL
ORDER BY contact_by ASC
LIMIT $1
`

// Lists contacts that have a contact_by date set (used for testing mode filtering).
// Returns contacts ordered by contact_by (soonest first).
func (q *Queries) ListContactsWithContactBy(ctx context.Context, limit int32) ([]*Contact, error) {
	rows, err := q.db.Query(ctx, ListContactsWithContactBy, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Location,
			&i.Birthday,
			&i.HowMet,
			&i.Cadence,
			&i.LastContacted,
			&i.ProfilePhoto,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContactBy,
			&i.LastInteractionAt,
			&i.LastOutreachAt,
			&i.LastResponseAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListOverdueContacts = `-- name: ListOverdueContacts :many
SELECT id, full_name, location, birthday, how_met, cadence, last_contacted, profile_photo, deleted_at, created_at, updated_at, contact_by, last_interaction_at, last_outreach_at, last_response_at FROM contact
WHERE deleted_at IS NULL
  AND contact_by IS NOT NULL
  AND contact_by < $1::date
ORDER BY contact_by ASC
LIMIT $2
`

type ListOverdueContactsParams struct {
	Today      pgtype.Date `json:"today"`
	LimitCount int32       `json:"limit_count"`
}

// Lists contacts whose contact_by date is before today (overdue).
// Returns contacts ordered by how overdue they are (most overdue first).
func (q *Queries) ListOverdueContacts(ctx context.Context, arg ListOverdueContactsParams) ([]*Contact, error) {
	rows, err := q.db.Query(ctx, ListOverdueContacts, arg.Today, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Location,
			&i.Birthday,
			&i.HowMet,
			&i.Cadence,
			&i.LastContacted,
			&i.ProfilePhoto,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContactBy,
			&i.LastInteractionAt,
			&i.LastOutreachAt,
			&i.LastResponseAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchContactIDs = `-- name: SearchContactIDs :many
SELECT c.id FROM contact c
LEFT JOIN (
  SELECT contact_id, string_agg(value, ' ') AS method_values
  FROM contact_method
  GROUP BY contact_id
) cm ON cm.contact_id = c.id
WHERE c.deleted_at IS NULL
  AND ($1 = '' OR
       ($1 = 'has_cadence' AND c.cadence IS NOT NULL AND c.cadence != '') OR
       ($1 = 'no_cadence' AND (c.cadence IS NULL OR c.cadence = '')))
  AND ($2 = '' OR
       ($2 = 'has_followup' AND EXISTS(SELECT 1 FROM contact_task WHERE contact_task.contact_id = c.id AND contact_task.kind = 'follow_up' AND contact_task.state = 'managed')) OR
       ($2 = 'no_followup' AND NOT EXISTS(SELECT 1 FROM contact_task WHERE contact_task.contact_id = c.id AND contact_task.kind = 'follow_up' AND contact_task.state = 'managed')))
  AND to_tsvector('english', c.full_name || ' ' || COALESCE(cm.method_values, '')) @@ plainto_tsquery('english', $3)
ORDER BY ts_rank(
  to_tsvector('english', c.full_name || ' ' || COALESCE(cm.method_values, '')),
  plainto_tsquery('english', $3)
) DESC
`

type SearchContactIDsParams struct {
	CadenceFilter  interface{} `json:"cadence_filter"`
	FollowupFilter interface{} `json:"followup_filter"`
	SearchQuery    string      `json:"search_query"`
}

// Lightweight query returning only IDs with search for navigation
func (q *Queries) SearchContactIDs(ctx context.Context, arg SearchContactIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, SearchContactIDs, arg.CadenceFilter, arg.FollowupFilter, arg.SearchQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchContactIDsSorted = `-- name: SearchContactIDsSorted :many
SELECT c.id FROM contact c
LEFT JOIN (
  SELECT contact_id, string_agg(value, ' ') AS method_values
  FROM contact_method
  GROUP BY contact_id
) cm ON cm.contact_id = c.id
WHERE c.deleted_at IS NULL
  AND ($1 = '' OR
       ($1 = 'has_cadence' AND c.cadence IS NOT NULL AND c.cadence != '') OR
       ($1 = 'no_cadence' AND (c.cadence IS NULL OR c.cadence = '')))
  AND ($2 = '' OR
       ($2 = 'has_followup' AND EXISTS(SELECT 1 FROM contact_task WHERE contact_task.contact_id = c.id AND contact_task.kind = 'follow_up' AND contact_task.state = 'managed')) OR
       ($2 = 'no_followup' AND NOT EXISTS(SELECT 1 FROM contact_task WHERE contact_task.contact_id = c.id AND contact_task.kind = 'follow_up' AND contact_task.state = 'managed')))
  AND to_tsvector('english', c.full_name || ' ' || COALESCE(cm.method_values, '')) @@ plainto_tsquery('english', $3)
ORDER BY
  CASE WHEN $4 = 'name' AND $5 = 'asc' THEN c.full_name END ASC,
  CASE WHEN $4 = 'name' AND $5 = 'desc' THEN c.full_name END DESC,
  CASE WHEN $4 = 'location' AND $5 = 'asc' THEN COALESCE(c.location, '') END ASC,
  CASE WHEN $4 = 'location' AND $5 = 'desc' THEN COALESCE(c.location, '') END DESC,
  CASE WHEN $4 = 'birthday' AND $5 = 'asc' THEN c.birthday END ASC NULLS LAST,
  CASE WHEN $4 = 'birthday' AND $5 = 'desc' THEN c.birthday END DESC NULLS LAST,
  CASE WHEN $4 = 'last_contacted' AND $5 = 'asc' THEN c.last_contacted END ASC NULLS LAST,
  CASE WHEN $4 = 'last_contacted' AND $5 = 'desc' THEN c.last_contacted END DESC NULLS LAST,
  CASE WHEN $4 = 'contact_by' AND $5 = 'asc' THEN c.contact_by END ASC NULLS LAST,
  CASE WHEN $4 = 'contact_by' AND $5 = 'desc' THEN c.contact_by END DESC NULLS LAST,
  -- Cadence sort by frequency: weekly=1 (most frequent) to annual=6 (least frequent), null=7
  CASE WHEN $4 = 'cadence' AND $5 = 'desc' THEN
    CASE c.cadence WHEN 'weekly' THEN 1 WHEN 'biweekly' THEN 2 WHEN 'monthly' THEN 3 WHEN 'quarterly' THEN 4 WHEN 'biannual' THEN 5 WHEN 'annual' THEN 6 ELSE 7 END
  END ASC,
  CASE WHEN $4 = 'cadence' AND $5 = 'asc' THEN
    CASE c.cadence WHEN 'weekly' THEN 1 WHEN 'biweekly' THEN 2 WHEN 'monthly' THEN 3 WHEN 'quarterly' THEN 4 WHEN 'biannual' THEN 5 WHEN 'annual' THEN 6 ELSE 7 END
  END DESC,
  -- Secondary sort by name for cadence sorting
  CASE WHEN $4 = 'cadence' THEN c.full_name END ASC
`

type SearchContactIDsSortedParams struct {
	CadenceFilter  interface{} `json:"cadence_filter"`
	FollowupFilter interface{} `json:"followup_filter"`
	SearchQuery    string      `json:"search_query"`
	SortField      interface{} `json:"sort_field"`
	SortOrder      interface{} `json:"sort_order"`
}

// Lightweight query returning only IDs with search and sorting for navigation
func (q *Queries) SearchContactIDsSorted(ctx context.Context, arg SearchContactIDsSortedParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, SearchContactIDsSorted,
		arg.CadenceFilter,
		arg.FollowupFilter,
		arg.SearchQuery,
		arg.SortField,
		arg.SortOrder,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchContacts = `-- name: SearchContacts :many
SELECT c.id, c.full_name, c.location, c.birthday, c.how_met, c.cadence, c.last_contacted, c.profile_photo, c.deleted_at, c.created_at, c.updated_at, c.contact_by, c.last_interaction_at, c.last_outreach_at, c.last_response_at FROM contact c
LEFT JOIN (
  SELECT contact_id, string_agg(value, ' ') AS method_values
  FROM contact_method
  GROUP BY contact_id
) cm ON cm.contact_id = c.id
WHERE c.deleted_at IS NULL
  AND ($1 = '' OR
       ($1 = 'has_cadence' AND c.cadence IS NOT NULL AND c.cadence != '') OR
       ($1 = 'no_cadence' AND (c.cadence IS NULL OR c.cadence = '')))
  AND ($2 = '' OR
       ($2 = 'has_followup' AND EXISTS(SELECT 1 FROM contact_task WHERE contact_task.contact_id = c.id AND contact_task.kind = 'follow_up' AND contact_task.state = 'managed')) OR
       ($2 = 'no_followup' AND NOT EXISTS(SELECT 1 FROM contact_task WHERE contact_task.contact_id = c.id AND contact_task.kind = 'follow_up' AND contact_task.state = 'managed')))
  AND to_tsvector('english', c.full_name || ' ' || COALESCE(cm.method_values, '')) @@ plainto_tsquery('english', $3)
ORDER BY ts_rank(
  to_tsvector('english', c.full_name || ' ' || COALESCE(cm.method_values, '')),
  plainto_tsquery('english', $3)
) DESC
LIMIT $5 OFFSET $4
`

type SearchContactsParams struct {
	CadenceFilter  interface{} `json:"cadence_filter"`
	FollowupFilter interface{} `json:"followup_filter"`
	SearchQuery    string      `json:"search_query"`
	PageOffset     int32       `json:"page_offset"`
	PageLimit      int32       `json:"page_limit"`
}

func (q *Queries) SearchContacts(ctx context.Context, arg SearchContactsParams) ([]*Contact, error) {
	rows, err := q.db.Query(ctx, SearchContacts,
		arg.CadenceFilter,
		arg.FollowupFilter,
		arg.SearchQuery,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Location,
			&i.Birthday,
			&i.HowMet,
			&i.Cadence,
			&i.LastContacted,
			&i.ProfilePhoto,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContactBy,
			&i.LastInteractionAt,
			&i.LastOutreachAt,
			&i.LastResponseAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchContactsSorted = `-- name: SearchContactsSorted :many
SELECT c.id, c.full_name, c.location, c.birthday, c.how_met, c.cadence, c.last_contacted, c.profile_photo, c.deleted_at, c.created_at, c.updated_at, c.contact_by, c.last_interaction_at, c.last_outreach_at, c.last_response_at FROM contact c
LEFT JOIN (
  SELECT contact_id, string_agg(value, ' ') AS method_values
  FROM contact_method
  GROUP BY contact_id
) cm ON cm.contact_id = c.id
WHERE c.deleted_at IS NULL
  AND ($1 = '' OR
       ($1 = 'has_cadence' AND c.cadence IS NOT NULL AND c.cadence != '') OR
       ($1 = 'no_cadence' AND (c.cadence IS NULL OR c.cadence = '')))
  AND ($2 = '' OR
       ($2 = 'has_followup' AND EXISTS(SELECT 1 FROM contact_task WHERE contact_task.contact_id = c.id AND contact_task.kind = 'follow_up' AND contact_task.state = 'managed')) OR
       ($2 = 'no_followup' AND NOT EXISTS(SELECT 1 FROM contact_task WHERE contact_task.contact_id = c.id AND contact_task.kind = 'follow_up' AND contact_task.state = 'managed')))
  AND to_tsvector('english', c.full_name || ' ' || COALESCE(cm.method_values, '')) @@ plainto_tsquery('english', $3)
ORDER BY
  CASE WHEN $4 = 'name' AND $5 = 'asc' THEN c.full_name END ASC,
  CASE WHEN $4 = 'name' AND $5 = 'desc' THEN c.full_name END DESC,
  CASE WHEN $4 = 'location' AND $5 = 'asc' THEN COALESCE(c.location, '') END ASC,
  CASE WHEN $4 = 'location' AND $5 = 'desc' THEN COALESCE(c.location, '') END DESC,
  CASE WHEN $4 = 'birthday' AND $5 = 'asc' THEN c.birthday END ASC NULLS LAST,
  CASE WHEN $4 = 'birthday' AND $5 = 'desc' THEN c.birthday END DESC NULLS LAST,
  CASE WHEN $4 = 'last_contacted' AND $5 = 'asc' THEN c.last_contacted END ASC NULLS LAST,
  CASE WHEN $4 = 'last_contacted' AND $5 = 'desc' THEN c.last_contacted END DESC NULLS LAST,
  CASE WHEN $4 = 'contact_by' AND $5 = 'asc' THEN c.contact_by END ASC NULLS LAST,
  CASE WHEN $4 = 'contact_by' AND $5 = 'desc' THEN c.contact_by END DESC NULLS LAST,
  -- Cadence sort by frequency: weekly=1 (most frequent) to annual=6 (least frequent), null=7
  CASE WHEN $4 = 'cadence' AND $5 = 'desc' THEN
    CASE c.cadence WHEN 'weekly' THEN 1 WHEN 'biweekly' THEN 2 WHEN 'monthly' THEN 3 WHEN 'quarterly' THEN 4 WHEN 'biannual' THEN 5 WHEN 'annual' THEN 6 ELSE 7 END
  END ASC,
  CASE WHEN $4 = 'cadence' AND $5 = 'asc' THEN
    CASE c.cadence WHEN 'weekly' THEN 1 WHEN 'biweekly' THEN 2 WHEN 'monthly' THEN 3 WHEN 'quarterly' THEN 4 WHEN 'biannual' THEN 5 WHEN 'annual' THEN 6 ELSE 7 END
  END DESC,
  -- Secondary sort by name for cadence sorting
  CASE WHEN $4 = 'cadence' THEN c.full_name END ASC
LIMIT $7 OFFSET $6
`

type SearchContactsSortedParams struct {
	CadenceFilter  interface{} `json:"cadence_filter"`
	FollowupFilter interface{} `json:"followup_filter"`
	SearchQuery    string      `json:"search_query"`
	SortField      interface{} `json:"sort_field"`
	SortOrder      interface{} `json:"sort_order"`
	PageOffset     int32       `json:"page_offset"`
	PageLimit      int32       `json:"page_limit"`
}

func (q *Queries) SearchContactsSorted(ctx context.Context, arg SearchContactsSortedParams) ([]*Contact, error) {
	rows, err := q.db.Query(ctx, SearchContactsSorted,
		arg.CadenceFilter,
		arg.FollowupFilter,
		arg.SearchQuery,
		arg.SortField,
		arg.SortOrder,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Location,
			&i.Birthday,
			&i.HowMet,
			&i.Cadence,
			&i.LastContacted,
			&i.ProfilePhoto,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContactBy,
			&i.LastInteractionAt,
			&i.LastOutreachAt,
			&i.LastResponseAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SnapshotContactCadenceFields = `-- name: SnapshotContactCadenceFields :one
SELECT last_contacted, last_outreach_at, last_response_at, contact_by
FROM contact
WHERE id = $1 AND deleted_at IS NULL
`

type SnapshotContactCadenceFieldsRow struct {
	LastContacted  pgtype.Timestamptz `json:"last_contacted"`
	LastOutreachAt pgtype.Timestamptz `json:"last_outreach_at"`
	LastResponseAt pgtype.Timestamptz `json:"last_response_at"`
	ContactBy      pgtype.Date        `json:"contact_by"`
}

// Returns only the four spec-listed cadence columns. Used by PR 7's
// direct-path post-commit closure to capture the post-image inside its
// own short-lived tx (plan Decision 5). Consumer does NOT call this —
// consumer reads prev from the event payload (plan Decision 2a).
func (q *Queries) SnapshotContactCadenceFields(ctx context.Context, id pgtype.UUID) (*SnapshotContactCadenceFieldsRow, error) {
	row := q.db.QueryRow(ctx, SnapshotContactCadenceFields, id)
	var i SnapshotContactCadenceFieldsRow
	err := row.Scan(
		&i.LastContacted,
		&i.LastOutreachAt,
		&i.LastResponseAt,
		&i.ContactBy,
	)
	return &i, err
}

const SoftDeleteContact = `-- name: SoftDeleteContact :exec
UPDATE contact SET
  deleted_at = NOW(),
  updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteContact(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, SoftDeleteContact, id)
	return err
}

const UpdateContact = `-- name: UpdateContact :one
UPDATE contact SET
  full_name = $2,
  location = $3,
  birthday = $4,
  how_met = $5,
  cadence = $6,
  profile_photo = $7,
  updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, full_name, location, birthday, how_met, cadence, last_contacted, profile_photo, deleted_at, created_at, updated_at, contact_by, last_interaction_at, last_outreach_at, last_response_at
`

type UpdateContactParams struct {
	ID           pgtype.UUID `json:"id"`
	FullName     string      `json:"full_name"`
	Location     pgtype.Text `json:"location"`
	Birthday     pgtype.Date `json:"birthday"`
	HowMet       pgtype.Text `json:"how_met"`
	Cadence      pgtype.Text `json:"cadence"`
	ProfilePhoto pgtype.Text `json:"profile_photo"`
}

// Profile-only update path (PR 8 cutover; plan Step 8). Writes name,
// location, birthday, how_met, cadence, profile_photo — NEVER writes
// last_contacted, last_outreach_at, last_response_at, or contact_by.
// ContactService.UpdateContact handles the cadence-change side-effect
// (recomputing contact_by) by calling CadenceUpdater.ApplyContactByOverride
// in the same tx; EnrichmentService uses this query for cadence-absent
// inferred fields and CadenceUpdater.ApplyContactByOverride when the
// input DTO carries an explicit cadence preference.
func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (*Contact, error) {
	row := q.db.QueryRow(ctx, UpdateContact,
		arg.ID,
		arg.FullName,
		arg.Location,
		arg.Birthday,
		arg.HowMet,
		arg.Cadence,
		arg.ProfilePhoto,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Location,
		&i.Birthday,
		&i.HowMet,
		&i.Cadence,
		&i.LastContacted,
		&i.ProfilePhoto,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContactBy,
		&i.LastInteractionAt,
		&i.LastOutreachAt,
		&i.LastResponseAt,
	)
	return &i, err
}

const UpdateContactBy = `-- name: UpdateContactBy :exec
UPDATE contact SET
  contact_by = $2,
  updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateContactByParams struct {
	ID        pgtype.UUID `json:"id"`
	ContactBy pgtype.Date `json:"contact_by"`
}

// Updates just the contact_by field (for Todoist deadline sync).
func (q *Queries) UpdateContactBy(ctx context.Context, arg UpdateContactByParams) error {
	_, err := q.db.Exec(ctx, UpdateContactBy, arg.ID, arg.ContactBy)
	return err
}

const UpdateContactCadenceForward = `-- name: UpdateContactCadenceForward :exec
UPDATE contact SET
    last_contacted = CASE
        WHEN $1::boolean
          AND (last_contacted IS NULL OR $2::timestamptz > last_contacted)
        THEN $2::timestamptz
        ELSE last_contacted
    END,
    last_interaction_at = CASE
        WHEN $1::boolean
          AND (last_interaction_at IS NULL OR $2::timestamptz > last_interaction_at)
        THEN $2::timestamptz
        ELSE last_interaction_at
    END,
    last_outreach_at = CASE
        WHEN $3::boolean
          AND (last_outreach_at IS NULL OR $4::timestamptz > last_outreach_at)
        THEN $4::timestamptz
        ELSE last_outreach_at
    END,
    last_response_at = CASE
        WHEN $5::boolean
          AND (last_response_at IS NULL OR $6::timestamptz > last_response_at)
        THEN $6::timestamptz
        ELSE last_response_at
    END,
    contact_by = CASE
        WHEN $7::boolean
          AND $8::date IS NOT NULL
          AND (contact_by IS NULL OR $8::date > contact_by)
        THEN $8::date
        ELSE contact_by
    END,
    updated_at = NOW()
WHERE id = $9 AND deleted_at IS NULL
`

type UpdateContactCadenceForwardParams struct {
	ApplyLastContacted  bool               `json:"apply_last_contacted"`
	LastContacted       pgtype.Timestamptz `json:"last_contacted"`
	ApplyLastOutreachAt bool               `json:"apply_last_outreach_at"`
	LastOutreachAt      pgtype.Timestamptz `json:"last_outreach_at"`
	ApplyLastResponseAt bool               `json:"apply_last_response_at"`
	LastResponseAt      pgtype.Timestamptz `json:"last_response_at"`
	ApplyContactBy      bool               `json:"apply_contact_by"`
	ContactBy           pgtype.Date        `json:"contact_by"`
	ID                  pgtype.UUID        `json:"id"`
}

// Forward-only cadence write (spec §3.4.2). Each of the four cadence
// columns is updated only when its apply-flag is true AND the new value
// strictly exceeds the existing one (or the existing is NULL). Unused
// by the PR 7 runtime path (consumer computes in memory per plan
// Decision 4); shipped so sqlc validates the SQL against the schema and
// PR 8 cutover can wire it without a second schema-validation step.
//
// last_interaction_at piggybacks on apply_last_contacted: the direct-path
// queries UpdateContactResponseFields/UpdateContactMutualFields historically
// bumped last_interaction_at together with last_contacted for inbound +
// mutual, and never for outbound-only. Replicating that here keeps the
// inbound/mutual → "last non-outbound interaction" invariant intact
// post-cutover without adding a 5th apply flag.
func (q *Queries) UpdateContactCadenceForward(ctx context.Context, arg UpdateContactCadenceForwardParams) error {
	_, err := q.db.Exec(ctx, UpdateContactCadenceForward,
		arg.ApplyLastContacted,
		arg.LastContacted,
		arg.ApplyLastOutreachAt,
		arg.LastOutreachAt,
		arg.ApplyLastResponseAt,
		arg.LastResponseAt,
		arg.ApplyContactBy,
		arg.ContactBy,
		arg.ID,
	)
	return err
}

const UpdateContactCadenceUnconditional = `-- name: UpdateContactCadenceUnconditional :exec
UPDATE contact SET
    last_contacted = CASE
        WHEN $1::boolean THEN $2::timestamptz
        ELSE last_contacted
    END,
    last_interaction_at = CASE
        WHEN $1::boolean THEN $2::timestamptz
        ELSE last_interaction_at
    END,
    last_outreach_at = CASE
        WHEN $3::boolean THEN $4::timestamptz
        ELSE last_outreach_at
    END,
    last_response_at = CASE
        WHEN $5::boolean THEN $6::timestamptz
        ELSE last_response_at
    END,
    contact_by = CASE
        WHEN $7::boolean THEN $8::date
        ELSE contact_by
    END,
    updated_at = NOW()
WHERE id = $9 AND deleted_at IS NULL
`

type UpdateContactCadenceUnconditionalParams struct {
	ApplyLastContacted  bool               `json:"apply_last_contacted"`
	LastContacted       pgtype.Timestamptz `json:"last_contacted"`
	ApplyLastOutreachAt bool               `json:"apply_last_outreach_at"`
	LastOutreachAt      pgtype.Timestamptz `json:"last_outreach_at"`
	ApplyLastResponseAt bool               `json:"apply_last_response_at"`
	LastResponseAt      pgtype.Timestamptz `json:"last_response_at"`
	ApplyContactBy      bool               `json:"apply_contact_by"`
	ContactBy           pgtype.Date        `json:"contact_by"`
	ID                  pgtype.UUID        `json:"id"`
}

// Manual-source branch (spec §3.4.2 "manual-source exception"): user
// correction — any passed-in value replaces the existing one
// unconditionally. Apply-flags still gate which columns are touched
// (e.g., a manual outbound still shouldn't bump last_contacted per
// direction rules). Unused by the PR 7 runtime path; shipped for PR 8.
//
// last_interaction_at piggybacks on apply_last_contacted — see the
// UpdateContactCadenceForward comment above. Unconditional semantics so
// manual-source corrections overwrite regardless of existing value.
func (q *Queries) UpdateContactCadenceUnconditional(ctx context.Context, arg UpdateContactCadenceUnconditionalParams) error {
	_, err := q.db.Exec(ctx, UpdateContactCadenceUnconditional,
		arg.ApplyLastContacted,
		arg.LastContacted,
		arg.ApplyLastOutreachAt,
		arg.LastOutreachAt,
		arg.ApplyLastResponseAt,
		arg.LastResponseAt,
		arg.ApplyContactBy,
		arg.ContactBy,
		arg.ID,
	)
	return err
}

const UpdateContactLastContacted = `-- name: UpdateContactLastContacted :exec
UPDATE contact SET
  last_contacted = $2,
  contact_by = $3,
  last_interaction_at = $2,
  last_outreach_at = $2,
  last_response_at = $2,
  updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateContactLastContactedParams struct {
	ID            pgtype.UUID        `json:"id"`
	LastContacted pgtype.Timestamptz `json:"last_contacted"`
	ContactBy     pgtype.Date        `json:"contact_by"`
}

// Updates last_contacted, contact_by, and all direction timestamp fields (for mutual interactions)
func (q *Queries) UpdateContactLastContacted(ctx context.Context, arg UpdateContactLastContactedParams) error {
	_, err := q.db.Exec(ctx, UpdateContactLastContacted, arg.ID, arg.LastContacted, arg.ContactBy)
	return err
}

const UpdateContactLastContactedIfLater = `-- name: UpdateContactLastContactedIfLater :exec
UPDATE contact SET
  last_contacted = GREATEST(COALESCE(last_contacted, '1970-01-01'::timestamptz), $2),
  last_interaction_at = GREATEST(COALESCE(last_interaction_at, '1970-01-01'::timestamptz), $2),
  last_outreach_at = GREATEST(COALESCE(last_outreach_at, '1970-01-01'::timestamptz), $2),
  last_response_at = GREATEST(COALESCE(last_response_at, '1970-01-01'::timestamptz), $2),
  contact_by = CASE
    WHEN $2 > COALESCE(last_contacted, '1970-01-01'::timestamptz) AND cadence IS NOT NULL AND cadence != '' THEN
      ($2::date + CASE cadence
        WHEN 'weekly' THEN 7
        WHEN 'biweekly' THEN 14
        WHEN 'monthly' THEN 30
        WHEN 'quarterly' THEN 90
        WHEN 'biannual' THEN 180
        WHEN 'annual' THEN 365
        ELSE 0
      END)
    WHEN $2 > COALESCE(last_contacted, '1970-01-01'::timestamptz) THEN NULL
    ELSE contact_by
  END,
  updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateContactLastContactedIfLaterParams struct {
	ID            pgtype.UUID        `json:"id"`
	LastContacted pgtype.Timestamptz `json:"last_contacted"`
}

// Updates last_contacted and contact_by only if the new date is later.
// Also updates direction timestamp fields (this path is used by gcal, which is always mutual).
// contact_by is recalculated from the new last_contacted date using the contact's existing cadence.
// Cadence day mappings: weekly=7, biweekly=14, monthly=30, quarterly=90, biannual=180, annual=365
func (q *Queries) UpdateContactLastContactedIfLater(ctx context.Context, arg UpdateContactLastContactedIfLaterParams) error {
	_, err := q.db.Exec(ctx, UpdateContactLastContactedIfLater, arg.ID, arg.LastContacted)
	return err
}

const UpdateContactMutualFields = `-- name: UpdateContactMutualFields :exec
UPDATE contact SET
  last_contacted = CASE
    WHEN $1::boolean THEN $2::timestamptz
    WHEN $2::timestamptz > COALESCE(last_contacted, '1970-01-01'::timestamptz) THEN $2::timestamptz
    ELSE last_contacted
  END,
  last_interaction_at = CASE
    WHEN $1::boolean THEN $2::timestamptz
    WHEN $2::timestamptz > COALESCE(last_interaction_at, '1970-01-01'::timestamptz) THEN $2::timestamptz
    ELSE last_interaction_at
  END,
  last_outreach_at = CASE
    WHEN $1::boolean THEN $2::timestamptz
    WHEN $2::timestamptz > COALESCE(last_outreach_at, '1970-01-01'::timestamptz) THEN $2::timestamptz
    ELSE last_outreach_at
  END,
  last_response_at = CASE
    WHEN $1::boolean THEN $2::timestamptz
    WHEN $2::timestamptz > COALESCE(last_response_at, '1970-01-01'::timestamptz) THEN $2::timestamptz
    ELSE last_response_at
  END,
  contact_by = CASE
    WHEN $3::date IS NOT NULL THEN $3::date
    ELSE contact_by
  END,
  updated_at = NOW()
WHERE id = $4 AND deleted_at IS NULL
`

type UpdateContactMutualFieldsParams struct {
	IsManual   bool               `json:"is_manual"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	ContactBy  pgtype.Date        `json:"contact_by"`
	ID         pgtype.UUID        `json:"id"`
}

// Updates all direction fields + last_contacted + contact_by (for mutual interactions).
// Uses forward-only semantics for automated sources; manual always updates.
func (q *Queries) UpdateContactMutualFields(ctx context.Context, arg UpdateContactMutualFieldsParams) error {
	_, err := q.db.Exec(ctx, UpdateContactMutualFields,
		arg.IsManual,
		arg.OccurredAt,
		arg.ContactBy,
		arg.ID,
	)
	return err
}

const UpdateContactOutreachAt = `-- name: UpdateContactOutreachAt :exec
UPDATE contact SET
  last_outreach_at = CASE
    WHEN $1::boolean THEN $2::timestamptz
    WHEN $2::timestamptz > COALESCE(last_outreach_at, '1970-01-01'::timestamptz) THEN $2::timestamptz
    ELSE last_outreach_at
  END,
  updated_at = NOW()
WHERE id = $3 AND deleted_at IS NULL
`

type UpdateContactOutreachAtParams struct {
	IsManual   bool               `json:"is_manual"`
	OutreachAt pgtype.Timestamptz `json:"outreach_at"`
	ID         pgtype.UUID        `json:"id"`
}

// Updates only last_outreach_at (for outbound-only interactions).
// Uses forward-only semantics: only updates if the new time is later.
func (q *Queries) UpdateContactOutreachAt(ctx context.Context, arg UpdateContactOutreachAtParams) error {
	_, err := q.db.Exec(ctx, UpdateContactOutreachAt, arg.IsManual, arg.OutreachAt, arg.ID)
	return err
}

const UpdateContactResponseFields = `-- name: UpdateContactResponseFields :exec
UPDATE contact SET
  last_contacted = CASE
    WHEN $1::boolean THEN $2::timestamptz
    WHEN $2::timestamptz > COALESCE(last_contacted, '1970-01-01'::timestamptz) THEN $2::timestamptz
    ELSE last_contacted
  END,
  last_interaction_at = CASE
    WHEN $1::boolean THEN $2::timestamptz
    WHEN $2::timestamptz > COALESCE(last_interaction_at, '1970-01-01'::timestamptz) THEN $2::timestamptz
    ELSE last_interaction_at
  END,
  last_response_at = CASE
    WHEN $1::boolean THEN $2::timestamptz
    WHEN $2::timestamptz > COALESCE(last_response_at, '1970-01-01'::timestamptz) THEN $2::timestamptz
    ELSE last_response_at
  END,
  contact_by = CASE
    WHEN $3::date IS NOT NULL THEN $3::date
    ELSE contact_by
  END,
  updated_at = NOW()
WHERE id = $4 AND deleted_at IS NULL
`

type UpdateContactResponseFieldsParams struct {
	IsManual   bool               `json:"is_manual"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	ContactBy  pgtype.Date        `json:"contact_by"`
	ID         pgtype.UUID        `json:"id"`
}

// Updates last_contacted, last_interaction_at, last_response_at, and contact_by (for inbound interactions).
// Uses forward-only semantics for automated sources; manual always updates.
func (q *Queries) UpdateContactResponseFields(ctx context.Context, arg UpdateContactResponseFieldsParams) error {
	_, err := q.db.Exec(ctx, UpdateContactResponseFields,
		arg.IsManual,
		arg.OccurredAt,
		arg.ContactBy,
		arg.ID,
	)
	return err
}
