// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contact_method.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateContactMethod = `-- name: CreateContactMethod :one
INSERT INTO contact_method (
    contact_id,
    type,
    value,
    is_primary
) VALUES (
    $1, $2, $3, $4
) RETURNING id, contact_id, type, value, is_primary, created_at, updated_at
`

type CreateContactMethodParams struct {
	ContactID pgtype.UUID `json:"contact_id"`
	Type      string      `json:"type"`
	Value     string      `json:"value"`
	IsPrimary pgtype.Bool `json:"is_primary"`
}

func (q *Queries) CreateContactMethod(ctx context.Context, arg CreateContactMethodParams) (*ContactMethod, error) {
	row := q.db.QueryRow(ctx, CreateContactMethod,
		arg.ContactID,
		arg.Type,
		arg.Value,
		arg.IsPrimary,
	)
	var i ContactMethod
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Type,
		&i.Value,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const DeleteContactMethodsByContact = `-- name: DeleteContactMethodsByContact :exec
DELETE FROM contact_method
WHERE contact_id = $1
`

func (q *Queries) DeleteContactMethodsByContact(ctx context.Context, contactID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteContactMethodsByContact, contactID)
	return err
}

const FindMethodsByNormalizedValue = `-- name: FindMethodsByNormalizedValue :many
SELECT cm.id, cm.contact_id, cm.type, cm.value, cm.is_primary, cm.created_at, cm.updated_at, c.full_name as contact_name
FROM contact_method cm
JOIN contact c ON c.id = cm.contact_id
WHERE cm.type = ANY($1::text[])
  AND LOWER(TRIM(cm.value)) = $2
  AND c.deleted_at IS NULL
`

type FindMethodsByNormalizedValueParams struct {
	Column1 []string `json:"column_1"`
	Value   string   `json:"value"`
}

type FindMethodsByNormalizedValueRow struct {
	ID          pgtype.UUID        `json:"id"`
	ContactID   pgtype.UUID        `json:"contact_id"`
	Type        string             `json:"type"`
	Value       string             `json:"value"`
	IsPrimary   pgtype.Bool        `json:"is_primary"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ContactName string             `json:"contact_name"`
}

func (q *Queries) FindMethodsByNormalizedValue(ctx context.Context, arg FindMethodsByNormalizedValueParams) ([]*FindMethodsByNormalizedValueRow, error) {
	rows, err := q.db.Query(ctx, FindMethodsByNormalizedValue, arg.Column1, arg.Value)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FindMethodsByNormalizedValueRow{}
	for rows.Next() {
		var i FindMethodsByNormalizedValueRow
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Type,
			&i.Value,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContactName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListContactMethodsByContact = `-- name: ListContactMethodsByContact :many

SELECT id, contact_id, type, value, is_primary, created_at, updated_at FROM contact_method
WHERE contact_id = $1
ORDER BY is_primary DESC, created_at ASC
`

// Contact method queries
func (q *Queries) ListContactMethodsByContact(ctx context.Context, contactID pgtype.UUID) ([]*ContactMethod, error) {
	rows, err := q.db.Query(ctx, ListContactMethodsByContact, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ContactMethod{}
	for rows.Next() {
		var i ContactMethod
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Type,
			&i.Value,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateContactMethodValue = `-- name: UpdateContactMethodValue :one
UPDATE contact_method
SET value = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, contact_id, type, value, is_primary, created_at, updated_at
`

type UpdateContactMethodValueParams struct {
	ID    pgtype.UUID `json:"id"`
	Value string      `json:"value"`
}

func (q *Queries) UpdateContactMethodValue(ctx context.Context, arg UpdateContactMethodValueParams) (*ContactMethod, error) {
	row := q.db.QueryRow(ctx, UpdateContactMethodValue, arg.ID, arg.Value)
	var i ContactMethod
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Type,
		&i.Value,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
