// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contact_merge.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountMergeCalendarEvents = `-- name: CountMergeCalendarEvents :one
SELECT COUNT(*) FROM calendar_event
WHERE $1::uuid = ANY(matched_contact_ids)
`

// Count calendar events involving a contact (for merge preview)
func (q *Queries) CountMergeCalendarEvents(ctx context.Context, dollar_1 pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, CountMergeCalendarEvents, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountMergeContactMethods = `-- name: CountMergeContactMethods :one
SELECT COUNT(*) FROM contact_method
WHERE contact_id = $1
`

// Count contact methods for a contact (for merge preview)
func (q *Queries) CountMergeContactMethods(ctx context.Context, contactID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, CountMergeContactMethods, contactID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountMergeInteractions = `-- name: CountMergeInteractions :one
SELECT COUNT(*) FROM interaction
WHERE contact_id = $1
`

// Count interactions for a contact (for merge preview)
func (q *Queries) CountMergeInteractions(ctx context.Context, contactID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, CountMergeInteractions, contactID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountMergeNotes = `-- name: CountMergeNotes :one
SELECT COUNT(*) FROM note
WHERE contact_id = $1
`

// Count notes for a contact (for merge preview)
func (q *Queries) CountMergeNotes(ctx context.Context, contactID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, CountMergeNotes, contactID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const DeduplicateCalendarEventContacts = `-- name: DeduplicateCalendarEventContacts :exec
UPDATE calendar_event
SET matched_contact_ids = (
    SELECT array_agg(DISTINCT contact_id)
    FROM unnest(matched_contact_ids) AS contact_id
),
    updated_at = NOW()
WHERE $1::uuid = ANY(matched_contact_ids)
  AND (
    SELECT COUNT(*) FROM unnest(matched_contact_ids) AS cid WHERE cid = $1::uuid
  ) > 1
`

// Remove duplicate contact IDs that may result from merge
// Uses subquery with DISTINCT to rebuild the array without duplicates
func (q *Queries) DeduplicateCalendarEventContacts(ctx context.Context, targetContactID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeduplicateCalendarEventContacts, targetContactID)
	return err
}

const DeleteDuplicateContactMethods = `-- name: DeleteDuplicateContactMethods :exec
DELETE FROM contact_method cm_source
WHERE cm_source.contact_id = $1
  AND EXISTS (
    SELECT 1 FROM contact_method cm_target
    WHERE cm_target.contact_id = $2
      AND cm_target.value_normalized = cm_source.value_normalized
      AND cm_target.type = cm_source.type
  )
`

type DeleteDuplicateContactMethodsParams struct {
	SourceContactID pgtype.UUID `json:"source_contact_id"`
	TargetContactID pgtype.UUID `json:"target_contact_id"`
}

// Delete contact methods from source that already exist in target (by normalized value and type)
func (q *Queries) DeleteDuplicateContactMethods(ctx context.Context, arg DeleteDuplicateContactMethodsParams) error {
	_, err := q.db.Exec(ctx, DeleteDuplicateContactMethods, arg.SourceContactID, arg.TargetContactID)
	return err
}

const DemoteSourcePrimaryMethods = `-- name: DemoteSourcePrimaryMethods :exec
UPDATE contact_method cm_source
SET is_primary = false,
    updated_at = NOW()
WHERE cm_source.contact_id = $1
  AND cm_source.is_primary = true
  AND cm_source.type IN (
    SELECT cm_target.type FROM contact_method cm_target
    WHERE cm_target.contact_id = $2
      AND cm_target.is_primary = true
  )
`

type DemoteSourcePrimaryMethodsParams struct {
	SourceContactID pgtype.UUID `json:"source_contact_id"`
	TargetContactID pgtype.UUID `json:"target_contact_id"`
}

// Demote source's primary contact methods when target already has a primary for that type
// This prevents violation of the unique partial index on (contact_id, type) WHERE is_primary = true
func (q *Queries) DemoteSourcePrimaryMethods(ctx context.Context, arg DemoteSourcePrimaryMethodsParams) error {
	_, err := q.db.Exec(ctx, DemoteSourcePrimaryMethods, arg.SourceContactID, arg.TargetContactID)
	return err
}

const FindDuplicateContactMethods = `-- name: FindDuplicateContactMethods :many
SELECT cm_source.value, cm_source.type
FROM contact_method cm_source
INNER JOIN contact_method cm_target
  ON cm_source.value_normalized = cm_target.value_normalized
  AND cm_source.type = cm_target.type
WHERE cm_source.contact_id = $1
  AND cm_target.contact_id = $2
`

type FindDuplicateContactMethodsParams struct {
	SourceContactID pgtype.UUID `json:"source_contact_id"`
	TargetContactID pgtype.UUID `json:"target_contact_id"`
}

type FindDuplicateContactMethodsRow struct {
	Value string `json:"value"`
	Type  string `json:"type"`
}

// Find contact methods that exist in both source and target
// Used to identify duplicates that will be skipped during merge
func (q *Queries) FindDuplicateContactMethods(ctx context.Context, arg FindDuplicateContactMethodsParams) ([]*FindDuplicateContactMethodsRow, error) {
	rows, err := q.db.Query(ctx, FindDuplicateContactMethods, arg.SourceContactID, arg.TargetContactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FindDuplicateContactMethodsRow{}
	for rows.Next() {
		var i FindDuplicateContactMethodsRow
		if err := rows.Scan(&i.Value, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ReplaceContactInCalendarEvents = `-- name: ReplaceContactInCalendarEvents :exec
UPDATE calendar_event
SET matched_contact_ids = array_replace(matched_contact_ids, $1::uuid, $2::uuid),
    updated_at = NOW()
WHERE $1::uuid = ANY(matched_contact_ids)
`

type ReplaceContactInCalendarEventsParams struct {
	SourceContactID pgtype.UUID `json:"source_contact_id"`
	TargetContactID pgtype.UUID `json:"target_contact_id"`
}

// Replace source contact ID with target contact ID in calendar event matched_contact_ids array
// Uses array_replace for efficient in-place replacement
func (q *Queries) ReplaceContactInCalendarEvents(ctx context.Context, arg ReplaceContactInCalendarEventsParams) error {
	_, err := q.db.Exec(ctx, ReplaceContactInCalendarEvents, arg.SourceContactID, arg.TargetContactID)
	return err
}

const RepointExternalContactsToContact = `-- name: RepointExternalContactsToContact :exec
UPDATE external_contact
SET crm_contact_id = $1,
    updated_at = NOW()
WHERE crm_contact_id = $2
`

type RepointExternalContactsToContactParams struct {
	TargetContactID pgtype.UUID `json:"target_contact_id"`
	SourceContactID pgtype.UUID `json:"source_contact_id"`
}

// Re-point import links from the merge source to the target. Both
// crm_contact_id indexes are non-unique, so this is collision-free. The
// external_contact upsert preserves crm_contact_id on re-sync, so the
// repoint is not overwritten by the next daemon sync.
func (q *Queries) RepointExternalContactsToContact(ctx context.Context, arg RepointExternalContactsToContactParams) error {
	_, err := q.db.Exec(ctx, RepointExternalContactsToContact, arg.TargetContactID, arg.SourceContactID)
	return err
}

const RepointIdentitiesToContact = `-- name: RepointIdentitiesToContact :exec
UPDATE external_identity
SET contact_id = $1,
    updated_at = NOW()
WHERE contact_id = $2
`

type RepointIdentitiesToContactParams struct {
	TargetContactID pgtype.UUID `json:"target_contact_id"`
	SourceContactID pgtype.UUID `json:"source_contact_id"`
}

// Re-point identity-cache rows from the merge source (loser) to the target
// (winner) so future inbound events from the loser's handles attribute to
// the survivor. Collision-free: external_identity uniqueness is on
// (identifier, identifier_type, source) globally, so at most one row exists
// per triple regardless of contact.
func (q *Queries) RepointIdentitiesToContact(ctx context.Context, arg RepointIdentitiesToContactParams) error {
	_, err := q.db.Exec(ctx, RepointIdentitiesToContact, arg.TargetContactID, arg.SourceContactID)
	return err
}

const RepointMessagesMessageContact = `-- name: RepointMessagesMessageContact :exec
UPDATE messages_message
SET matched_contact_id = $1
WHERE matched_contact_id = $2
`

type RepointMessagesMessageContactParams struct {
	TargetContactID pgtype.UUID `json:"target_contact_id"`
	SourceContactID pgtype.UUID `json:"source_contact_id"`
}

// Re-point iMessage staging rows (committed pre-merge, incl. unprocessed)
// from the merge source to the target. messages_message uniqueness is on
// the message guid, not the contact — collision-free. NOTE: the table has
// no updated_at column (049); do not set one.
func (q *Queries) RepointMessagesMessageContact(ctx context.Context, arg RepointMessagesMessageContactParams) error {
	_, err := q.db.Exec(ctx, RepointMessagesMessageContact, arg.TargetContactID, arg.SourceContactID)
	return err
}

const RepointPhoneCallContact = `-- name: RepointPhoneCallContact :exec
UPDATE phone_call
SET matched_contact_id = $1
WHERE matched_contact_id = $2
`

type RepointPhoneCallContactParams struct {
	TargetContactID pgtype.UUID `json:"target_contact_id"`
	SourceContactID pgtype.UUID `json:"source_contact_id"`
}

// Re-point call staging rows from the merge source to the target.
// Uniqueness is on call_unique_id — collision-free. NOTE: phone_call has
// no updated_at column (055); do not set one.
func (q *Queries) RepointPhoneCallContact(ctx context.Context, arg RepointPhoneCallContactParams) error {
	_, err := q.db.Exec(ctx, RepointPhoneCallContact, arg.TargetContactID, arg.SourceContactID)
	return err
}

const RepointTelegramMessageContact = `-- name: RepointTelegramMessageContact :exec
UPDATE telegram_message
SET matched_contact_id = $1
WHERE matched_contact_id = $2
`

type RepointTelegramMessageContactParams struct {
	TargetContactID pgtype.UUID `json:"target_contact_id"`
	SourceContactID pgtype.UUID `json:"source_contact_id"`
}

// Re-point Telegram staging rows from the merge source to the target.
// Uniqueness is on (telegram_chat_id, telegram_message_id) — collision-free.
// NOTE: telegram_message has no updated_at column (032); do not set one.
func (q *Queries) RepointTelegramMessageContact(ctx context.Context, arg RepointTelegramMessageContactParams) error {
	_, err := q.db.Exec(ctx, RepointTelegramMessageContact, arg.TargetContactID, arg.SourceContactID)
	return err
}

const TransferContactMethods = `-- name: TransferContactMethods :exec

UPDATE contact_method
SET contact_id = $1,
    updated_at = NOW()
WHERE contact_id = $2
`

type TransferContactMethodsParams struct {
	TargetContactID pgtype.UUID `json:"target_contact_id"`
	SourceContactID pgtype.UUID `json:"source_contact_id"`
}

// Contact merge queries
// These queries support merging one contact (source) into another (target)
// Transfer contact methods from source to target contact
func (q *Queries) TransferContactMethods(ctx context.Context, arg TransferContactMethodsParams) error {
	_, err := q.db.Exec(ctx, TransferContactMethods, arg.TargetContactID, arg.SourceContactID)
	return err
}

const TransferInteractions = `-- name: TransferInteractions :exec
UPDATE interaction
SET contact_id = $1
WHERE contact_id = $2
`

type TransferInteractionsParams struct {
	TargetContactID pgtype.UUID `json:"target_contact_id"`
	SourceContactID pgtype.UUID `json:"source_contact_id"`
}

// Transfer interactions from source to target contact (includes soft-deleted for audit trail)
func (q *Queries) TransferInteractions(ctx context.Context, arg TransferInteractionsParams) error {
	_, err := q.db.Exec(ctx, TransferInteractions, arg.TargetContactID, arg.SourceContactID)
	return err
}

const TransferNotes = `-- name: TransferNotes :exec
UPDATE note
SET contact_id = $1,
    updated_at = NOW()
WHERE contact_id = $2
`

type TransferNotesParams struct {
	TargetContactID pgtype.UUID `json:"target_contact_id"`
	SourceContactID pgtype.UUID `json:"source_contact_id"`
}

// Transfer notes from source to target contact
func (q *Queries) TransferNotes(ctx context.Context, arg TransferNotesParams) error {
	_, err := q.db.Exec(ctx, TransferNotes, arg.TargetContactID, arg.SourceContactID)
	return err
}
