// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entity.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CreateEntity = `-- name: CreateEntity :one

INSERT INTO entity (node_id, subtype, normalized_name, external_ref, detail)
VALUES ($1, $2, $3, $4, $5)
RETURNING node_id, subtype, normalized_name, external_ref, detail
`

type CreateEntityParams struct {
	NodeID         pgtype.UUID `json:"node_id"`
	Subtype        string      `json:"subtype"`
	NormalizedName string      `json:"normalized_name"`
	ExternalRef    pgtype.Text `json:"external_ref"`
	Detail         []byte      `json:"detail"`
}

// Entity subtype queries (SP1 graph foundation).
func (q *Queries) CreateEntity(ctx context.Context, arg CreateEntityParams) (*Entity, error) {
	row := q.db.QueryRow(ctx, CreateEntity,
		arg.NodeID,
		arg.Subtype,
		arg.NormalizedName,
		arg.ExternalRef,
		arg.Detail,
	)
	var i Entity
	err := row.Scan(
		&i.NodeID,
		&i.Subtype,
		&i.NormalizedName,
		&i.ExternalRef,
		&i.Detail,
	)
	return &i, err
}

const FindEntityBySubtypeName = `-- name: FindEntityBySubtypeName :one
SELECT node_id, subtype, normalized_name, external_ref, detail FROM entity WHERE subtype = $1 AND normalized_name = $2
`

type FindEntityBySubtypeNameParams struct {
	Subtype        string `json:"subtype"`
	NormalizedName string `json:"normalized_name"`
}

// Entity-resolution dedup lookup against the (subtype, normalized_name) unique.
func (q *Queries) FindEntityBySubtypeName(ctx context.Context, arg FindEntityBySubtypeNameParams) (*Entity, error) {
	row := q.db.QueryRow(ctx, FindEntityBySubtypeName, arg.Subtype, arg.NormalizedName)
	var i Entity
	err := row.Scan(
		&i.NodeID,
		&i.Subtype,
		&i.NormalizedName,
		&i.ExternalRef,
		&i.Detail,
	)
	return &i, err
}

const GetEntity = `-- name: GetEntity :one
SELECT node_id, subtype, normalized_name, external_ref, detail FROM entity WHERE node_id = $1
`

func (q *Queries) GetEntity(ctx context.Context, nodeID pgtype.UUID) (*Entity, error) {
	row := q.db.QueryRow(ctx, GetEntity, nodeID)
	var i Entity
	err := row.Scan(
		&i.NodeID,
		&i.Subtype,
		&i.NormalizedName,
		&i.ExternalRef,
		&i.Detail,
	)
	return &i, err
}

const UpdateEntityDetail = `-- name: UpdateEntityDetail :exec
UPDATE entity SET detail = detail || $2 WHERE node_id = $1
`

type UpdateEntityDetailParams struct {
	NodeID pgtype.UUID `json:"node_id"`
	Detail []byte      `json:"detail"`
}

// Merge-patches the per-instance detail JSONB (e.g. a tag color edit) using the
// || concatenation operator so other keys are preserved, not overwritten.
func (q *Queries) UpdateEntityDetail(ctx context.Context, arg UpdateEntityDetailParams) error {
	_, err := q.db.Exec(ctx, UpdateEntityDetail, arg.NodeID, arg.Detail)
	return err
}
