// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_shadow_cadence_observation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountCadenceShadowObservationsByWriter = `-- name: CountCadenceShadowObservationsByWriter :one
SELECT COUNT(*) FROM event_shadow_cadence_observation
WHERE writer = $1
`

// Used by integration tests and bake-window evidence collection.
func (q *Queries) CountCadenceShadowObservationsByWriter(ctx context.Context, writer string) (int64, error) {
	row := q.db.QueryRow(ctx, CountCadenceShadowObservationsByWriter, writer)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const FindCadenceShadowDivergences = `-- name: FindCadenceShadowDivergences :many
WITH direct_obs AS (
    SELECT id, event_id, writer, contact_id, source, direction, branch, occurred_at, prev_last_contacted, prev_last_outreach_at, prev_last_response_at, prev_contact_by, next_last_contacted, next_last_outreach_at, next_last_response_at, next_contact_by, apply_last_contacted, apply_last_outreach_at, apply_last_response_at, apply_contact_by, observed_at FROM event_shadow_cadence_observation
    WHERE writer = 'direct'
      AND observed_at >= $1::timestamptz
      AND observed_at <  $2::timestamptz
),
consumer_obs AS (
    SELECT id, event_id, writer, contact_id, source, direction, branch, occurred_at, prev_last_contacted, prev_last_outreach_at, prev_last_response_at, prev_contact_by, next_last_contacted, next_last_outreach_at, next_last_response_at, next_contact_by, apply_last_contacted, apply_last_outreach_at, apply_last_response_at, apply_contact_by, observed_at FROM event_shadow_cadence_observation
    WHERE writer = 'consumer'
      AND observed_at >= $1::timestamptz
      AND observed_at <  $2::timestamptz
),
joined AS (
    SELECT
        COALESCE(d.event_id, c.event_id)       AS event_id,
        COALESCE(d.contact_id, c.contact_id)   AS contact_id,
        GREATEST(d.observed_at, c.observed_at) AS pair_observed_at,
        d.branch                               AS direct_branch,
        c.branch                               AS consumer_branch,
        d.next_last_contacted                  AS direct_next_last_contacted,
        c.next_last_contacted                  AS consumer_next_last_contacted,
        d.next_last_outreach_at                AS direct_next_last_outreach_at,
        c.next_last_outreach_at                AS consumer_next_last_outreach_at,
        d.next_last_response_at                AS direct_next_last_response_at,
        c.next_last_response_at                AS consumer_next_last_response_at,
        d.next_contact_by                      AS direct_next_contact_by,
        c.next_contact_by                      AS consumer_next_contact_by
    FROM direct_obs d
    FULL OUTER JOIN consumer_obs c USING (event_id)
    WHERE (d.event_id IS NULL
       OR c.event_id IS NULL
       OR d.branch                IS DISTINCT FROM c.branch
       OR d.next_last_contacted   IS DISTINCT FROM c.next_last_contacted
       OR d.next_last_outreach_at IS DISTINCT FROM c.next_last_outreach_at
       OR d.next_last_response_at IS DISTINCT FROM c.next_last_response_at
       OR d.next_contact_by       IS DISTINCT FROM c.next_contact_by)
      AND GREATEST(d.observed_at, c.observed_at)
          < $2::timestamptz - INTERVAL '5 seconds'
)
SELECT
    j.event_id,
    j.contact_id,
    j.direct_branch,
    j.consumer_branch,
    j.direct_next_last_contacted,
    j.consumer_next_last_contacted,
    j.direct_next_last_outreach_at,
    j.consumer_next_last_outreach_at,
    j.direct_next_last_response_at,
    j.consumer_next_last_response_at,
    j.direct_next_contact_by,
    j.consumer_next_contact_by
FROM joined j
LEFT JOIN contact ct ON ct.id = j.contact_id
WHERE ct.deleted_at IS NULL
`

type FindCadenceShadowDivergencesParams struct {
	ObservedAtFrom pgtype.Timestamptz `json:"observed_at_from"`
	ObservedAtTo   pgtype.Timestamptz `json:"observed_at_to"`
}

type FindCadenceShadowDivergencesRow struct {
	EventID                    pgtype.UUID        `json:"event_id"`
	ContactID                  pgtype.UUID        `json:"contact_id"`
	DirectBranch               pgtype.Text        `json:"direct_branch"`
	ConsumerBranch             pgtype.Text        `json:"consumer_branch"`
	DirectNextLastContacted    pgtype.Timestamptz `json:"direct_next_last_contacted"`
	ConsumerNextLastContacted  pgtype.Timestamptz `json:"consumer_next_last_contacted"`
	DirectNextLastOutreachAt   pgtype.Timestamptz `json:"direct_next_last_outreach_at"`
	ConsumerNextLastOutreachAt pgtype.Timestamptz `json:"consumer_next_last_outreach_at"`
	DirectNextLastResponseAt   pgtype.Timestamptz `json:"direct_next_last_response_at"`
	ConsumerNextLastResponseAt pgtype.Timestamptz `json:"consumer_next_last_response_at"`
	DirectNextContactBy        pgtype.Date        `json:"direct_next_contact_by"`
	ConsumerNextContactBy      pgtype.Date        `json:"consumer_next_contact_by"`
}

// Post-bake divergence query. FULL OUTER JOIN of direct vs consumer rows
// on event_id — per plan Decision 1 each (event_id, writer) pair is unique,
// so the join resolves at most one direct + one consumer row per event.
// A non-empty result indicates real drift: direct missing, consumer
// missing, or next_* values disagreeing.
//
// Race-class filters baked in (plan Decision 4 taxonomy):
//
//  1. Grace window (`GREATEST(direct.observed_at, consumer.observed_at)
//     < @observed_at_to - 5s`) — applied on the JOINED pair, NOT on each
//     side independently. The direct-path observer fires from an async
//     post-commit closure that may land after the consumer. Filtering
//     each CTE independently causes a false consumer-only divergence
//     when consumer lands past the grace edge (e.g. T-6s) and direct
//     lands inside the grace edge (e.g. T-4s): the pre-filter removes
//     direct, consumer survives, and the FULL OUTER JOIN flags the
//     surviving consumer row as "direct missing". Moving the filter to
//     the joined CTE keeps both sides visible and only excludes the
//     pair when the later of the two is still within grace.
//  2. Exclude events where the paired contact is soft-deleted
//     (contact.deleted_at IS NOT NULL). The direct-path closure skips
//     snapshot writes when the contact is gone (plan Decision 4
//     contact_soft_deleted_midstream race class); the consumer may
//     still have written because its check runs at event-time, not
//     query-time. These rows are expected-one-sided.
//
// @observed_at_to is the "hard" right edge of the query window; the
// 5-second grace is subtracted on the joined pair's latest observed_at
// so the direct-path post-commit closure gets ample time to land before
// we treat "direct missing" (or "consumer missing") as real drift.
func (q *Queries) FindCadenceShadowDivergences(ctx context.Context, arg FindCadenceShadowDivergencesParams) ([]*FindCadenceShadowDivergencesRow, error) {
	rows, err := q.db.Query(ctx, FindCadenceShadowDivergences, arg.ObservedAtFrom, arg.ObservedAtTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FindCadenceShadowDivergencesRow{}
	for rows.Next() {
		var i FindCadenceShadowDivergencesRow
		if err := rows.Scan(
			&i.EventID,
			&i.ContactID,
			&i.DirectBranch,
			&i.ConsumerBranch,
			&i.DirectNextLastContacted,
			&i.ConsumerNextLastContacted,
			&i.DirectNextLastOutreachAt,
			&i.ConsumerNextLastOutreachAt,
			&i.DirectNextLastResponseAt,
			&i.ConsumerNextLastResponseAt,
			&i.DirectNextContactBy,
			&i.ConsumerNextContactBy,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const FindCadenceShadowObservationByEventAndWriter = `-- name: FindCadenceShadowObservationByEventAndWriter :one
SELECT id, event_id, writer, contact_id, source, direction, branch, occurred_at, prev_last_contacted, prev_last_outreach_at, prev_last_response_at, prev_contact_by, next_last_contacted, next_last_outreach_at, next_last_response_at, next_contact_by, apply_last_contacted, apply_last_outreach_at, apply_last_response_at, apply_contact_by, observed_at FROM event_shadow_cadence_observation
WHERE event_id = $1 AND writer = $2
LIMIT 1
`

type FindCadenceShadowObservationByEventAndWriterParams struct {
	EventID pgtype.UUID `json:"event_id"`
	Writer  string      `json:"writer"`
}

// Inline divergence logger uses this: given a consumer row just inserted,
// look up the paired 'direct' row to compare next_* values. Returns
// sql.ErrNoRows when the direct path hasn't observed yet (expected when
// the consumer fires before the direct-path post-commit closure lands).
func (q *Queries) FindCadenceShadowObservationByEventAndWriter(ctx context.Context, arg FindCadenceShadowObservationByEventAndWriterParams) (*EventShadowCadenceObservation, error) {
	row := q.db.QueryRow(ctx, FindCadenceShadowObservationByEventAndWriter, arg.EventID, arg.Writer)
	var i EventShadowCadenceObservation
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Writer,
		&i.ContactID,
		&i.Source,
		&i.Direction,
		&i.Branch,
		&i.OccurredAt,
		&i.PrevLastContacted,
		&i.PrevLastOutreachAt,
		&i.PrevLastResponseAt,
		&i.PrevContactBy,
		&i.NextLastContacted,
		&i.NextLastOutreachAt,
		&i.NextLastResponseAt,
		&i.NextContactBy,
		&i.ApplyLastContacted,
		&i.ApplyLastOutreachAt,
		&i.ApplyLastResponseAt,
		&i.ApplyContactBy,
		&i.ObservedAt,
	)
	return &i, err
}

const InsertCadenceShadowObservation = `-- name: InsertCadenceShadowObservation :one

INSERT INTO event_shadow_cadence_observation (
    event_id, writer, contact_id, source, direction, branch, occurred_at,
    prev_last_contacted, prev_last_outreach_at, prev_last_response_at, prev_contact_by,
    next_last_contacted, next_last_outreach_at, next_last_response_at, next_contact_by,
    apply_last_contacted, apply_last_outreach_at, apply_last_response_at, apply_contact_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8::timestamptz,
    $9::timestamptz,
    $10::timestamptz,
    $11::date,
    $12::timestamptz,
    $13::timestamptz,
    $14::timestamptz,
    $15::date,
    $16,
    $17,
    $18,
    $19
)
ON CONFLICT (event_id, writer) DO NOTHING
RETURNING id, event_id, writer, contact_id, source, direction, branch, occurred_at, prev_last_contacted, prev_last_outreach_at, prev_last_response_at, prev_contact_by, next_last_contacted, next_last_outreach_at, next_last_response_at, next_contact_by, apply_last_contacted, apply_last_outreach_at, apply_last_response_at, apply_contact_by, observed_at
`

type InsertCadenceShadowObservationParams struct {
	EventID             pgtype.UUID        `json:"event_id"`
	Writer              string             `json:"writer"`
	ContactID           pgtype.UUID        `json:"contact_id"`
	Source              string             `json:"source"`
	Direction           string             `json:"direction"`
	Branch              string             `json:"branch"`
	OccurredAt          pgtype.Timestamptz `json:"occurred_at"`
	PrevLastContacted   pgtype.Timestamptz `json:"prev_last_contacted"`
	PrevLastOutreachAt  pgtype.Timestamptz `json:"prev_last_outreach_at"`
	PrevLastResponseAt  pgtype.Timestamptz `json:"prev_last_response_at"`
	PrevContactBy       pgtype.Date        `json:"prev_contact_by"`
	NextLastContacted   pgtype.Timestamptz `json:"next_last_contacted"`
	NextLastOutreachAt  pgtype.Timestamptz `json:"next_last_outreach_at"`
	NextLastResponseAt  pgtype.Timestamptz `json:"next_last_response_at"`
	NextContactBy       pgtype.Date        `json:"next_contact_by"`
	ApplyLastContacted  bool               `json:"apply_last_contacted"`
	ApplyLastOutreachAt bool               `json:"apply_last_outreach_at"`
	ApplyLastResponseAt bool               `json:"apply_last_response_at"`
	ApplyContactBy      bool               `json:"apply_contact_by"`
}

// Event shadow cadence-observation queries (spec §3.4.2, PR 7). Sibling
// table to event_shadow_observation (migration 038); captures cadence-
// column pre/post image per event so the post-bake divergence query can
// FULL OUTER JOIN on event_id. See
// .ai/log/plan/event-bus-foundation-pr7-cadence-updater-shadow.md.
// Inserts an observation row. The UNIQUE (event_id, writer) constraint
// (migration 039) gives at-most-one-row-per-writer semantics under river
// retries. ON CONFLICT DO NOTHING returns no rows on duplicate; callers
// treat "no rows" as idempotent success rather than an error.
func (q *Queries) InsertCadenceShadowObservation(ctx context.Context, arg InsertCadenceShadowObservationParams) (*EventShadowCadenceObservation, error) {
	row := q.db.QueryRow(ctx, InsertCadenceShadowObservation,
		arg.EventID,
		arg.Writer,
		arg.ContactID,
		arg.Source,
		arg.Direction,
		arg.Branch,
		arg.OccurredAt,
		arg.PrevLastContacted,
		arg.PrevLastOutreachAt,
		arg.PrevLastResponseAt,
		arg.PrevContactBy,
		arg.NextLastContacted,
		arg.NextLastOutreachAt,
		arg.NextLastResponseAt,
		arg.NextContactBy,
		arg.ApplyLastContacted,
		arg.ApplyLastOutreachAt,
		arg.ApplyLastResponseAt,
		arg.ApplyContactBy,
	)
	var i EventShadowCadenceObservation
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Writer,
		&i.ContactID,
		&i.Source,
		&i.Direction,
		&i.Branch,
		&i.OccurredAt,
		&i.PrevLastContacted,
		&i.PrevLastOutreachAt,
		&i.PrevLastResponseAt,
		&i.PrevContactBy,
		&i.NextLastContacted,
		&i.NextLastOutreachAt,
		&i.NextLastResponseAt,
		&i.NextContactBy,
		&i.ApplyLastContacted,
		&i.ApplyLastOutreachAt,
		&i.ApplyLastResponseAt,
		&i.ApplyContactBy,
		&i.ObservedAt,
	)
	return &i, err
}
