// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_consumer_claim.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const ExistsEventConsumerClaim = `-- name: ExistsEventConsumerClaim :one
SELECT EXISTS (
    SELECT 1 FROM event_consumer_claim
    WHERE event_id = $1 AND consumer = $2
) AS claimed
`

type ExistsEventConsumerClaimParams struct {
	EventID  uuid.UUID `json:"event_id"`
	Consumer string    `json:"consumer"`
}

// Non-mutating lookup. Returns true when a claim row exists for the
// given (event_id, consumer). Useful for assertions in tests and for
// read-only operator diagnostics; the production dedupe path uses
// InsertEventConsumerClaim's rows-inserted signal instead of polling.
func (q *Queries) ExistsEventConsumerClaim(ctx context.Context, arg ExistsEventConsumerClaimParams) (bool, error) {
	row := q.db.QueryRow(ctx, ExistsEventConsumerClaim, arg.EventID, arg.Consumer)
	var claimed bool
	err := row.Scan(&claimed)
	return claimed, err
}

const InsertEventConsumerClaim = `-- name: InsertEventConsumerClaim :execrows

INSERT INTO event_consumer_claim (event_id, consumer)
VALUES ($1, $2)
ON CONFLICT (event_id, consumer) DO NOTHING
`

type InsertEventConsumerClaimParams struct {
	EventID  uuid.UUID `json:"event_id"`
	Consumer string    `json:"consumer"`
}

// Event consumer claim queries (migration 040; spec §3.4.2).
// The (event_id, consumer) primary key enforces at-most-once
// processing across the inline + queued delivery paths for the
// CadenceUpdater consumer.
// Attempts to claim (event_id, consumer). Returns the number of rows
// inserted: 1 if this caller claimed the event, 0 if another caller
// already holds the claim. Callers treat 0 as "someone else wrote this
// event; return nil without mutating state".
func (q *Queries) InsertEventConsumerClaim(ctx context.Context, arg InsertEventConsumerClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, InsertEventConsumerClaim, arg.EventID, arg.Consumer)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
