// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_shadow_observation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountShadowObservationsByWriter = `-- name: CountShadowObservationsByWriter :one
SELECT COUNT(*) FROM event_shadow_observation
WHERE writer = $1
`

// Used by integration tests to assert exact row counts per writer. No
// deleted_at filter — append-only table.
func (q *Queries) CountShadowObservationsByWriter(ctx context.Context, writer string) (int64, error) {
	row := q.db.QueryRow(ctx, CountShadowObservationsByWriter, writer)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const FindMatchingDirectWriteByManual = `-- name: FindMatchingDirectWriteByManual :one
SELECT id, event_id, writer, kind, source, source_ref, contact_id, direction, occurred_at, interaction_id, replay, observed_at FROM event_shadow_observation
WHERE writer = 'direct'
  AND kind = 'direct_record'
  AND source = $1
  AND contact_id = $2
  AND source_ref IS NULL
  AND date_trunc('second', occurred_at) = date_trunc('second', $3::timestamptz)
ORDER BY observed_at DESC
LIMIT 1
`

type FindMatchingDirectWriteByManualParams struct {
	Source     string             `json:"source"`
	ContactID  pgtype.UUID        `json:"contact_id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

// Manual (no source_ref) variant: matches on (source, contact_id) and the
// occurred_at truncated to the second. The 30-minute dedup window of the
// direct path guarantees a single row per contact per minute-level ts.
func (q *Queries) FindMatchingDirectWriteByManual(ctx context.Context, arg FindMatchingDirectWriteByManualParams) (*EventShadowObservation, error) {
	row := q.db.QueryRow(ctx, FindMatchingDirectWriteByManual, arg.Source, arg.ContactID, arg.OccurredAt)
	var i EventShadowObservation
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Writer,
		&i.Kind,
		&i.Source,
		&i.SourceRef,
		&i.ContactID,
		&i.Direction,
		&i.OccurredAt,
		&i.InteractionID,
		&i.Replay,
		&i.ObservedAt,
	)
	return &i, err
}

const FindMatchingDirectWriteBySourceRef = `-- name: FindMatchingDirectWriteBySourceRef :one
SELECT id, event_id, writer, kind, source, source_ref, contact_id, direction, occurred_at, interaction_id, replay, observed_at FROM event_shadow_observation
WHERE writer = 'direct'
  AND kind = 'direct_record'
  AND source = $1
  AND source_ref = $2
  AND contact_id = $3
ORDER BY observed_at DESC
LIMIT 1
`

type FindMatchingDirectWriteBySourceRefParams struct {
	Source    string      `json:"source"`
	SourceRef pgtype.Text `json:"source_ref"`
	ContactID pgtype.UUID `json:"contact_id"`
}

// Fetches the most recent direct-path row matching the given
// (source, source_ref, contact_id). Used by the inline divergence logger
// (Decision 14 Part A) when the consumer commits a writer='consumer' row
// and wants to compare against the peer direct-path row. Returns the most
// recent fresh-write (kind = 'direct_record') row when multiple exist.
func (q *Queries) FindMatchingDirectWriteBySourceRef(ctx context.Context, arg FindMatchingDirectWriteBySourceRefParams) (*EventShadowObservation, error) {
	row := q.db.QueryRow(ctx, FindMatchingDirectWriteBySourceRef, arg.Source, arg.SourceRef, arg.ContactID)
	var i EventShadowObservation
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Writer,
		&i.Kind,
		&i.Source,
		&i.SourceRef,
		&i.ContactID,
		&i.Direction,
		&i.OccurredAt,
		&i.InteractionID,
		&i.Replay,
		&i.ObservedAt,
	)
	return &i, err
}

const FindShadowDivergencesManual = `-- name: FindShadowDivergencesManual :many
WITH direct_writes AS (
    SELECT source, contact_id, direction,
           date_trunc('second', occurred_at)::timestamptz AS ts
    FROM event_shadow_observation
    WHERE writer = 'direct'
      AND replay = false
      AND kind = 'direct_record'
      AND source_ref IS NULL
      AND observed_at >= $1::timestamptz
      AND observed_at < $2::timestamptz
),
consumer_writes AS (
    SELECT source, contact_id, direction,
           date_trunc('second', occurred_at)::timestamptz AS ts
    FROM event_shadow_observation
    WHERE writer = 'consumer'
      AND source_ref IS NULL
      AND observed_at >= $1::timestamptz
      AND observed_at < $2::timestamptz
)
SELECT
    COALESCE(d.source, c.source)         AS source,
    COALESCE(d.contact_id, c.contact_id) AS contact_id,
    d.direction                          AS direct_direction,
    c.direction                          AS consumer_direction,
    d.ts                                 AS direct_ts,
    c.ts                                 AS consumer_ts
FROM direct_writes d
FULL OUTER JOIN consumer_writes c
    USING (source, contact_id, ts)
WHERE d.direction IS DISTINCT FROM c.direction
`

type FindShadowDivergencesManualParams struct {
	ObservedAtFrom pgtype.Timestamptz `json:"observed_at_from"`
	ObservedAtTo   pgtype.Timestamptz `json:"observed_at_to"`
}

type FindShadowDivergencesManualRow struct {
	Source            string             `json:"source"`
	ContactID         pgtype.UUID        `json:"contact_id"`
	DirectDirection   pgtype.Text        `json:"direct_direction"`
	ConsumerDirection pgtype.Text        `json:"consumer_direction"`
	DirectTs          pgtype.Timestamptz `json:"direct_ts"`
	ConsumerTs        pgtype.Timestamptz `json:"consumer_ts"`
}

// Post-bake divergence query for manual (no-source_ref) kind. Joins on
// (source, contact_id, ts-second). Same semantics as the ref-bearing
// variant: consumer side includes replay=true (consumer "observed" the
// direct-path row via FindInWindow dedup).
func (q *Queries) FindShadowDivergencesManual(ctx context.Context, arg FindShadowDivergencesManualParams) ([]*FindShadowDivergencesManualRow, error) {
	rows, err := q.db.Query(ctx, FindShadowDivergencesManual, arg.ObservedAtFrom, arg.ObservedAtTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FindShadowDivergencesManualRow{}
	for rows.Next() {
		var i FindShadowDivergencesManualRow
		if err := rows.Scan(
			&i.Source,
			&i.ContactID,
			&i.DirectDirection,
			&i.ConsumerDirection,
			&i.DirectTs,
			&i.ConsumerTs,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const FindShadowDivergencesRefBearing = `-- name: FindShadowDivergencesRefBearing :many
WITH direct_writes AS (
    SELECT source, source_ref, contact_id, direction,
           date_trunc('second', occurred_at)::timestamptz AS ts
    FROM event_shadow_observation
    WHERE writer = 'direct'
      AND replay = false
      AND kind = 'direct_record'
      AND source_ref IS NOT NULL
      AND observed_at >= $1::timestamptz
      AND observed_at < $2::timestamptz
),
consumer_writes AS (
    SELECT source, source_ref, contact_id, direction,
           date_trunc('second', occurred_at)::timestamptz AS ts
    FROM event_shadow_observation
    WHERE writer = 'consumer'
      AND source_ref IS NOT NULL
      AND observed_at >= $1::timestamptz
      AND observed_at < $2::timestamptz
)
SELECT
    COALESCE(d.source, c.source)         AS source,
    COALESCE(d.source_ref, c.source_ref) AS source_ref,
    COALESCE(d.contact_id, c.contact_id) AS contact_id,
    d.direction                          AS direct_direction,
    c.direction                          AS consumer_direction,
    d.ts                                 AS direct_ts,
    c.ts                                 AS consumer_ts
FROM direct_writes d
FULL OUTER JOIN consumer_writes c
    USING (source, source_ref, contact_id)
WHERE d.direction IS DISTINCT FROM c.direction
   OR d.ts IS DISTINCT FROM c.ts
`

type FindShadowDivergencesRefBearingParams struct {
	ObservedAtFrom pgtype.Timestamptz `json:"observed_at_from"`
	ObservedAtTo   pgtype.Timestamptz `json:"observed_at_to"`
}

type FindShadowDivergencesRefBearingRow struct {
	Source            string             `json:"source"`
	SourceRef         pgtype.Text        `json:"source_ref"`
	ContactID         pgtype.UUID        `json:"contact_id"`
	DirectDirection   pgtype.Text        `json:"direct_direction"`
	ConsumerDirection pgtype.Text        `json:"consumer_direction"`
	DirectTs          pgtype.Timestamptz `json:"direct_ts"`
	ConsumerTs        pgtype.Timestamptz `json:"consumer_ts"`
}

// Post-bake divergence query for ref-bearing kinds. FULL OUTER JOIN of
// direct fresh-writes vs ALL consumer observations (including replay=true,
// which is the expected shadow-mode state: direct wrote first, consumer
// saw the existing row and early-returned). A non-empty result means one
// or more interactions disagreed between the two paths (direction
// mismatch, occurred_at mismatch, or one-side-only). Parameters bound the
// observation time range so the bake-window evidence is reproducible.
//
// Direct side: only replay=false (fresh writes). Direct-path dedupe hits
// (replay=true) are excluded because they're re-observations of rows the
// consumer already accounted for at their fresh-write time.
//
// Consumer side: BOTH replay=true and replay=false are included — the
// consumer "observed" the event either way; replay=true just means it
// found the direct-path row in the dedupe check.
func (q *Queries) FindShadowDivergencesRefBearing(ctx context.Context, arg FindShadowDivergencesRefBearingParams) ([]*FindShadowDivergencesRefBearingRow, error) {
	rows, err := q.db.Query(ctx, FindShadowDivergencesRefBearing, arg.ObservedAtFrom, arg.ObservedAtTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*FindShadowDivergencesRefBearingRow{}
	for rows.Next() {
		var i FindShadowDivergencesRefBearingRow
		if err := rows.Scan(
			&i.Source,
			&i.SourceRef,
			&i.ContactID,
			&i.DirectDirection,
			&i.ConsumerDirection,
			&i.DirectTs,
			&i.ConsumerTs,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const InsertEventShadowObservation = `-- name: InsertEventShadowObservation :one

INSERT INTO event_shadow_observation (
    event_id, writer, kind, source, source_ref, contact_id,
    direction, occurred_at, interaction_id, replay
) VALUES (
    $1::uuid,
    $2,
    $3,
    $4,
    $5::text,
    $6,
    $7,
    $8,
    $9::uuid,
    $10
)
RETURNING id, event_id, writer, kind, source, source_ref, contact_id, direction, occurred_at, interaction_id, replay, observed_at
`

type InsertEventShadowObservationParams struct {
	EventID       pgtype.UUID        `json:"event_id"`
	Writer        string             `json:"writer"`
	Kind          string             `json:"kind"`
	Source        string             `json:"source"`
	SourceRef     pgtype.Text        `json:"source_ref"`
	ContactID     pgtype.UUID        `json:"contact_id"`
	Direction     string             `json:"direction"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	InteractionID pgtype.UUID        `json:"interaction_id"`
	Replay        bool               `json:"replay"`
}

// Event shadow observation queries (spec §3.8, PR 5). Append-only log of
// what each write path (direct vs consumer) produced during shadow-mode
// bake. The post-bake divergence query FULL OUTER JOINs direct+consumer
// rows on (source, source_ref) to surface drift.
// Inserts an observation row and returns it. No ON CONFLICT — each call
// produces a new row. The event_id FK may be NULL for direct-path rows
// that fired without a paired event envelope (e.g., ExtendInteraction,
// PromoteInteractionToMutual).
func (q *Queries) InsertEventShadowObservation(ctx context.Context, arg InsertEventShadowObservationParams) (*EventShadowObservation, error) {
	row := q.db.QueryRow(ctx, InsertEventShadowObservation,
		arg.EventID,
		arg.Writer,
		arg.Kind,
		arg.Source,
		arg.SourceRef,
		arg.ContactID,
		arg.Direction,
		arg.OccurredAt,
		arg.InteractionID,
		arg.Replay,
	)
	var i EventShadowObservation
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Writer,
		&i.Kind,
		&i.Source,
		&i.SourceRef,
		&i.ContactID,
		&i.Direction,
		&i.OccurredAt,
		&i.InteractionID,
		&i.Replay,
		&i.ObservedAt,
	)
	return &i, err
}
