// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: external_contact.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountAllUnmatchedExternalContacts = `-- name: CountAllUnmatchedExternalContacts :one
SELECT COUNT(*) FROM external_contact
WHERE match_status = 'unmatched'
  AND source != 'anarlog_title'
  AND duplicate_of_id IS NULL
  AND deleted_at IS NULL
`

func (q *Queries) CountAllUnmatchedExternalContacts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountAllUnmatchedExternalContacts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountUnmatchedExternalContacts = `-- name: CountUnmatchedExternalContacts :one
SELECT COUNT(*) FROM external_contact
WHERE source = $1
  AND source != 'anarlog_title'
  AND match_status = 'unmatched'
  AND duplicate_of_id IS NULL
  AND deleted_at IS NULL
`

func (q *Queries) CountUnmatchedExternalContacts(ctx context.Context, source string) (int64, error) {
	row := q.db.QueryRow(ctx, CountUnmatchedExternalContacts, source)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateEnrichment = `-- name: CreateEnrichment :one
INSERT INTO contact_enrichment (
    contact_id, source, account_id, field, external_contact_id, original_value
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (contact_id, source, field, COALESCE(account_id, '')) DO UPDATE SET
    external_contact_id = EXCLUDED.external_contact_id,
    original_value = EXCLUDED.original_value,
    enriched_at = NOW()
RETURNING id, contact_id, source, account_id, field, external_contact_id, original_value, enriched_at
`

type CreateEnrichmentParams struct {
	ContactID         pgtype.UUID `json:"contact_id"`
	Source            string      `json:"source"`
	AccountID         pgtype.Text `json:"account_id"`
	Field             string      `json:"field"`
	ExternalContactID pgtype.UUID `json:"external_contact_id"`
	OriginalValue     pgtype.Text `json:"original_value"`
}

func (q *Queries) CreateEnrichment(ctx context.Context, arg CreateEnrichmentParams) (*ContactEnrichment, error) {
	row := q.db.QueryRow(ctx, CreateEnrichment,
		arg.ContactID,
		arg.Source,
		arg.AccountID,
		arg.Field,
		arg.ExternalContactID,
		arg.OriginalValue,
	)
	var i ContactEnrichment
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Source,
		&i.AccountID,
		&i.Field,
		&i.ExternalContactID,
		&i.OriginalValue,
		&i.EnrichedAt,
	)
	return &i, err
}

const DeleteEnrichment = `-- name: DeleteEnrichment :exec
DELETE FROM contact_enrichment WHERE id = $1
`

func (q *Queries) DeleteEnrichment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteEnrichment, id)
	return err
}

const DeleteEnrichmentsForContact = `-- name: DeleteEnrichmentsForContact :exec
DELETE FROM contact_enrichment WHERE contact_id = $1
`

func (q *Queries) DeleteEnrichmentsForContact(ctx context.Context, contactID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteEnrichmentsForContact, contactID)
	return err
}

const DeleteExternalContact = `-- name: DeleteExternalContact :exec
DELETE FROM external_contact WHERE id = $1
`

func (q *Queries) DeleteExternalContact(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteExternalContact, id)
	return err
}

const DeleteExternalContactsBySourceAccount = `-- name: DeleteExternalContactsBySourceAccount :exec
DELETE FROM external_contact
WHERE source = $1 AND COALESCE(account_id, '') = COALESCE($2, '')
`

type DeleteExternalContactsBySourceAccountParams struct {
	Source    string      `json:"source"`
	AccountID pgtype.Text `json:"account_id"`
}

func (q *Queries) DeleteExternalContactsBySourceAccount(ctx context.Context, arg DeleteExternalContactsBySourceAccountParams) error {
	_, err := q.db.Exec(ctx, DeleteExternalContactsBySourceAccount, arg.Source, arg.AccountID)
	return err
}

const FindExternalContactsByEmail = `-- name: FindExternalContactsByEmail :many
SELECT id, source, source_id, account_id, display_name, first_name, last_name, emails, phones, addresses, organization, job_title, birthday, photo_url, crm_contact_id, match_status, duplicate_of_id, etag, metadata, synced_at, created_at, updated_at, deleted_at, host_id, last_content_hash FROM external_contact
WHERE emails @> $1::jsonb
  AND duplicate_of_id IS NULL
  AND deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) FindExternalContactsByEmail(ctx context.Context, dollar_1 []byte) ([]*ExternalContact, error) {
	rows, err := q.db.Query(ctx, FindExternalContactsByEmail, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ExternalContact{}
	for rows.Next() {
		var i ExternalContact
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.SourceID,
			&i.AccountID,
			&i.DisplayName,
			&i.FirstName,
			&i.LastName,
			&i.Emails,
			&i.Phones,
			&i.Addresses,
			&i.Organization,
			&i.JobTitle,
			&i.Birthday,
			&i.PhotoUrl,
			&i.CrmContactID,
			&i.MatchStatus,
			&i.DuplicateOfID,
			&i.Etag,
			&i.Metadata,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.HostID,
			&i.LastContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const FindExternalContactsByNormalizedEmail = `-- name: FindExternalContactsByNormalizedEmail :many
SELECT id, source, source_id, account_id, display_name, first_name, last_name, emails, phones, addresses, organization, job_title, birthday, photo_url, crm_contact_id, match_status, duplicate_of_id, etag, metadata, synced_at, created_at, updated_at, deleted_at, host_id, last_content_hash FROM external_contact
WHERE jsonb_array_lower_values(emails, 'value') && ARRAY[LOWER($1)]
  AND duplicate_of_id IS NULL
  AND deleted_at IS NULL
ORDER BY created_at
`

// Finds external contacts whose JSONB emails contain the given normalized
// email value. Backed by idx_external_contact_emails_value_lower_gin via
// the jsonb_array_lower_values helper. Tombstoned rows are excluded so
// duplicate detection ignores soft-deleted candidates.
func (q *Queries) FindExternalContactsByNormalizedEmail(ctx context.Context, lower string) ([]*ExternalContact, error) {
	rows, err := q.db.Query(ctx, FindExternalContactsByNormalizedEmail, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ExternalContact{}
	for rows.Next() {
		var i ExternalContact
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.SourceID,
			&i.AccountID,
			&i.DisplayName,
			&i.FirstName,
			&i.LastName,
			&i.Emails,
			&i.Phones,
			&i.Addresses,
			&i.Organization,
			&i.JobTitle,
			&i.Birthday,
			&i.PhotoUrl,
			&i.CrmContactID,
			&i.MatchStatus,
			&i.DuplicateOfID,
			&i.Etag,
			&i.Metadata,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.HostID,
			&i.LastContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const FindExternalContactsBySourceAndSourceID = `-- name: FindExternalContactsBySourceAndSourceID :many
SELECT id, source, source_id, account_id, display_name, first_name, last_name, emails, phones, addresses, organization, job_title, birthday, photo_url, crm_contact_id, match_status, duplicate_of_id, etag, metadata, synced_at, created_at, updated_at, deleted_at, host_id, last_content_hash FROM external_contact
WHERE source = $1
  AND source_id = $2
  AND match_status = 'unmatched'
  AND deleted_at IS NULL
`

type FindExternalContactsBySourceAndSourceIDParams struct {
	Source   string `json:"source"`
	SourceID string `json:"source_id"`
}

// Finds all unmatched external_contact rows for a (source, source_id) pair
// regardless of account_id. Used by the calendar rematch handler to mark
// gcal_attendee import candidates as matched after a CRM contact links them.
// Tombstoned candidates must not be rematched.
func (q *Queries) FindExternalContactsBySourceAndSourceID(ctx context.Context, arg FindExternalContactsBySourceAndSourceIDParams) ([]*ExternalContact, error) {
	rows, err := q.db.Query(ctx, FindExternalContactsBySourceAndSourceID, arg.Source, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ExternalContact{}
	for rows.Next() {
		var i ExternalContact
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.SourceID,
			&i.AccountID,
			&i.DisplayName,
			&i.FirstName,
			&i.LastName,
			&i.Emails,
			&i.Phones,
			&i.Addresses,
			&i.Organization,
			&i.JobTitle,
			&i.Birthday,
			&i.PhotoUrl,
			&i.CrmContactID,
			&i.MatchStatus,
			&i.DuplicateOfID,
			&i.Etag,
			&i.Metadata,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.HostID,
			&i.LastContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetEnrichmentByField = `-- name: GetEnrichmentByField :one
SELECT id, contact_id, source, account_id, field, external_contact_id, original_value, enriched_at FROM contact_enrichment
WHERE contact_id = $1 AND field = $2
LIMIT 1
`

type GetEnrichmentByFieldParams struct {
	ContactID pgtype.UUID `json:"contact_id"`
	Field     string      `json:"field"`
}

func (q *Queries) GetEnrichmentByField(ctx context.Context, arg GetEnrichmentByFieldParams) (*ContactEnrichment, error) {
	row := q.db.QueryRow(ctx, GetEnrichmentByField, arg.ContactID, arg.Field)
	var i ContactEnrichment
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Source,
		&i.AccountID,
		&i.Field,
		&i.ExternalContactID,
		&i.OriginalValue,
		&i.EnrichedAt,
	)
	return &i, err
}

const GetEnrichmentsForContact = `-- name: GetEnrichmentsForContact :many

SELECT id, contact_id, source, account_id, field, external_contact_id, original_value, enriched_at FROM contact_enrichment
WHERE contact_id = $1
ORDER BY enriched_at DESC
`

// Contact Enrichment queries
func (q *Queries) GetEnrichmentsForContact(ctx context.Context, contactID pgtype.UUID) ([]*ContactEnrichment, error) {
	rows, err := q.db.Query(ctx, GetEnrichmentsForContact, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ContactEnrichment{}
	for rows.Next() {
		var i ContactEnrichment
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Source,
			&i.AccountID,
			&i.Field,
			&i.ExternalContactID,
			&i.OriginalValue,
			&i.EnrichedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetExternalContact = `-- name: GetExternalContact :one

SELECT id, source, source_id, account_id, display_name, first_name, last_name, emails, phones, addresses, organization, job_title, birthday, photo_url, crm_contact_id, match_status, duplicate_of_id, etag, metadata, synced_at, created_at, updated_at, deleted_at, host_id, last_content_hash FROM external_contact
WHERE id = $1
  AND deleted_at IS NULL
`

// External Contact queries
// Tombstoned rows are not retrievable by ID through normal flows.
func (q *Queries) GetExternalContact(ctx context.Context, id pgtype.UUID) (*ExternalContact, error) {
	row := q.db.QueryRow(ctx, GetExternalContact, id)
	var i ExternalContact
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourceID,
		&i.AccountID,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.Emails,
		&i.Phones,
		&i.Addresses,
		&i.Organization,
		&i.JobTitle,
		&i.Birthday,
		&i.PhotoUrl,
		&i.CrmContactID,
		&i.MatchStatus,
		&i.DuplicateOfID,
		&i.Etag,
		&i.Metadata,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HostID,
		&i.LastContentHash,
	)
	return &i, err
}

const GetExternalContactBySource = `-- name: GetExternalContactBySource :one
SELECT id, source, source_id, account_id, display_name, first_name, last_name, emails, phones, addresses, organization, job_title, birthday, photo_url, crm_contact_id, match_status, duplicate_of_id, etag, metadata, synced_at, created_at, updated_at, deleted_at, host_id, last_content_hash FROM external_contact
WHERE source = $1 AND source_id = $2 AND COALESCE(account_id, '') = COALESCE($3, '')
`

type GetExternalContactBySourceParams struct {
	Source    string      `json:"source"`
	SourceID  string      `json:"source_id"`
	AccountID pgtype.Text `json:"account_id"`
}

// Tombstone-aware: returns tombstoned rows too. The mac-daemon ingest path
// needs visibility into tombstoned rows so it can revive them on a fresh
// external_contact.upserted event. Existing telegram / gcontacts callers
// never tombstone, so the broader read does not affect them. Callers that
// want live-only rows must check `DeletedAt == nil` after the call.
func (q *Queries) GetExternalContactBySource(ctx context.Context, arg GetExternalContactBySourceParams) (*ExternalContact, error) {
	row := q.db.QueryRow(ctx, GetExternalContactBySource, arg.Source, arg.SourceID, arg.AccountID)
	var i ExternalContact
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourceID,
		&i.AccountID,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.Emails,
		&i.Phones,
		&i.Addresses,
		&i.Organization,
		&i.JobTitle,
		&i.Birthday,
		&i.PhotoUrl,
		&i.CrmContactID,
		&i.MatchStatus,
		&i.DuplicateOfID,
		&i.Etag,
		&i.Metadata,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HostID,
		&i.LastContentHash,
	)
	return &i, err
}

const HasEnrichmentForField = `-- name: HasEnrichmentForField :one
SELECT EXISTS(
    SELECT 1 FROM contact_enrichment
    WHERE contact_id = $1 AND field = $2
)
`

type HasEnrichmentForFieldParams struct {
	ContactID pgtype.UUID `json:"contact_id"`
	Field     string      `json:"field"`
}

func (q *Queries) HasEnrichmentForField(ctx context.Context, arg HasEnrichmentForFieldParams) (bool, error) {
	row := q.db.QueryRow(ctx, HasEnrichmentForField, arg.ContactID, arg.Field)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const IgnoreExternalContact = `-- name: IgnoreExternalContact :exec
UPDATE external_contact SET
    match_status = 'ignored',
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) IgnoreExternalContact(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, IgnoreExternalContact, id)
	return err
}

const ListAllUnmatchedExternalContacts = `-- name: ListAllUnmatchedExternalContacts :many
SELECT id, source, source_id, account_id, display_name, first_name, last_name, emails, phones, addresses, organization, job_title, birthday, photo_url, crm_contact_id, match_status, duplicate_of_id, etag, metadata, synced_at, created_at, updated_at, deleted_at, host_id, last_content_hash FROM external_contact
WHERE match_status = 'unmatched'
  AND source != 'anarlog_title'
  AND duplicate_of_id IS NULL
  AND deleted_at IS NULL
ORDER BY source, display_name
LIMIT $1 OFFSET $2
`

type ListAllUnmatchedExternalContactsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllUnmatchedExternalContacts(ctx context.Context, arg ListAllUnmatchedExternalContactsParams) ([]*ExternalContact, error) {
	rows, err := q.db.Query(ctx, ListAllUnmatchedExternalContacts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ExternalContact{}
	for rows.Next() {
		var i ExternalContact
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.SourceID,
			&i.AccountID,
			&i.DisplayName,
			&i.FirstName,
			&i.LastName,
			&i.Emails,
			&i.Phones,
			&i.Addresses,
			&i.Organization,
			&i.JobTitle,
			&i.Birthday,
			&i.PhotoUrl,
			&i.CrmContactID,
			&i.MatchStatus,
			&i.DuplicateOfID,
			&i.Etag,
			&i.Metadata,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.HostID,
			&i.LastContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListEnrichmentsBySource = `-- name: ListEnrichmentsBySource :many
SELECT id, contact_id, source, account_id, field, external_contact_id, original_value, enriched_at FROM contact_enrichment
WHERE source = $1
ORDER BY enriched_at DESC
LIMIT $2 OFFSET $3
`

type ListEnrichmentsBySourceParams struct {
	Source string `json:"source"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListEnrichmentsBySource(ctx context.Context, arg ListEnrichmentsBySourceParams) ([]*ContactEnrichment, error) {
	rows, err := q.db.Query(ctx, ListEnrichmentsBySource, arg.Source, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ContactEnrichment{}
	for rows.Next() {
		var i ContactEnrichment
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Source,
			&i.AccountID,
			&i.Field,
			&i.ExternalContactID,
			&i.OriginalValue,
			&i.EnrichedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListExternalContactsBySource = `-- name: ListExternalContactsBySource :many
SELECT id, source, source_id, account_id, display_name, first_name, last_name, emails, phones, addresses, organization, job_title, birthday, photo_url, crm_contact_id, match_status, duplicate_of_id, etag, metadata, synced_at, created_at, updated_at, deleted_at, host_id, last_content_hash FROM external_contact
WHERE source = $1
  AND ($2::text IS NULL OR account_id = $2)
  AND deleted_at IS NULL
ORDER BY display_name
LIMIT $3 OFFSET $4
`

type ListExternalContactsBySourceParams struct {
	Source  string `json:"source"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListExternalContactsBySource(ctx context.Context, arg ListExternalContactsBySourceParams) ([]*ExternalContact, error) {
	rows, err := q.db.Query(ctx, ListExternalContactsBySource,
		arg.Source,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ExternalContact{}
	for rows.Next() {
		var i ExternalContact
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.SourceID,
			&i.AccountID,
			&i.DisplayName,
			&i.FirstName,
			&i.LastName,
			&i.Emails,
			&i.Phones,
			&i.Addresses,
			&i.Organization,
			&i.JobTitle,
			&i.Birthday,
			&i.PhotoUrl,
			&i.CrmContactID,
			&i.MatchStatus,
			&i.DuplicateOfID,
			&i.Etag,
			&i.Metadata,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.HostID,
			&i.LastContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListExternalContactsForCRMContact = `-- name: ListExternalContactsForCRMContact :many
SELECT id, source, source_id, account_id, display_name, first_name, last_name, emails, phones, addresses, organization, job_title, birthday, photo_url, crm_contact_id, match_status, duplicate_of_id, etag, metadata, synced_at, created_at, updated_at, deleted_at, host_id, last_content_hash FROM external_contact
WHERE crm_contact_id = $1
  AND deleted_at IS NULL
ORDER BY source, account_id
`

func (q *Queries) ListExternalContactsForCRMContact(ctx context.Context, crmContactID pgtype.UUID) ([]*ExternalContact, error) {
	rows, err := q.db.Query(ctx, ListExternalContactsForCRMContact, crmContactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ExternalContact{}
	for rows.Next() {
		var i ExternalContact
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.SourceID,
			&i.AccountID,
			&i.DisplayName,
			&i.FirstName,
			&i.LastName,
			&i.Emails,
			&i.Phones,
			&i.Addresses,
			&i.Organization,
			&i.JobTitle,
			&i.Birthday,
			&i.PhotoUrl,
			&i.CrmContactID,
			&i.MatchStatus,
			&i.DuplicateOfID,
			&i.Etag,
			&i.Metadata,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.HostID,
			&i.LastContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListKnownExternalContactIDsByHostAndSource = `-- name: ListKnownExternalContactIDsByHostAndSource :many
SELECT source_id, last_content_hash
FROM external_contact
WHERE host_id = $1
  AND source = $2
  AND deleted_at IS NULL
ORDER BY source_id
`

type ListKnownExternalContactIDsByHostAndSourceParams struct {
	HostID pgtype.UUID `json:"host_id"`
	Source string      `json:"source"`
}

type ListKnownExternalContactIDsByHostAndSourceRow struct {
	SourceID        string      `json:"source_id"`
	LastContentHash pgtype.Text `json:"last_content_hash"`
}

// Returns (source_id, last_content_hash) for every live
// external_contact row owned by the given (host_id, source). Powers
// GET /api/v1/host/:id/sync/:source/known-ids. Tombstoned rows are
// excluded — the daemon's set-diff reconciliation requires that
// rows the Pi has soft-deleted are NOT reported as known (else the
// daemon never re-tombstones them).
//
// Lowercase-hex of last_content_hash is enforced upstream by the
// ingest layer's verifyExternalContactInvariants regex
// (^[a-f0-9]{64}$) plus the JCS hash-verification check. This query
// stores and returns the value verbatim. Legacy rows whose
// last_content_hash is NULL cause the daemon to fall back to the
// @deleted@unknown sentinel per the spec.
func (q *Queries) ListKnownExternalContactIDsByHostAndSource(ctx context.Context, arg ListKnownExternalContactIDsByHostAndSourceParams) ([]*ListKnownExternalContactIDsByHostAndSourceRow, error) {
	rows, err := q.db.Query(ctx, ListKnownExternalContactIDsByHostAndSource, arg.HostID, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListKnownExternalContactIDsByHostAndSourceRow{}
	for rows.Next() {
		var i ListKnownExternalContactIDsByHostAndSourceRow
		if err := rows.Scan(&i.SourceID, &i.LastContentHash); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUnmatchedExternalContacts = `-- name: ListUnmatchedExternalContacts :many
SELECT id, source, source_id, account_id, display_name, first_name, last_name, emails, phones, addresses, organization, job_title, birthday, photo_url, crm_contact_id, match_status, duplicate_of_id, etag, metadata, synced_at, created_at, updated_at, deleted_at, host_id, last_content_hash FROM external_contact
WHERE source = $1
  AND source != 'anarlog_title'
  AND match_status = 'unmatched'
  AND duplicate_of_id IS NULL
  AND deleted_at IS NULL
ORDER BY display_name
LIMIT $2 OFFSET $3
`

type ListUnmatchedExternalContactsParams struct {
	Source string `json:"source"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

// The `source != 'anarlog_title'` filter excludes weak token-aggregated
// discovery rows from the per-source Imports UI list. anarlog_title
// rows are surfaced through a dedicated grouped-by-token UI surface.
func (q *Queries) ListUnmatchedExternalContacts(ctx context.Context, arg ListUnmatchedExternalContactsParams) ([]*ExternalContact, error) {
	rows, err := q.db.Query(ctx, ListUnmatchedExternalContacts, arg.Source, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ExternalContact{}
	for rows.Next() {
		var i ExternalContact
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.SourceID,
			&i.AccountID,
			&i.DisplayName,
			&i.FirstName,
			&i.LastName,
			&i.Emails,
			&i.Phones,
			&i.Addresses,
			&i.Organization,
			&i.JobTitle,
			&i.Birthday,
			&i.PhotoUrl,
			&i.CrmContactID,
			&i.MatchStatus,
			&i.DuplicateOfID,
			&i.Etag,
			&i.Metadata,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.HostID,
			&i.LastContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ReviveExternalContact = `-- name: ReviveExternalContact :one
UPDATE external_contact SET
    deleted_at = NULL,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NOT NULL
RETURNING id, source, source_id, account_id, display_name, first_name, last_name, emails, phones, addresses, organization, job_title, birthday, photo_url, crm_contact_id, match_status, duplicate_of_id, etag, metadata, synced_at, created_at, updated_at, deleted_at, host_id, last_content_hash
`

// Clears deleted_at on a tombstoned row. Defensive WHERE deleted_at IS NOT
// NULL keeps the statement idempotent across concurrent revive races.
// Preserves crm_contact_id, match_status, and all content columns.
func (q *Queries) ReviveExternalContact(ctx context.Context, id pgtype.UUID) (*ExternalContact, error) {
	row := q.db.QueryRow(ctx, ReviveExternalContact, id)
	var i ExternalContact
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourceID,
		&i.AccountID,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.Emails,
		&i.Phones,
		&i.Addresses,
		&i.Organization,
		&i.JobTitle,
		&i.Birthday,
		&i.PhotoUrl,
		&i.CrmContactID,
		&i.MatchStatus,
		&i.DuplicateOfID,
		&i.Etag,
		&i.Metadata,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HostID,
		&i.LastContentHash,
	)
	return &i, err
}

const SoftDeleteExternalContact = `-- name: SoftDeleteExternalContact :exec
UPDATE external_contact SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

// Tombstones a live row. Defensive WHERE deleted_at IS NULL keeps the
// statement idempotent against a concurrent delete. crm_contact_id,
// match_status, and duplicate_of_id are preserved per the external_contact
// soft-delete contract.
func (q *Queries) SoftDeleteExternalContact(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, SoftDeleteExternalContact, id)
	return err
}

const UpdateExternalContactDuplicate = `-- name: UpdateExternalContactDuplicate :exec
UPDATE external_contact SET
    duplicate_of_id = $2,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

type UpdateExternalContactDuplicateParams struct {
	ID            pgtype.UUID `json:"id"`
	DuplicateOfID pgtype.UUID `json:"duplicate_of_id"`
}

func (q *Queries) UpdateExternalContactDuplicate(ctx context.Context, arg UpdateExternalContactDuplicateParams) error {
	_, err := q.db.Exec(ctx, UpdateExternalContactDuplicate, arg.ID, arg.DuplicateOfID)
	return err
}

const UpdateExternalContactMatch = `-- name: UpdateExternalContactMatch :one
UPDATE external_contact SET
    crm_contact_id = $2,
    match_status = $3,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, source, source_id, account_id, display_name, first_name, last_name, emails, phones, addresses, organization, job_title, birthday, photo_url, crm_contact_id, match_status, duplicate_of_id, etag, metadata, synced_at, created_at, updated_at, deleted_at, host_id, last_content_hash
`

type UpdateExternalContactMatchParams struct {
	ID           pgtype.UUID `json:"id"`
	CrmContactID pgtype.UUID `json:"crm_contact_id"`
	MatchStatus  pgtype.Text `json:"match_status"`
}

// Filter `deleted_at IS NULL` so a tombstoned row cannot have its
// match state mutated. A tombstoned row is invisible to every read
// path; writes should be invisible too.
func (q *Queries) UpdateExternalContactMatch(ctx context.Context, arg UpdateExternalContactMatchParams) (*ExternalContact, error) {
	row := q.db.QueryRow(ctx, UpdateExternalContactMatch, arg.ID, arg.CrmContactID, arg.MatchStatus)
	var i ExternalContact
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourceID,
		&i.AccountID,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.Emails,
		&i.Phones,
		&i.Addresses,
		&i.Organization,
		&i.JobTitle,
		&i.Birthday,
		&i.PhotoUrl,
		&i.CrmContactID,
		&i.MatchStatus,
		&i.DuplicateOfID,
		&i.Etag,
		&i.Metadata,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HostID,
		&i.LastContentHash,
	)
	return &i, err
}

const UpsertExternalContact = `-- name: UpsertExternalContact :one
INSERT INTO external_contact (
    source, source_id, account_id, host_id, display_name, first_name, last_name,
    emails, phones, addresses, organization, job_title, birthday, photo_url,
    crm_contact_id, match_status, duplicate_of_id, etag, metadata, synced_at,
    last_content_hash
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21
)
ON CONFLICT (source, source_id, COALESCE(account_id, '')) DO UPDATE SET
    -- Claim-on-first-non-NULL: legacy rows with NULL host_id get
    -- claimed by the upserting host; non-NULL ownership is preserved.
    host_id           = COALESCE(external_contact.host_id, EXCLUDED.host_id),
    display_name      = EXCLUDED.display_name,
    first_name        = EXCLUDED.first_name,
    last_name         = EXCLUDED.last_name,
    emails            = EXCLUDED.emails,
    phones            = EXCLUDED.phones,
    addresses         = EXCLUDED.addresses,
    organization      = EXCLUDED.organization,
    job_title         = EXCLUDED.job_title,
    birthday          = EXCLUDED.birthday,
    photo_url         = EXCLUDED.photo_url,
    etag              = EXCLUDED.etag,
    metadata          = EXCLUDED.metadata,
    synced_at         = EXCLUDED.synced_at,
    last_content_hash = EXCLUDED.last_content_hash,
    updated_at        = NOW()
RETURNING id, source, source_id, account_id, display_name, first_name, last_name, emails, phones, addresses, organization, job_title, birthday, photo_url, crm_contact_id, match_status, duplicate_of_id, etag, metadata, synced_at, created_at, updated_at, deleted_at, host_id, last_content_hash
`

type UpsertExternalContactParams struct {
	Source          string             `json:"source"`
	SourceID        string             `json:"source_id"`
	AccountID       pgtype.Text        `json:"account_id"`
	HostID          pgtype.UUID        `json:"host_id"`
	DisplayName     pgtype.Text        `json:"display_name"`
	FirstName       pgtype.Text        `json:"first_name"`
	LastName        pgtype.Text        `json:"last_name"`
	Emails          []byte             `json:"emails"`
	Phones          []byte             `json:"phones"`
	Addresses       []byte             `json:"addresses"`
	Organization    pgtype.Text        `json:"organization"`
	JobTitle        pgtype.Text        `json:"job_title"`
	Birthday        pgtype.Date        `json:"birthday"`
	PhotoUrl        pgtype.Text        `json:"photo_url"`
	CrmContactID    pgtype.UUID        `json:"crm_contact_id"`
	MatchStatus     pgtype.Text        `json:"match_status"`
	DuplicateOfID   pgtype.UUID        `json:"duplicate_of_id"`
	Etag            pgtype.Text        `json:"etag"`
	Metadata        []byte             `json:"metadata"`
	SyncedAt        pgtype.Timestamptz `json:"synced_at"`
	LastContentHash pgtype.Text        `json:"last_content_hash"`
}

// Named-param variant. host_id follows claim-on-first-non-NULL-emit:
// legacy rows whose host_id IS NULL (pre-migration data) get claimed
// by the first host that emits an upsert for them, but non-NULL
// ownership is preserved thereafter. This keeps existing
// icloud_contacts rows reachable from /known-ids on upgraded systems
// without requiring destructive operator cleanup. Re-pair onto a
// different Mac for already-owned rows is a documented limitation;
// scripts/admin/reset_icloud_contacts.sh handles that path.
//
// last_content_hash is written on both INSERT and UPDATE so the
// /known-ids endpoint always returns the most recent payload's hash.
// Application-layer regex enforces lowercase 64-char hex on write;
// this query stores the value verbatim.
func (q *Queries) UpsertExternalContact(ctx context.Context, arg UpsertExternalContactParams) (*ExternalContact, error) {
	row := q.db.QueryRow(ctx, UpsertExternalContact,
		arg.Source,
		arg.SourceID,
		arg.AccountID,
		arg.HostID,
		arg.DisplayName,
		arg.FirstName,
		arg.LastName,
		arg.Emails,
		arg.Phones,
		arg.Addresses,
		arg.Organization,
		arg.JobTitle,
		arg.Birthday,
		arg.PhotoUrl,
		arg.CrmContactID,
		arg.MatchStatus,
		arg.DuplicateOfID,
		arg.Etag,
		arg.Metadata,
		arg.SyncedAt,
		arg.LastContentHash,
	)
	var i ExternalContact
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourceID,
		&i.AccountID,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.Emails,
		&i.Phones,
		&i.Addresses,
		&i.Organization,
		&i.JobTitle,
		&i.Birthday,
		&i.PhotoUrl,
		&i.CrmContactID,
		&i.MatchStatus,
		&i.DuplicateOfID,
		&i.Etag,
		&i.Metadata,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HostID,
		&i.LastContentHash,
	)
	return &i, err
}

const UpsertTelegramDiscoveryCandidate = `-- name: UpsertTelegramDiscoveryCandidate :one
INSERT INTO external_contact (
    source, source_id, display_name, first_name, last_name, metadata, synced_at
) VALUES ('telegram', $1, $2, $3, $4, $5, $6)
ON CONFLICT (source, source_id, COALESCE(account_id, '')) DO UPDATE SET
    display_name = COALESCE(EXCLUDED.display_name, external_contact.display_name),
    first_name   = COALESCE(EXCLUDED.first_name,   external_contact.first_name),
    last_name    = COALESCE(EXCLUDED.last_name,    external_contact.last_name),
    metadata     = external_contact.metadata || EXCLUDED.metadata,
    synced_at    = EXCLUDED.synced_at,
    updated_at   = NOW()
RETURNING id, source, source_id, account_id, display_name, first_name, last_name, emails, phones, addresses, organization, job_title, birthday, photo_url, crm_contact_id, match_status, duplicate_of_id, etag, metadata, synced_at, created_at, updated_at, deleted_at, host_id, last_content_hash
`

type UpsertTelegramDiscoveryCandidateParams struct {
	SourceID    string             `json:"source_id"`
	DisplayName pgtype.Text        `json:"display_name"`
	FirstName   pgtype.Text        `json:"first_name"`
	LastName    pgtype.Text        `json:"last_name"`
	Metadata    []byte             `json:"metadata"`
	SyncedAt    pgtype.Timestamptz `json:"synced_at"`
}

// Telegram-specific upsert that preserves populated peer fields when a later
// message arrives with null entity data. Never clears a name/handle that was
// previously captured. Metadata is merged (|| operator) so keys from earlier
// writes (e.g. username) are retained when the new map omits them.
func (q *Queries) UpsertTelegramDiscoveryCandidate(ctx context.Context, arg UpsertTelegramDiscoveryCandidateParams) (*ExternalContact, error) {
	row := q.db.QueryRow(ctx, UpsertTelegramDiscoveryCandidate,
		arg.SourceID,
		arg.DisplayName,
		arg.FirstName,
		arg.LastName,
		arg.Metadata,
		arg.SyncedAt,
	)
	var i ExternalContact
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SourceID,
		&i.AccountID,
		&i.DisplayName,
		&i.FirstName,
		&i.LastName,
		&i.Emails,
		&i.Phones,
		&i.Addresses,
		&i.Organization,
		&i.JobTitle,
		&i.Birthday,
		&i.PhotoUrl,
		&i.CrmContactID,
		&i.MatchStatus,
		&i.DuplicateOfID,
		&i.Etag,
		&i.Metadata,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HostID,
		&i.LastContentHash,
	)
	return &i, err
}
