// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: external_contact_source_counts.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const CountExternalContactsByHostAndSource = `-- name: CountExternalContactsByHostAndSource :many
SELECT source, COUNT(*) AS count
FROM external_contact
WHERE host_id = $1
  AND deleted_at IS NULL
  AND duplicate_of_id IS NULL
GROUP BY source
ORDER BY source
`

type CountExternalContactsByHostAndSourceRow struct {
	Source string `json:"source"`
	Count  int64  `json:"count"`
}

// Counts live external_contact rows per source, scoped to a host. Powers
// the GET /api/v1/host/:id/source-counts endpoint (issue #327). Filters
// match the "caught up" semantic the Hosts page UI needs:
//   - deleted_at IS NULL: excludes tombstoned rows.
//   - duplicate_of_id IS NULL: excludes merge-dupe rows that the import
//     UI doesn't surface.
func (q *Queries) CountExternalContactsByHostAndSource(ctx context.Context, hostID *uuid.UUID) ([]*CountExternalContactsByHostAndSourceRow, error) {
	rows, err := q.db.Query(ctx, CountExternalContactsByHostAndSource, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*CountExternalContactsByHostAndSourceRow{}
	for rows.Next() {
		var i CountExternalContactsByHostAndSourceRow
		if err := rows.Scan(&i.Source, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
