// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interaction.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountContactInteractions = `-- name: CountContactInteractions :one
SELECT COUNT(*) FROM interaction
WHERE contact_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountContactInteractions(ctx context.Context, contactID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, CountContactInteractions, contactID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateInteraction = `-- name: CreateInteraction :one
INSERT INTO interaction (contact_id, source, source_ref, occurred_at, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, contact_id, source, source_ref, occurred_at, description, created_at, deleted_at
`

type CreateInteractionParams struct {
	ContactID   pgtype.UUID        `json:"contact_id"`
	Source      string             `json:"source"`
	SourceRef   pgtype.Text        `json:"source_ref"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Description pgtype.Text        `json:"description"`
}

func (q *Queries) CreateInteraction(ctx context.Context, arg CreateInteractionParams) (*Interaction, error) {
	row := q.db.QueryRow(ctx, CreateInteraction,
		arg.ContactID,
		arg.Source,
		arg.SourceRef,
		arg.OccurredAt,
		arg.Description,
	)
	var i Interaction
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Source,
		&i.SourceRef,
		&i.OccurredAt,
		&i.Description,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const FindInteractionBySourceRef = `-- name: FindInteractionBySourceRef :one
SELECT id, contact_id, source, source_ref, occurred_at, description, created_at, deleted_at FROM interaction
WHERE contact_id = $1 AND source = $2 AND source_ref = $3 AND deleted_at IS NULL
LIMIT 1
`

type FindInteractionBySourceRefParams struct {
	ContactID pgtype.UUID `json:"contact_id"`
	Source    string      `json:"source"`
	SourceRef pgtype.Text `json:"source_ref"`
}

// Find an existing interaction by contact, source, and source_ref (for deduplication)
func (q *Queries) FindInteractionBySourceRef(ctx context.Context, arg FindInteractionBySourceRefParams) (*Interaction, error) {
	row := q.db.QueryRow(ctx, FindInteractionBySourceRef, arg.ContactID, arg.Source, arg.SourceRef)
	var i Interaction
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Source,
		&i.SourceRef,
		&i.OccurredAt,
		&i.Description,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const FindInteractionInWindow = `-- name: FindInteractionInWindow :one
SELECT id, contact_id, source, source_ref, occurred_at, description, created_at, deleted_at FROM interaction
WHERE contact_id = $1
  AND source = $4
  AND deleted_at IS NULL
  AND occurred_at BETWEEN $2 AND $3
ORDER BY occurred_at DESC
LIMIT 1
`

type FindInteractionInWindowParams struct {
	ContactID    pgtype.UUID        `json:"contact_id"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
	OccurredAt_2 pgtype.Timestamptz `json:"occurred_at_2"`
	Source       string             `json:"source"`
}

// Find an existing manual interaction within a time window (for manual deduplication)
func (q *Queries) FindInteractionInWindow(ctx context.Context, arg FindInteractionInWindowParams) (*Interaction, error) {
	row := q.db.QueryRow(ctx, FindInteractionInWindow,
		arg.ContactID,
		arg.OccurredAt,
		arg.OccurredAt_2,
		arg.Source,
	)
	var i Interaction
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Source,
		&i.SourceRef,
		&i.OccurredAt,
		&i.Description,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const GetInteraction = `-- name: GetInteraction :one

SELECT id, contact_id, source, source_ref, occurred_at, description, created_at, deleted_at FROM interaction WHERE id = $1 AND deleted_at IS NULL
`

// Interaction queries
func (q *Queries) GetInteraction(ctx context.Context, id pgtype.UUID) (*Interaction, error) {
	row := q.db.QueryRow(ctx, GetInteraction, id)
	var i Interaction
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Source,
		&i.SourceRef,
		&i.OccurredAt,
		&i.Description,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const ListContactInteractions = `-- name: ListContactInteractions :many
SELECT id, contact_id, source, source_ref, occurred_at, description, created_at, deleted_at FROM interaction
WHERE contact_id = $1 AND deleted_at IS NULL
ORDER BY occurred_at DESC
LIMIT $2 OFFSET $3
`

type ListContactInteractionsParams struct {
	ContactID pgtype.UUID `json:"contact_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListContactInteractions(ctx context.Context, arg ListContactInteractionsParams) ([]*Interaction, error) {
	rows, err := q.db.Query(ctx, ListContactInteractions, arg.ContactID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Interaction{}
	for rows.Next() {
		var i Interaction
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Source,
			&i.SourceRef,
			&i.OccurredAt,
			&i.Description,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SoftDeleteInteraction = `-- name: SoftDeleteInteraction :exec
UPDATE interaction SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteInteraction(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, SoftDeleteInteraction, id)
	return err
}
