// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages_message.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const BackdateMessagesMessageClaim = `-- name: BackdateMessagesMessageClaim :exec
UPDATE messages_message
SET claimed_at = NOW() - INTERVAL '10 minutes'
WHERE id = ANY($1::uuid[])
`

// Test-only helper: ages the claim past the 5-minute TTL. Production
// code MUST NOT call this.
func (q *Queries) BackdateMessagesMessageClaim(ctx context.Context, messageIds []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, BackdateMessagesMessageClaim, messageIds)
	return err
}

const ClaimMessagesMessages = `-- name: ClaimMessagesMessages :many
UPDATE messages_message
SET claimed_at = NOW(),
    claimed_session_ref = $1
WHERE id = ANY($2::uuid[])
  AND processed_at IS NULL
  AND (claimed_at IS NULL OR claimed_at < NOW() - INTERVAL '5 minutes')
  AND deleted_at IS NULL
RETURNING id
`

type ClaimMessagesMessagesParams struct {
	SessionRef pgtype.Text   `json:"session_ref"`
	MessageIds []pgtype.UUID `json:"message_ids"`
}

// Race-safe conditional claim — same predicate shape as
// ClaimTelegramMessages. Returns the IDs actually claimed so the engine
// can detect partial claims.
func (q *Queries) ClaimMessagesMessages(ctx context.Context, arg ClaimMessagesMessagesParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, ClaimMessagesMessages, arg.SessionRef, arg.MessageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ClearMessagesMessageStaleClaim = `-- name: ClearMessagesMessageStaleClaim :exec
UPDATE messages_message
SET claimed_at = NULL,
    claimed_session_ref = NULL
WHERE id = ANY($1::uuid[])
  AND claimed_session_ref = $2
  AND processed_at IS NULL
  AND deleted_at IS NULL
`

type ClearMessagesMessageStaleClaimParams struct {
	MessageIds         []pgtype.UUID `json:"message_ids"`
	ExpectedSessionRef pgtype.Text   `json:"expected_session_ref"`
}

// Defensive recovery branch: clears claim columns for rows still
// carrying the expected stale session_ref. Used when the engine
// detected a recovery pass but FindEventBySource returned no row.
func (q *Queries) ClearMessagesMessageStaleClaim(ctx context.Context, arg ClearMessagesMessageStaleClaimParams) error {
	_, err := q.db.Exec(ctx, ClearMessagesMessageStaleClaim, arg.MessageIds, arg.ExpectedSessionRef)
	return err
}

const GetMessagesMessage = `-- name: GetMessagesMessage :one
SELECT id, guid, chat_guid, peer_handle, peer_normalized, text, message_type, sent_at, is_outgoing, is_group_chat, reply_to_guid, matched_contact_id, interaction_id, mac_host_id, processed_at, claimed_at, claimed_session_ref, deleted_at, created_at FROM messages_message
WHERE guid = $1
  AND deleted_at IS NULL
`

// Lookup by guid (primary external identifier). Used by reply-target
// resolution.
func (q *Queries) GetMessagesMessage(ctx context.Context, guid string) (*MessagesMessage, error) {
	row := q.db.QueryRow(ctx, GetMessagesMessage, guid)
	var i MessagesMessage
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.ChatGuid,
		&i.PeerHandle,
		&i.PeerNormalized,
		&i.Text,
		&i.MessageType,
		&i.SentAt,
		&i.IsOutgoing,
		&i.IsGroupChat,
		&i.ReplyToGuid,
		&i.MatchedContactID,
		&i.InteractionID,
		&i.MacHostID,
		&i.ProcessedAt,
		&i.ClaimedAt,
		&i.ClaimedSessionRef,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const GetMessagesMessageByReplyTarget = `-- name: GetMessagesMessageByReplyTarget :one
SELECT id, guid, chat_guid, peer_handle, peer_normalized, text, message_type, sent_at, is_outgoing, is_group_chat, reply_to_guid, matched_contact_id, interaction_id, mac_host_id, processed_at, claimed_at, claimed_session_ref, deleted_at, created_at FROM messages_message
WHERE chat_guid = $1
  AND guid = $2
  AND deleted_at IS NULL
`

type GetMessagesMessageByReplyTargetParams struct {
	ChatGuid string `json:"chat_guid"`
	Guid     string `json:"guid"`
}

// Source-neutral analog of GetTelegramMessage for the aggregator's
// explicit-reply-bridge path. chat_guid is included for scoping
// selectivity.
func (q *Queries) GetMessagesMessageByReplyTarget(ctx context.Context, arg GetMessagesMessageByReplyTargetParams) (*MessagesMessage, error) {
	row := q.db.QueryRow(ctx, GetMessagesMessageByReplyTarget, arg.ChatGuid, arg.Guid)
	var i MessagesMessage
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.ChatGuid,
		&i.PeerHandle,
		&i.PeerNormalized,
		&i.Text,
		&i.MessageType,
		&i.SentAt,
		&i.IsOutgoing,
		&i.IsGroupChat,
		&i.ReplyToGuid,
		&i.MatchedContactID,
		&i.InteractionID,
		&i.MacHostID,
		&i.ProcessedAt,
		&i.ClaimedAt,
		&i.ClaimedSessionRef,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const GetMessagesMessageContainer = `-- name: GetMessagesMessageContainer :one
SELECT chat_guid, is_group_chat
FROM messages_message
WHERE id = $1
`

type GetMessagesMessageContainerRow struct {
	ChatGuid    string `json:"chat_guid"`
	IsGroupChat bool   `json:"is_group_chat"`
}

// Returns the venue-container key (chat_guid + group flag) for a staging row by
// its UUID. Used by the live interaction recorder to resolve the messages
// venue. The container is consistent across all messages in one aggregated
// session, so reading the first id is sufficient.
func (q *Queries) GetMessagesMessageContainer(ctx context.Context, id pgtype.UUID) (*GetMessagesMessageContainerRow, error) {
	row := q.db.QueryRow(ctx, GetMessagesMessageContainer, id)
	var i GetMessagesMessageContainerRow
	err := row.Scan(&i.ChatGuid, &i.IsGroupChat)
	return &i, err
}

const HardDeleteMessagesMessagesByMacHost = `-- name: HardDeleteMessagesMessagesByMacHost :exec
DELETE FROM messages_message
WHERE mac_host_id = $1
`

// Test-only helper (mirrors HardDeleteTelegramMessagesByChatIDRange).
// Cleanup needs hard-delete because the upsert does not clear deleted_at
// on conflict, so soft-deleted rows would resurrect as phantoms on the
// next run. Scoped by mac_host_id so tests can pass a fresh mac_host UUID
// per run and clean only their own rows.
func (q *Queries) HardDeleteMessagesMessagesByMacHost(ctx context.Context, macHostID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, HardDeleteMessagesMessagesByMacHost, macHostID)
	return err
}

const ListStrandedMessagesMessages = `-- name: ListStrandedMessagesMessages :many
SELECT id, guid, chat_guid, peer_handle, peer_normalized, text, message_type, sent_at, is_outgoing, is_group_chat, reply_to_guid, matched_contact_id, interaction_id, mac_host_id, processed_at, claimed_at, claimed_session_ref, deleted_at, created_at FROM messages_message
WHERE matched_contact_id IS NULL
  AND processed_at IS NULL
  AND deleted_at IS NULL
ORDER BY sent_at
`

// Lists rows with matched_contact_id IS NULL — i.e., rows that the
// ingest service accepted into staging but couldn't match to a contact
// at the time. The crm-admin --messages-rematch-stranded command
// iterates this list to retroactively match rows after a contact_method
// is added.
func (q *Queries) ListStrandedMessagesMessages(ctx context.Context) ([]*MessagesMessage, error) {
	rows, err := q.db.Query(ctx, ListStrandedMessagesMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*MessagesMessage{}
	for rows.Next() {
		var i MessagesMessage
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.ChatGuid,
			&i.PeerHandle,
			&i.PeerNormalized,
			&i.Text,
			&i.MessageType,
			&i.SentAt,
			&i.IsOutgoing,
			&i.IsGroupChat,
			&i.ReplyToGuid,
			&i.MatchedContactID,
			&i.InteractionID,
			&i.MacHostID,
			&i.ProcessedAt,
			&i.ClaimedAt,
			&i.ClaimedSessionRef,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUnprocessedMessagesByContact = `-- name: ListUnprocessedMessagesByContact :many
SELECT id, guid, chat_guid, peer_handle, peer_normalized, text, message_type, sent_at, is_outgoing, is_group_chat, reply_to_guid, matched_contact_id, interaction_id, mac_host_id, processed_at, claimed_at, claimed_session_ref, deleted_at, created_at FROM messages_message
WHERE matched_contact_id = $1
  AND processed_at IS NULL
  AND (claimed_at IS NULL OR claimed_at < NOW() - INTERVAL '5 minutes')
  AND deleted_at IS NULL
ORDER BY chat_guid, sent_at
`

func (q *Queries) ListUnprocessedMessagesByContact(ctx context.Context, matchedContactID pgtype.UUID) ([]*MessagesMessage, error) {
	rows, err := q.db.Query(ctx, ListUnprocessedMessagesByContact, matchedContactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*MessagesMessage{}
	for rows.Next() {
		var i MessagesMessage
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.ChatGuid,
			&i.PeerHandle,
			&i.PeerNormalized,
			&i.Text,
			&i.MessageType,
			&i.SentAt,
			&i.IsOutgoing,
			&i.IsGroupChat,
			&i.ReplyToGuid,
			&i.MatchedContactID,
			&i.InteractionID,
			&i.MacHostID,
			&i.ProcessedAt,
			&i.ClaimedAt,
			&i.ClaimedSessionRef,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUnprocessedMessagesByContactAndChat = `-- name: ListUnprocessedMessagesByContactAndChat :many
SELECT id, guid, chat_guid, peer_handle, peer_normalized, text, message_type, sent_at, is_outgoing, is_group_chat, reply_to_guid, matched_contact_id, interaction_id, mac_host_id, processed_at, claimed_at, claimed_session_ref, deleted_at, created_at FROM messages_message
WHERE matched_contact_id = $1
  AND chat_guid = $2
  AND processed_at IS NULL
  AND (claimed_at IS NULL OR claimed_at < NOW() - INTERVAL '5 minutes')
  AND deleted_at IS NULL
ORDER BY sent_at
`

type ListUnprocessedMessagesByContactAndChatParams struct {
	MatchedContactID pgtype.UUID `json:"matched_contact_id"`
	ChatGuid         string      `json:"chat_guid"`
}

func (q *Queries) ListUnprocessedMessagesByContactAndChat(ctx context.Context, arg ListUnprocessedMessagesByContactAndChatParams) ([]*MessagesMessage, error) {
	rows, err := q.db.Query(ctx, ListUnprocessedMessagesByContactAndChat, arg.MatchedContactID, arg.ChatGuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*MessagesMessage{}
	for rows.Next() {
		var i MessagesMessage
		if err := rows.Scan(
			&i.ID,
			&i.Guid,
			&i.ChatGuid,
			&i.PeerHandle,
			&i.PeerNormalized,
			&i.Text,
			&i.MessageType,
			&i.SentAt,
			&i.IsOutgoing,
			&i.IsGroupChat,
			&i.ReplyToGuid,
			&i.MatchedContactID,
			&i.InteractionID,
			&i.MacHostID,
			&i.ProcessedAt,
			&i.ClaimedAt,
			&i.ClaimedSessionRef,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUnprocessedMessagesChatsByContact = `-- name: ListUnprocessedMessagesChatsByContact :many
SELECT DISTINCT chat_guid
FROM messages_message
WHERE matched_contact_id = $1
  AND processed_at IS NULL
  AND (claimed_at IS NULL OR claimed_at < NOW() - INTERVAL '5 minutes')
  AND deleted_at IS NULL
ORDER BY chat_guid ASC
`

// Distinct chat_guid values for a contact with at least one eligible
// (unprocessed AND unclaimed-or-stale) staging row. Used by the
// messaging aggregator worker to drive per-chat AggregateForContact
// invocations — the chat-aware path is what preserves the engine's
// extend/bridge/coalesce contract (see spec §3 "Stage 2 — Aggregator").
func (q *Queries) ListUnprocessedMessagesChatsByContact(ctx context.Context, matchedContactID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, ListUnprocessedMessagesChatsByContact, matchedContactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var chat_guid string
		if err := rows.Scan(&chat_guid); err != nil {
			return nil, err
		}
		items = append(items, chat_guid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUnprocessedMessagesContactIDs = `-- name: ListUnprocessedMessagesContactIDs :many
SELECT DISTINCT matched_contact_id
FROM messages_message
WHERE matched_contact_id IS NOT NULL
  AND processed_at IS NULL
  AND (claimed_at IS NULL OR claimed_at < NOW() - INTERVAL '5 minutes')
  AND deleted_at IS NULL
`

// Claim-aware filter — same predicate shape as telegram_message.
func (q *Queries) ListUnprocessedMessagesContactIDs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, ListUnprocessedMessagesContactIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var matched_contact_id pgtype.UUID
		if err := rows.Scan(&matched_contact_id); err != nil {
			return nil, err
		}
		items = append(items, matched_contact_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkMessagesMessagesProcessed = `-- name: MarkMessagesMessagesProcessed :exec
UPDATE messages_message
SET processed_at = NOW(),
    interaction_id = $1,
    claimed_at = NULL,
    claimed_session_ref = NULL
WHERE id = ANY($2::uuid[])
  AND deleted_at IS NULL
`

type MarkMessagesMessagesProcessedParams struct {
	InteractionID pgtype.UUID   `json:"interaction_id"`
	MessageIds    []pgtype.UUID `json:"message_ids"`
}

// Non-tx variant. Mirror of MarkTelegramMessagesProcessed — used by the
// engine's extend/promote/bridge paths only; no session-scope predicate
// needed because those paths do not publish events.
func (q *Queries) MarkMessagesMessagesProcessed(ctx context.Context, arg MarkMessagesMessagesProcessedParams) error {
	_, err := q.db.Exec(ctx, MarkMessagesMessagesProcessed, arg.InteractionID, arg.MessageIds)
	return err
}

const MarkMessagesMessagesProcessedForSession = `-- name: MarkMessagesMessagesProcessedForSession :execrows
UPDATE messages_message
SET processed_at = NOW(),
    interaction_id = $1,
    claimed_at = NULL,
    claimed_session_ref = NULL
WHERE id = ANY($2::uuid[])
  AND (claimed_session_ref = $3 OR claimed_session_ref IS NULL)
  AND processed_at IS NULL
  AND deleted_at IS NULL
`

type MarkMessagesMessagesProcessedForSessionParams struct {
	InteractionID pgtype.UUID   `json:"interaction_id"`
	MessageIds    []pgtype.UUID `json:"message_ids"`
	SessionRef    pgtype.Text   `json:"session_ref"`
}

// Tx-bound variant. Mirror of MarkTelegramMessagesProcessedForSession —
// used by InteractionRecorder consumer when processing a create-path
// event. The predicate rejects rows whose claimed_session_ref differs
// from this consumer's session (boundary-shift defense) but ALSO
// accepts rows that were never claimed (claimed_session_ref IS NULL):
// the non-tx publish path leaves rows unclaimed, and there's no risk
// of cross-event overwrite when the row has not yet been processed by
// anyone.
//
// Returns rows affected. The consumer distinguishes three cases:
//   - affected == len(message_ids): happy path.
//   - affected == 0 on a fresh write: predicate filtered everything
//     out (boundary-shift race). Caller MUST roll back the tx.
//   - affected == 0 on a replay: expected; rows were already linked
//     to the existing interaction on the original attempt.
func (q *Queries) MarkMessagesMessagesProcessedForSession(ctx context.Context, arg MarkMessagesMessagesProcessedForSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, MarkMessagesMessagesProcessedForSession, arg.InteractionID, arg.MessageIds, arg.SessionRef)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const UpdateMatchedContactForStrandedMessage = `-- name: UpdateMatchedContactForStrandedMessage :exec
UPDATE messages_message
SET matched_contact_id = $1,
    peer_normalized    = $2
WHERE id = $3
  AND matched_contact_id IS NULL
  AND processed_at IS NULL
  AND deleted_at IS NULL
`

type UpdateMatchedContactForStrandedMessageParams struct {
	MatchedContactID pgtype.UUID `json:"matched_contact_id"`
	PeerNormalized   pgtype.Text `json:"peer_normalized"`
	ID               pgtype.UUID `json:"id"`
}

// Sets matched_contact_id + peer_normalized on a single stranded row.
// Scoped to rows that are still unmatched + unprocessed so a
// concurrent ingest path (a never-stranding daemon push for a peer
// that just got matched) cannot be overwritten by this admin path.
func (q *Queries) UpdateMatchedContactForStrandedMessage(ctx context.Context, arg UpdateMatchedContactForStrandedMessageParams) error {
	_, err := q.db.Exec(ctx, UpdateMatchedContactForStrandedMessage, arg.MatchedContactID, arg.PeerNormalized, arg.ID)
	return err
}

const UpsertMessagesMessage = `-- name: UpsertMessagesMessage :one
INSERT INTO messages_message (
    guid, chat_guid, peer_handle, peer_normalized,
    text, message_type, sent_at, is_outgoing, is_group_chat,
    reply_to_guid, matched_contact_id, mac_host_id
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9,
    $10, $11, $12
)
ON CONFLICT (guid) DO UPDATE SET
    -- No-op update so RETURNING reliably returns the existing row. We
    -- deliberately do NOT overwrite text or any user-visible field on
    -- conflict: a second push of the same guid is by definition the same
    -- content (chat.db rows are immutable post-iOS 16 except for edits,
    -- which are out of v1 scope per spec §2 messages → edits/deletes).
    guid = EXCLUDED.guid
RETURNING id, guid, chat_guid, peer_handle, peer_normalized, text, message_type, sent_at, is_outgoing, is_group_chat, reply_to_guid, matched_contact_id, interaction_id, mac_host_id, processed_at, claimed_at, claimed_session_ref, deleted_at, created_at
`

type UpsertMessagesMessageParams struct {
	Guid             string             `json:"guid"`
	ChatGuid         string             `json:"chat_guid"`
	PeerHandle       string             `json:"peer_handle"`
	PeerNormalized   pgtype.Text        `json:"peer_normalized"`
	Text             pgtype.Text        `json:"text"`
	MessageType      string             `json:"message_type"`
	SentAt           pgtype.Timestamptz `json:"sent_at"`
	IsOutgoing       bool               `json:"is_outgoing"`
	IsGroupChat      bool               `json:"is_group_chat"`
	ReplyToGuid      pgtype.Text        `json:"reply_to_guid"`
	MatchedContactID pgtype.UUID        `json:"matched_contact_id"`
	MacHostID        pgtype.UUID        `json:"mac_host_id"`
}

// Insert with no-op on guid conflict. peer_normalized and matched_contact_id
// come from the Pi ingest service identity-match path. mac_host_id is
// provenance — multi-host dedup is by guid, not by host.
func (q *Queries) UpsertMessagesMessage(ctx context.Context, arg UpsertMessagesMessageParams) (*MessagesMessage, error) {
	row := q.db.QueryRow(ctx, UpsertMessagesMessage,
		arg.Guid,
		arg.ChatGuid,
		arg.PeerHandle,
		arg.PeerNormalized,
		arg.Text,
		arg.MessageType,
		arg.SentAt,
		arg.IsOutgoing,
		arg.IsGroupChat,
		arg.ReplyToGuid,
		arg.MatchedContactID,
		arg.MacHostID,
	)
	var i MessagesMessage
	err := row.Scan(
		&i.ID,
		&i.Guid,
		&i.ChatGuid,
		&i.PeerHandle,
		&i.PeerNormalized,
		&i.Text,
		&i.MessageType,
		&i.SentAt,
		&i.IsOutgoing,
		&i.IsGroupChat,
		&i.ReplyToGuid,
		&i.MatchedContactID,
		&i.InteractionID,
		&i.MacHostID,
		&i.ProcessedAt,
		&i.ClaimedAt,
		&i.ClaimedSessionRef,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return &i, err
}
