// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState `json:"river_job_state"`
	Valid         bool          `json:"valid"` // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type CalendarEvent struct {
	ID                   pgtype.UUID        `json:"id"`
	GcalEventID          string             `json:"gcal_event_id"`
	GcalCalendarID       string             `json:"gcal_calendar_id"`
	GoogleAccountID      string             `json:"google_account_id"`
	Title                pgtype.Text        `json:"title"`
	Description          pgtype.Text        `json:"description"`
	Location             pgtype.Text        `json:"location"`
	StartTime            pgtype.Timestamptz `json:"start_time"`
	EndTime              pgtype.Timestamptz `json:"end_time"`
	AllDay               pgtype.Bool        `json:"all_day"`
	Status               pgtype.Text        `json:"status"`
	UserResponse         pgtype.Text        `json:"user_response"`
	OrganizerEmail       pgtype.Text        `json:"organizer_email"`
	Attendees            []byte             `json:"attendees"`
	MatchedContactIds    []pgtype.UUID      `json:"matched_contact_ids"`
	SyncedAt             pgtype.Timestamptz `json:"synced_at"`
	LastContactedUpdated pgtype.Bool        `json:"last_contacted_updated"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	HtmlLink             pgtype.Text        `json:"html_link"`
}

type Connection struct {
	ID           pgtype.UUID        `json:"id"`
	ContactAID   pgtype.UUID        `json:"contact_a_id"`
	ContactBID   pgtype.UUID        `json:"contact_b_id"`
	Relationship pgtype.Text        `json:"relationship"`
	Strength     pgtype.Int4        `json:"strength"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Contact struct {
	ID                pgtype.UUID        `json:"id"`
	FullName          string             `json:"full_name"`
	Location          pgtype.Text        `json:"location"`
	Birthday          pgtype.Date        `json:"birthday"`
	HowMet            pgtype.Text        `json:"how_met"`
	Cadence           pgtype.Text        `json:"cadence"`
	LastContacted     pgtype.Timestamptz `json:"last_contacted"`
	ProfilePhoto      pgtype.Text        `json:"profile_photo"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ContactBy         pgtype.Date        `json:"contact_by"`
	LastInteractionAt pgtype.Timestamptz `json:"last_interaction_at"`
	LastOutreachAt    pgtype.Timestamptz `json:"last_outreach_at"`
	LastResponseAt    pgtype.Timestamptz `json:"last_response_at"`
}

type ContactEnrichment struct {
	ID                pgtype.UUID        `json:"id"`
	ContactID         pgtype.UUID        `json:"contact_id"`
	Source            string             `json:"source"`
	AccountID         pgtype.Text        `json:"account_id"`
	Field             string             `json:"field"`
	ExternalContactID pgtype.UUID        `json:"external_contact_id"`
	OriginalValue     pgtype.Text        `json:"original_value"`
	EnrichedAt        pgtype.Timestamptz `json:"enriched_at"`
}

type ContactMethod struct {
	ID              pgtype.UUID        `json:"id"`
	ContactID       pgtype.UUID        `json:"contact_id"`
	Type            string             `json:"type"`
	Value           string             `json:"value"`
	IsPrimary       pgtype.Bool        `json:"is_primary"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ValueNormalized string             `json:"value_normalized"`
}

type ContactSummary struct {
	ID          pgtype.UUID        `json:"id"`
	ContactID   pgtype.UUID        `json:"contact_id"`
	Summary     string             `json:"summary"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type ContactTag struct {
	ContactID pgtype.UUID        `json:"contact_id"`
	TagID     pgtype.UUID        `json:"tag_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ContactTask struct {
	ID             pgtype.UUID        `json:"id"`
	ContactID      pgtype.UUID        `json:"contact_id"`
	Provider       string             `json:"provider"`
	Kind           string             `json:"kind"`
	ExternalTaskID string             `json:"external_task_id"`
	State          string             `json:"state"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
}

type Event struct {
	ID         pgtype.UUID        `json:"id"`
	Source     string             `json:"source"`
	SourceID   pgtype.Text        `json:"source_id"`
	Kind       string             `json:"kind"`
	Payload    []byte             `json:"payload"`
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type EventConsumerClaim struct {
	EventID   pgtype.UUID        `json:"event_id"`
	Consumer  string             `json:"consumer"`
	ClaimedAt pgtype.Timestamptz `json:"claimed_at"`
}

type EventShadowCadenceObservation struct {
	ID                  pgtype.UUID        `json:"id"`
	EventID             pgtype.UUID        `json:"event_id"`
	Writer              string             `json:"writer"`
	ContactID           pgtype.UUID        `json:"contact_id"`
	Source              string             `json:"source"`
	Direction           string             `json:"direction"`
	Branch              string             `json:"branch"`
	OccurredAt          pgtype.Timestamptz `json:"occurred_at"`
	PrevLastContacted   pgtype.Timestamptz `json:"prev_last_contacted"`
	PrevLastOutreachAt  pgtype.Timestamptz `json:"prev_last_outreach_at"`
	PrevLastResponseAt  pgtype.Timestamptz `json:"prev_last_response_at"`
	PrevContactBy       pgtype.Date        `json:"prev_contact_by"`
	NextLastContacted   pgtype.Timestamptz `json:"next_last_contacted"`
	NextLastOutreachAt  pgtype.Timestamptz `json:"next_last_outreach_at"`
	NextLastResponseAt  pgtype.Timestamptz `json:"next_last_response_at"`
	NextContactBy       pgtype.Date        `json:"next_contact_by"`
	ApplyLastContacted  bool               `json:"apply_last_contacted"`
	ApplyLastOutreachAt bool               `json:"apply_last_outreach_at"`
	ApplyLastResponseAt bool               `json:"apply_last_response_at"`
	ApplyContactBy      bool               `json:"apply_contact_by"`
	ObservedAt          pgtype.Timestamptz `json:"observed_at"`
}

type EventShadowFollowupObservation struct {
	ID                    pgtype.UUID        `json:"id"`
	EventID               pgtype.UUID        `json:"event_id"`
	Writer                string             `json:"writer"`
	ContactID             pgtype.UUID        `json:"contact_id"`
	Source                string             `json:"source"`
	Direction             string             `json:"direction"`
	OccurredAt            pgtype.Timestamptz `json:"occurred_at"`
	Action                string             `json:"action"`
	SkipReason            pgtype.Text        `json:"skip_reason"`
	WouldIdempotencyKey   pgtype.Text        `json:"would_idempotency_key"`
	WouldDeadline         pgtype.Date        `json:"would_deadline"`
	DirectContactTaskID   pgtype.UUID        `json:"direct_contact_task_id"`
	ConsumerCalledTodoist bool               `json:"consumer_called_todoist"`
	ObservedAt            pgtype.Timestamptz `json:"observed_at"`
}

type EventShadowObservation struct {
	ID            pgtype.UUID        `json:"id"`
	EventID       pgtype.UUID        `json:"event_id"`
	Writer        string             `json:"writer"`
	Kind          string             `json:"kind"`
	Source        string             `json:"source"`
	SourceRef     pgtype.Text        `json:"source_ref"`
	ContactID     pgtype.UUID        `json:"contact_id"`
	Direction     string             `json:"direction"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	InteractionID pgtype.UUID        `json:"interaction_id"`
	Replay        bool               `json:"replay"`
	ObservedAt    pgtype.Timestamptz `json:"observed_at"`
}

type ExternalContact struct {
	ID            pgtype.UUID        `json:"id"`
	Source        string             `json:"source"`
	SourceID      string             `json:"source_id"`
	AccountID     pgtype.Text        `json:"account_id"`
	DisplayName   pgtype.Text        `json:"display_name"`
	FirstName     pgtype.Text        `json:"first_name"`
	LastName      pgtype.Text        `json:"last_name"`
	Emails        []byte             `json:"emails"`
	Phones        []byte             `json:"phones"`
	Addresses     []byte             `json:"addresses"`
	Organization  pgtype.Text        `json:"organization"`
	JobTitle      pgtype.Text        `json:"job_title"`
	Birthday      pgtype.Date        `json:"birthday"`
	PhotoUrl      pgtype.Text        `json:"photo_url"`
	CrmContactID  pgtype.UUID        `json:"crm_contact_id"`
	MatchStatus   pgtype.Text        `json:"match_status"`
	DuplicateOfID pgtype.UUID        `json:"duplicate_of_id"`
	Etag          pgtype.Text        `json:"etag"`
	Metadata      []byte             `json:"metadata"`
	SyncedAt      pgtype.Timestamptz `json:"synced_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ExternalIdentity struct {
	ID              pgtype.UUID        `json:"id"`
	Identifier      string             `json:"identifier"`
	IdentifierType  string             `json:"identifier_type"`
	RawIdentifier   pgtype.Text        `json:"raw_identifier"`
	Source          string             `json:"source"`
	SourceID        pgtype.Text        `json:"source_id"`
	ContactID       pgtype.UUID        `json:"contact_id"`
	MatchType       pgtype.Text        `json:"match_type"`
	MatchConfidence pgtype.Float8      `json:"match_confidence"`
	DisplayName     pgtype.Text        `json:"display_name"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	MessageCount    pgtype.Int4        `json:"message_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ExternalSyncLog struct {
	ID             pgtype.UUID        `json:"id"`
	SyncStateID    pgtype.UUID        `json:"sync_state_id"`
	Source         string             `json:"source"`
	AccountID      pgtype.Text        `json:"account_id"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	Status         string             `json:"status"`
	ItemsProcessed pgtype.Int4        `json:"items_processed"`
	ItemsMatched   pgtype.Int4        `json:"items_matched"`
	ItemsCreated   pgtype.Int4        `json:"items_created"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ExternalSyncState struct {
	ID                   pgtype.UUID        `json:"id"`
	Source               string             `json:"source"`
	AccountID            pgtype.Text        `json:"account_id"`
	Enabled              bool               `json:"enabled"`
	Status               string             `json:"status"`
	Strategy             string             `json:"strategy"`
	LastSyncAt           pgtype.Timestamptz `json:"last_sync_at"`
	LastSuccessfulSyncAt pgtype.Timestamptz `json:"last_successful_sync_at"`
	NextSyncAt           pgtype.Timestamptz `json:"next_sync_at"`
	SyncCursor           pgtype.Text        `json:"sync_cursor"`
	ErrorMessage         pgtype.Text        `json:"error_message"`
	ErrorCount           int32              `json:"error_count"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Interaction struct {
	ID          pgtype.UUID        `json:"id"`
	ContactID   pgtype.UUID        `json:"contact_id"`
	Source      string             `json:"source"`
	SourceRef   pgtype.Text        `json:"source_ref"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	Direction   string             `json:"direction"`
}

type Note struct {
	ID        pgtype.UUID        `json:"id"`
	ContactID pgtype.UUID        `json:"contact_id"`
	Body      string             `json:"body"`
	Category  pgtype.Text        `json:"category"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type NoteEmbedding struct {
	NoteID    pgtype.UUID        `json:"note_id"`
	Embedding pgvector.Vector    `json:"embedding"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OauthCredential struct {
	ID                    pgtype.UUID        `json:"id"`
	Provider              string             `json:"provider"`
	AccountID             string             `json:"account_id"`
	AccountName           pgtype.Text        `json:"account_name"`
	AccessTokenEncrypted  []byte             `json:"access_token_encrypted"`
	RefreshTokenEncrypted []byte             `json:"refresh_token_encrypted"`
	EncryptionNonce       []byte             `json:"encryption_nonce"`
	TokenType             pgtype.Text        `json:"token_type"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	Scopes                []string           `json:"scopes"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type PromptQuery struct {
	ID          pgtype.UUID        `json:"id"`
	Query       string             `json:"query"`
	Response    string             `json:"response"`
	ContextUsed []byte             `json:"context_used"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RiverJob struct {
	ID           int64              `json:"id"`
	State        RiverJobState      `json:"state"`
	Attempt      int16              `json:"attempt"`
	MaxAttempts  int16              `json:"max_attempts"`
	AttemptedAt  pgtype.Timestamptz `json:"attempted_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	FinalizedAt  pgtype.Timestamptz `json:"finalized_at"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	Priority     int16              `json:"priority"`
	Args         []byte             `json:"args"`
	AttemptedBy  []string           `json:"attempted_by"`
	Errors       [][]byte           `json:"errors"`
	Kind         string             `json:"kind"`
	Metadata     []byte             `json:"metadata"`
	Queue        string             `json:"queue"`
	Tags         []string           `json:"tags"`
	UniqueKey    []byte             `json:"unique_key"`
	UniqueStates pgtype.Bits        `json:"unique_states"`
}

type Tag struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Color     pgtype.Text        `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TelegramChannelState struct {
	ID         pgtype.UUID        `json:"id"`
	ChannelID  int64              `json:"channel_id"`
	Pts        int32              `json:"pts"`
	AccessHash int64              `json:"access_hash"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type TelegramChatConfig struct {
	ID               pgtype.UUID        `json:"id"`
	TelegramChatID   int64              `json:"telegram_chat_id"`
	ChatTitle        pgtype.Text        `json:"chat_title"`
	ChatType         string             `json:"chat_type"`
	MemberCount      pgtype.Int4        `json:"member_count"`
	Status           string             `json:"status"`
	BackfillCursor   pgtype.Int4        `json:"backfill_cursor"`
	BackfillComplete bool               `json:"backfill_complete"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type TelegramMessage struct {
	ID                 pgtype.UUID        `json:"id"`
	TelegramMessageID  int32              `json:"telegram_message_id"`
	TelegramChatID     int64              `json:"telegram_chat_id"`
	ChatType           string             `json:"chat_type"`
	ChatTitle          pgtype.Text        `json:"chat_title"`
	MessageText        pgtype.Text        `json:"message_text"`
	MessageType        string             `json:"message_type"`
	SentAt             pgtype.Timestamptz `json:"sent_at"`
	EditedAt           pgtype.Timestamptz `json:"edited_at"`
	IsOutgoing         bool               `json:"is_outgoing"`
	ReplyToMsgID       pgtype.Int4        `json:"reply_to_msg_id"`
	PeerUserID         pgtype.Int8        `json:"peer_user_id"`
	PeerUsername       pgtype.Text        `json:"peer_username"`
	PeerFirstName      pgtype.Text        `json:"peer_first_name"`
	PeerLastName       pgtype.Text        `json:"peer_last_name"`
	PeerPhone          pgtype.Text        `json:"peer_phone"`
	MatchedContactID   pgtype.UUID        `json:"matched_contact_id"`
	InteractionID      pgtype.UUID        `json:"interaction_id"`
	ProcessedAt        pgtype.Timestamptz `json:"processed_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	PeerEntityResolved bool               `json:"peer_entity_resolved"`
}

type TelegramSession struct {
	ID                   int32              `json:"id"`
	SessionDataEncrypted []byte             `json:"session_data_encrypted"`
	EncryptionNonce      []byte             `json:"encryption_nonce"`
	PhoneNumber          pgtype.Text        `json:"phone_number"`
	TelegramUserID       pgtype.Int8        `json:"telegram_user_id"`
	Username             pgtype.Text        `json:"username"`
	AuthState            string             `json:"auth_state"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type TelegramUpdateState struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    int64              `json:"user_id"`
	Pts       int32              `json:"pts"`
	Qts       int32              `json:"qts"`
	Seq       int32              `json:"seq"`
	Date      int32              `json:"date"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
