// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type CalendarEvent struct {
	ID                   pgtype.UUID        `json:"id"`
	GcalEventID          string             `json:"gcal_event_id"`
	GcalCalendarID       string             `json:"gcal_calendar_id"`
	GoogleAccountID      string             `json:"google_account_id"`
	Title                pgtype.Text        `json:"title"`
	Description          pgtype.Text        `json:"description"`
	Location             pgtype.Text        `json:"location"`
	StartTime            pgtype.Timestamptz `json:"start_time"`
	EndTime              pgtype.Timestamptz `json:"end_time"`
	AllDay               pgtype.Bool        `json:"all_day"`
	Status               pgtype.Text        `json:"status"`
	UserResponse         pgtype.Text        `json:"user_response"`
	OrganizerEmail       pgtype.Text        `json:"organizer_email"`
	Attendees            []byte             `json:"attendees"`
	MatchedContactIds    []pgtype.UUID      `json:"matched_contact_ids"`
	SyncedAt             pgtype.Timestamptz `json:"synced_at"`
	LastContactedUpdated pgtype.Bool        `json:"last_contacted_updated"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Connection struct {
	ID           pgtype.UUID        `json:"id"`
	ContactAID   pgtype.UUID        `json:"contact_a_id"`
	ContactBID   pgtype.UUID        `json:"contact_b_id"`
	Relationship pgtype.Text        `json:"relationship"`
	Strength     pgtype.Int4        `json:"strength"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Contact struct {
	ID            pgtype.UUID        `json:"id"`
	FullName      string             `json:"full_name"`
	Location      pgtype.Text        `json:"location"`
	Birthday      pgtype.Date        `json:"birthday"`
	HowMet        pgtype.Text        `json:"how_met"`
	Cadence       pgtype.Text        `json:"cadence"`
	LastContacted pgtype.Timestamptz `json:"last_contacted"`
	ProfilePhoto  pgtype.Text        `json:"profile_photo"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ContactEnrichment struct {
	ID                pgtype.UUID        `json:"id"`
	ContactID         pgtype.UUID        `json:"contact_id"`
	Source            string             `json:"source"`
	AccountID         pgtype.Text        `json:"account_id"`
	Field             string             `json:"field"`
	ExternalContactID pgtype.UUID        `json:"external_contact_id"`
	OriginalValue     pgtype.Text        `json:"original_value"`
	EnrichedAt        pgtype.Timestamptz `json:"enriched_at"`
}

type ContactMethod struct {
	ID        pgtype.UUID        `json:"id"`
	ContactID pgtype.UUID        `json:"contact_id"`
	Type      string             `json:"type"`
	Value     string             `json:"value"`
	IsPrimary pgtype.Bool        `json:"is_primary"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ContactSummary struct {
	ID          pgtype.UUID        `json:"id"`
	ContactID   pgtype.UUID        `json:"contact_id"`
	Summary     string             `json:"summary"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type ContactTag struct {
	ContactID pgtype.UUID        `json:"contact_id"`
	TagID     pgtype.UUID        `json:"tag_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ExternalContact struct {
	ID            pgtype.UUID        `json:"id"`
	Source        string             `json:"source"`
	SourceID      string             `json:"source_id"`
	AccountID     pgtype.Text        `json:"account_id"`
	DisplayName   pgtype.Text        `json:"display_name"`
	FirstName     pgtype.Text        `json:"first_name"`
	LastName      pgtype.Text        `json:"last_name"`
	Emails        []byte             `json:"emails"`
	Phones        []byte             `json:"phones"`
	Addresses     []byte             `json:"addresses"`
	Organization  pgtype.Text        `json:"organization"`
	JobTitle      pgtype.Text        `json:"job_title"`
	Birthday      pgtype.Date        `json:"birthday"`
	PhotoUrl      pgtype.Text        `json:"photo_url"`
	CrmContactID  pgtype.UUID        `json:"crm_contact_id"`
	MatchStatus   pgtype.Text        `json:"match_status"`
	DuplicateOfID pgtype.UUID        `json:"duplicate_of_id"`
	Etag          pgtype.Text        `json:"etag"`
	Metadata      []byte             `json:"metadata"`
	SyncedAt      pgtype.Timestamptz `json:"synced_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ExternalIdentity struct {
	ID              pgtype.UUID        `json:"id"`
	Identifier      string             `json:"identifier"`
	IdentifierType  string             `json:"identifier_type"`
	RawIdentifier   pgtype.Text        `json:"raw_identifier"`
	Source          string             `json:"source"`
	SourceID        pgtype.Text        `json:"source_id"`
	ContactID       pgtype.UUID        `json:"contact_id"`
	MatchType       pgtype.Text        `json:"match_type"`
	MatchConfidence pgtype.Float8      `json:"match_confidence"`
	DisplayName     pgtype.Text        `json:"display_name"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	MessageCount    pgtype.Int4        `json:"message_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ExternalSyncLog struct {
	ID             pgtype.UUID        `json:"id"`
	SyncStateID    pgtype.UUID        `json:"sync_state_id"`
	Source         string             `json:"source"`
	AccountID      pgtype.Text        `json:"account_id"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	Status         string             `json:"status"`
	ItemsProcessed pgtype.Int4        `json:"items_processed"`
	ItemsMatched   pgtype.Int4        `json:"items_matched"`
	ItemsCreated   pgtype.Int4        `json:"items_created"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ExternalSyncState struct {
	ID                   pgtype.UUID        `json:"id"`
	Source               string             `json:"source"`
	AccountID            pgtype.Text        `json:"account_id"`
	Enabled              bool               `json:"enabled"`
	Status               string             `json:"status"`
	Strategy             string             `json:"strategy"`
	LastSyncAt           pgtype.Timestamptz `json:"last_sync_at"`
	LastSuccessfulSyncAt pgtype.Timestamptz `json:"last_successful_sync_at"`
	NextSyncAt           pgtype.Timestamptz `json:"next_sync_at"`
	SyncCursor           pgtype.Text        `json:"sync_cursor"`
	ErrorMessage         pgtype.Text        `json:"error_message"`
	ErrorCount           int32              `json:"error_count"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Interaction struct {
	ID              pgtype.UUID        `json:"id"`
	ContactID       pgtype.UUID        `json:"contact_id"`
	Type            string             `json:"type"`
	Description     pgtype.Text        `json:"description"`
	InteractionDate pgtype.Timestamptz `json:"interaction_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type InteractionEmbedding struct {
	InteractionID pgtype.UUID        `json:"interaction_id"`
	Embedding     pgvector.Vector    `json:"embedding"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Note struct {
	ID        pgtype.UUID        `json:"id"`
	ContactID pgtype.UUID        `json:"contact_id"`
	Body      string             `json:"body"`
	Category  pgtype.Text        `json:"category"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type NoteEmbedding struct {
	NoteID    pgtype.UUID        `json:"note_id"`
	Embedding pgvector.Vector    `json:"embedding"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OauthCredential struct {
	ID                    pgtype.UUID        `json:"id"`
	Provider              string             `json:"provider"`
	AccountID             string             `json:"account_id"`
	AccountName           pgtype.Text        `json:"account_name"`
	AccessTokenEncrypted  []byte             `json:"access_token_encrypted"`
	RefreshTokenEncrypted []byte             `json:"refresh_token_encrypted"`
	EncryptionNonce       []byte             `json:"encryption_nonce"`
	TokenType             pgtype.Text        `json:"token_type"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	Scopes                []string           `json:"scopes"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type PromptQuery struct {
	ID          pgtype.UUID        `json:"id"`
	Query       string             `json:"query"`
	Response    string             `json:"response"`
	ContextUsed []byte             `json:"context_used"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Reminder struct {
	ID          pgtype.UUID        `json:"id"`
	ContactID   pgtype.UUID        `json:"contact_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	Completed   pgtype.Bool        `json:"completed"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	Source      pgtype.Text        `json:"source"`
}

type Tag struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Color     pgtype.Text        `json:"color"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TimeEntry struct {
	ID              pgtype.UUID        `json:"id"`
	Description     string             `json:"description"`
	Project         pgtype.Text        `json:"project"`
	ContactID       pgtype.UUID        `json:"contact_id"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	DurationMinutes pgtype.Int4        `json:"duration_minutes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
