// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: note.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountContactNotes = `-- name: CountContactNotes :one
SELECT COUNT(*) FROM note WHERE contact_id = $1
`

func (q *Queries) CountContactNotes(ctx context.Context, contactID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, CountContactNotes, contactID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateNote = `-- name: CreateNote :one
INSERT INTO note (contact_id, body, category) 
VALUES ($1, $2, $3) 
RETURNING id, contact_id, body, category, created_at, updated_at
`

type CreateNoteParams struct {
	ContactID pgtype.UUID `json:"contact_id"`
	Body      string      `json:"body"`
	Category  pgtype.Text `json:"category"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (*Note, error) {
	row := q.db.QueryRow(ctx, CreateNote, arg.ContactID, arg.Body, arg.Category)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Body,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const CreateNoteWithTimestamp = `-- name: CreateNoteWithTimestamp :one
INSERT INTO note (contact_id, body, category, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, contact_id, body, category, created_at, updated_at
`

type CreateNoteWithTimestampParams struct {
	ContactID pgtype.UUID        `json:"contact_id"`
	Body      string             `json:"body"`
	Category  pgtype.Text        `json:"category"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Create a note with a specific created_at timestamp (for migrations)
func (q *Queries) CreateNoteWithTimestamp(ctx context.Context, arg CreateNoteWithTimestampParams) (*Note, error) {
	row := q.db.QueryRow(ctx, CreateNoteWithTimestamp,
		arg.ContactID,
		arg.Body,
		arg.Category,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Body,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const DeleteContactNoteByCategory = `-- name: DeleteContactNoteByCategory :exec
DELETE FROM note
WHERE contact_id = $1 AND category = $2
`

type DeleteContactNoteByCategoryParams struct {
	ContactID pgtype.UUID `json:"contact_id"`
	Category  pgtype.Text `json:"category"`
}

// Delete a note for a contact by category
func (q *Queries) DeleteContactNoteByCategory(ctx context.Context, arg DeleteContactNoteByCategoryParams) error {
	_, err := q.db.Exec(ctx, DeleteContactNoteByCategory, arg.ContactID, arg.Category)
	return err
}

const DeleteNote = `-- name: DeleteNote :exec
DELETE FROM note WHERE id = $1
`

func (q *Queries) DeleteNote(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, DeleteNote, id)
	return err
}

const GetContactNoteByCategory = `-- name: GetContactNoteByCategory :one
SELECT id, contact_id, body, category, created_at, updated_at FROM note
WHERE contact_id = $1 AND category = $2
`

type GetContactNoteByCategoryParams struct {
	ContactID pgtype.UUID `json:"contact_id"`
	Category  pgtype.Text `json:"category"`
}

// Get a single note for a contact by category (e.g., 'notepad')
func (q *Queries) GetContactNoteByCategory(ctx context.Context, arg GetContactNoteByCategoryParams) (*Note, error) {
	row := q.db.QueryRow(ctx, GetContactNoteByCategory, arg.ContactID, arg.Category)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Body,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const GetNote = `-- name: GetNote :one

SELECT id, contact_id, body, category, created_at, updated_at FROM note WHERE id = $1
`

// Note queries
func (q *Queries) GetNote(ctx context.Context, id pgtype.UUID) (*Note, error) {
	row := q.db.QueryRow(ctx, GetNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Body,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const ListContactNotes = `-- name: ListContactNotes :many
SELECT id, contact_id, body, category, created_at, updated_at FROM note 
WHERE contact_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListContactNotesParams struct {
	ContactID pgtype.UUID `json:"contact_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListContactNotes(ctx context.Context, arg ListContactNotesParams) ([]*Note, error) {
	rows, err := q.db.Query(ctx, ListContactNotes, arg.ContactID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Body,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchNotes = `-- name: SearchNotes :many
SELECT id, contact_id, body, category, created_at, updated_at FROM note
WHERE to_tsvector('english', body) @@ plainto_tsquery('english', $1)
ORDER BY ts_rank(
  to_tsvector('english', body),
  plainto_tsquery('english', $1)
) DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type SearchNotesParams struct {
	PlaintoTsquery string `json:"plainto_tsquery"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) SearchNotes(ctx context.Context, arg SearchNotesParams) ([]*Note, error) {
	rows, err := q.db.Query(ctx, SearchNotes, arg.PlaintoTsquery, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Body,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateNote = `-- name: UpdateNote :one
UPDATE note SET
  body = $2,
  category = $3,
  updated_at = NOW()
WHERE id = $1
RETURNING id, contact_id, body, category, created_at, updated_at
`

type UpdateNoteParams struct {
	ID       pgtype.UUID `json:"id"`
	Body     string      `json:"body"`
	Category pgtype.Text `json:"category"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (*Note, error) {
	row := q.db.QueryRow(ctx, UpdateNote, arg.ID, arg.Body, arg.Category)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Body,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const UpsertContactNoteByCategory = `-- name: UpsertContactNoteByCategory :one
INSERT INTO note (contact_id, body, category)
VALUES ($1, $2, $3)
ON CONFLICT (contact_id) WHERE category = 'notepad'
DO UPDATE SET body = EXCLUDED.body, updated_at = NOW()
RETURNING id, contact_id, body, category, created_at, updated_at
`

type UpsertContactNoteByCategoryParams struct {
	ContactID pgtype.UUID `json:"contact_id"`
	Body      string      `json:"body"`
	Category  pgtype.Text `json:"category"`
}

// Insert or update a note for a contact by category (atomic operation for concurrent safety)
// Note: This uses the unique index on (contact_id) WHERE category = 'notepad'
func (q *Queries) UpsertContactNoteByCategory(ctx context.Context, arg UpsertContactNoteByCategoryParams) (*Note, error) {
	row := q.db.QueryRow(ctx, UpsertContactNoteByCategory, arg.ContactID, arg.Body, arg.Category)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Body,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
