// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddContactTag(ctx context.Context, arg AddContactTagParams) error
	BulkLinkIdentitiesToContact(ctx context.Context, arg BulkLinkIdentitiesToContactParams) error
	// Mark all pending follow-up tasks as completed for a contact (when a response arrives)
	CompleteFollowUpForContact(ctx context.Context, contactID pgtype.UUID) ([]*ContactTask, error)
	CompleteSyncLog(ctx context.Context, arg CompleteSyncLogParams) (*ExternalSyncLog, error)
	CountAllUnmatchedExternalContacts(ctx context.Context) (int64, error)
	CountContactInteractions(ctx context.Context, contactID pgtype.UUID) (int64, error)
	CountContactNotes(ctx context.Context, contactID pgtype.UUID) (int64, error)
	CountContactTasksByProvider(ctx context.Context, arg CountContactTasksByProviderParams) (int64, error)
	CountContacts(ctx context.Context, arg CountContactsParams) (int64, error)
	CountContactsByNamePrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error)
	// Count events for a specific contact
	CountEventsForContact(ctx context.Context, contactID pgtype.UUID) (int64, error)
	CountExternalContactsByDisplayNamePrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error)
	CountIdentitiesBySource(ctx context.Context, source string) (int64, error)
	// Count calendar events involving a contact (for merge preview)
	CountMergeCalendarEvents(ctx context.Context, dollar_1 pgtype.UUID) (int64, error)
	// Count contact methods for a contact (for merge preview)
	CountMergeContactMethods(ctx context.Context, contactID pgtype.UUID) (int64, error)
	// Count interactions for a contact (for merge preview)
	CountMergeInteractions(ctx context.Context, contactID pgtype.UUID) (int64, error)
	// Count notes for a contact (for merge preview)
	CountMergeNotes(ctx context.Context, contactID pgtype.UUID) (int64, error)
	// Count OAuth credentials for a provider
	CountOAuthCredentials(ctx context.Context, provider string) (int64, error)
	CountSearchContacts(ctx context.Context, arg CountSearchContactsParams) (int64, error)
	CountSyncLogsByState(ctx context.Context, syncStateID pgtype.UUID) (int64, error)
	CountUnmatchedExternalContacts(ctx context.Context, source string) (int64, error)
	CountUnmatchedIdentities(ctx context.Context) (int64, error)
	CreateContact(ctx context.Context, arg CreateContactParams) (*Contact, error)
	CreateContactMethod(ctx context.Context, arg CreateContactMethodParams) (*ContactMethod, error)
	CreateContactTask(ctx context.Context, arg CreateContactTaskParams) (*ContactTask, error)
	CreateEnrichment(ctx context.Context, arg CreateEnrichmentParams) (*ContactEnrichment, error)
	CreateInteraction(ctx context.Context, arg CreateInteractionParams) (*Interaction, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) (*Note, error)
	// Create a note with a specific created_at timestamp (for migrations)
	CreateNoteWithTimestamp(ctx context.Context, arg CreateNoteWithTimestampParams) (*Note, error)
	// External Sync Log Queries
	CreateSyncLog(ctx context.Context, arg CreateSyncLogParams) (*ExternalSyncLog, error)
	CreateSyncState(ctx context.Context, arg CreateSyncStateParams) (*ExternalSyncState, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (*Tag, error)
	// Remove duplicate contact IDs that may result from merge
	// Uses subquery with DISTINCT to rebuild the array without duplicates
	DeduplicateCalendarEventContacts(ctx context.Context, targetContactID pgtype.UUID) error
	DeleteCalendarEventsByGcalEventIdPrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error)
	DeleteCalendarEventsByTitlePrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error)
	DeleteContactMethodsByContact(ctx context.Context, contactID pgtype.UUID) error
	// Delete a note for a contact by category
	DeleteContactNoteByCategory(ctx context.Context, arg DeleteContactNoteByCategoryParams) error
	DeleteContactTask(ctx context.Context, id pgtype.UUID) error
	// Delete task link for a contact+provider+kind (e.g., when cadence is disabled)
	DeleteContactTaskByContact(ctx context.Context, arg DeleteContactTaskByContactParams) error
	// Delete all tasks for a provider (e.g., when disconnecting Todoist)
	DeleteContactTasksByProvider(ctx context.Context, provider string) error
	// Test data management queries
	// These queries are used by the test API endpoints to seed and cleanup test data
	DeleteContactsByNamePrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error)
	// Delete connections that would become duplicates after merge
	// (connections between source and target, or connections that now point same way)
	DeleteDuplicateConnections(ctx context.Context, arg DeleteDuplicateConnectionsParams) error
	// Delete contact methods from source that already exist in target (by normalized value and type)
	DeleteDuplicateContactMethods(ctx context.Context, arg DeleteDuplicateContactMethodsParams) error
	// Delete source's connections (as contact_a) where target already connects to the same contact_b
	// Prevents duplicate (target, X) rows after transfer
	DeleteDuplicateThirdPartyConnectionsA(ctx context.Context, arg DeleteDuplicateThirdPartyConnectionsAParams) error
	// Delete source's connections (as contact_b) where target already connects to the same contact_a
	// Prevents duplicate (X, target) rows after transfer
	DeleteDuplicateThirdPartyConnectionsB(ctx context.Context, arg DeleteDuplicateThirdPartyConnectionsBParams) error
	DeleteEnrichment(ctx context.Context, id pgtype.UUID) error
	DeleteEnrichmentsForContact(ctx context.Context, contactID pgtype.UUID) error
	// Delete all events for a Google account (used when revoking access)
	DeleteEventsByAccount(ctx context.Context, googleAccountID string) error
	DeleteExternalContact(ctx context.Context, id pgtype.UUID) error
	DeleteExternalContactsByDisplayNamePrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error)
	DeleteExternalContactsBySourceAccount(ctx context.Context, arg DeleteExternalContactsBySourceAccountParams) error
	DeleteExternalContactsBySourceIDPrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error)
	DeleteIdentitiesForContact(ctx context.Context, contactID pgtype.UUID) error
	DeleteIdentity(ctx context.Context, id pgtype.UUID) error
	DeleteNote(ctx context.Context, id pgtype.UUID) error
	// Delete an OAuth credential by ID
	DeleteOAuthCredential(ctx context.Context, id pgtype.UUID) error
	// Delete all OAuth credentials for a provider
	DeleteOAuthCredentialByProvider(ctx context.Context, provider string) error
	DeleteOldSyncLogs(ctx context.Context, createdAt pgtype.Timestamptz) error
	DeleteSyncState(ctx context.Context, id pgtype.UUID) error
	DeleteSyncStatesByAccountID(ctx context.Context, accountID pgtype.Text) error
	DeleteTag(ctx context.Context, id pgtype.UUID) error
	// Demote source's primary contact methods when target already has a primary for that type
	// This prevents violation of the unique partial index on (contact_id, type) WHERE is_primary = true
	DemoteSourcePrimaryMethods(ctx context.Context, arg DemoteSourcePrimaryMethodsParams) error
	// Find contact methods that exist in both source and target
	// Used to identify duplicates that will be skipped during merge
	FindDuplicateContactMethods(ctx context.Context, arg FindDuplicateContactMethodsParams) ([]*FindDuplicateContactMethodsRow, error)
	FindExternalContactsByEmail(ctx context.Context, dollar_1 []byte) ([]*ExternalContact, error)
	FindExternalContactsByNormalizedEmail(ctx context.Context, lower string) ([]*ExternalContact, error)
	FindIdentitiesByIdentifier(ctx context.Context, arg FindIdentitiesByIdentifierParams) ([]*ExternalIdentity, error)
	// Find an existing interaction by contact, source, and source_ref (for deduplication)
	FindInteractionBySourceRef(ctx context.Context, arg FindInteractionBySourceRefParams) (*Interaction, error)
	// Find an existing manual interaction within a time window (for manual deduplication)
	FindInteractionInWindow(ctx context.Context, arg FindInteractionInWindowParams) (*Interaction, error)
	FindMethodsByNormalizedValue(ctx context.Context, arg FindMethodsByNormalizedValueParams) ([]*FindMethodsByNormalizedValueRow, error)
	// Find a pending follow-up task for a contact (kind='follow_up', state='managed')
	FindPendingFollowUp(ctx context.Context, contactID pgtype.UUID) (*ContactTask, error)
	FindSimilarContacts(ctx context.Context, arg FindSimilarContactsParams) ([]*FindSimilarContactsRow, error)
	// Finds similar contacts for multiple candidate names in a single batch query.
	// Uses UNNEST to expand input arrays and LATERAL join to find matches per candidate.
	// Returns results grouped by candidate_id with matches ordered by similarity.
	FindSimilarContactsBatch(ctx context.Context, arg FindSimilarContactsBatchParams) ([]*FindSimilarContactsBatchRow, error)
	// Look up an event by its Google Calendar ID
	GetCalendarEventByGcalID(ctx context.Context, arg GetCalendarEventByGcalIDParams) (*CalendarEvent, error)
	// Look up an event by its UUID
	GetCalendarEventByID(ctx context.Context, id pgtype.UUID) (*CalendarEvent, error)
	// Contact queries
	GetContact(ctx context.Context, id pgtype.UUID) (*Contact, error)
	// Get a single note for a contact by category (e.g., 'notepad')
	GetContactNoteByCategory(ctx context.Context, arg GetContactNoteByCategoryParams) (*Note, error)
	GetContactTags(ctx context.Context, contactID pgtype.UUID) ([]*Tag, error)
	// Contact Task Queries (for Todoist cadence sync)
	GetContactTask(ctx context.Context, id pgtype.UUID) (*ContactTask, error)
	// Get the task for a specific contact+provider+kind combination
	GetContactTaskByContact(ctx context.Context, arg GetContactTaskByContactParams) (*ContactTask, error)
	// Look up a task by its external provider ID
	GetContactTaskByExternalID(ctx context.Context, arg GetContactTaskByExternalIDParams) (*ContactTask, error)
	// Find a task by its pending temp ID in metadata (for mapping temp IDs to real Todoist IDs)
	GetContactTaskByPendingTempID(ctx context.Context, arg GetContactTaskByPendingTempIDParams) (*ContactTask, error)
	GetEnrichmentByField(ctx context.Context, arg GetEnrichmentByFieldParams) (*ContactEnrichment, error)
	// Contact Enrichment queries
	GetEnrichmentsForContact(ctx context.Context, contactID pgtype.UUID) ([]*ContactEnrichment, error)
	// External Contact queries
	GetExternalContact(ctx context.Context, id pgtype.UUID) (*ExternalContact, error)
	GetExternalContactBySource(ctx context.Context, arg GetExternalContactBySourceParams) (*ExternalContact, error)
	// External identity queries for cross-platform contact identity matching
	GetIdentityByID(ctx context.Context, id pgtype.UUID) (*ExternalIdentity, error)
	GetIdentityByIdentifier(ctx context.Context, arg GetIdentityByIdentifierParams) (*ExternalIdentity, error)
	// Interaction queries
	GetInteraction(ctx context.Context, id pgtype.UUID) (*Interaction, error)
	// Note queries
	GetNote(ctx context.Context, id pgtype.UUID) (*Note, error)
	// OAuth Credential Queries
	// Get a specific OAuth credential by provider and account ID
	GetOAuthCredential(ctx context.Context, arg GetOAuthCredentialParams) (*OauthCredential, error)
	// Get a specific OAuth credential by UUID
	GetOAuthCredentialByID(ctx context.Context, id pgtype.UUID) (*OauthCredential, error)
	// Get non-sensitive credential info for display
	GetOAuthCredentialStatus(ctx context.Context, id pgtype.UUID) (*GetOAuthCredentialStatusRow, error)
	GetSyncLog(ctx context.Context, id pgtype.UUID) (*ExternalSyncLog, error)
	// External Sync State Queries
	GetSyncState(ctx context.Context, id pgtype.UUID) (*ExternalSyncState, error)
	GetSyncStateBySource(ctx context.Context, arg GetSyncStateBySourceParams) (*ExternalSyncState, error)
	// Tag queries
	GetTag(ctx context.Context, id pgtype.UUID) (*Tag, error)
	GetTagByName(ctx context.Context, name string) (*Tag, error)
	HardDeleteContact(ctx context.Context, id pgtype.UUID) error
	HasEnrichmentForField(ctx context.Context, arg HasEnrichmentForFieldParams) (bool, error)
	IgnoreExternalContact(ctx context.Context, id pgtype.UUID) error
	LinkIdentityToContact(ctx context.Context, arg LinkIdentityToContactParams) (*ExternalIdentity, error)
	// List all OAuth credentials
	ListAllOAuthCredentials(ctx context.Context) ([]*OauthCredential, error)
	ListAllUnmatchedExternalContacts(ctx context.Context, arg ListAllUnmatchedExternalContactsParams) ([]*ExternalContact, error)
	// Lightweight query returning only IDs for navigation
	ListContactIDs(ctx context.Context, arg ListContactIDsParams) ([]pgtype.UUID, error)
	// Lightweight query returning only IDs with sorting for navigation
	ListContactIDsSorted(ctx context.Context, arg ListContactIDsSortedParams) ([]pgtype.UUID, error)
	ListContactInteractions(ctx context.Context, arg ListContactInteractionsParams) ([]*Interaction, error)
	// Contact method queries
	ListContactMethodsByContact(ctx context.Context, contactID pgtype.UUID) ([]*ContactMethod, error)
	ListContactNotes(ctx context.Context, arg ListContactNotesParams) ([]*Note, error)
	// List all tasks for a contact
	ListContactTasksByContact(ctx context.Context, contactID pgtype.UUID) ([]*ContactTask, error)
	// List tasks for a contact with optional state and kind filters
	ListContactTasksByContactFiltered(ctx context.Context, arg ListContactTasksByContactFilteredParams) ([]*ContactTask, error)
	// List all tasks for a provider (optionally filtered by state)
	ListContactTasksByProvider(ctx context.Context, arg ListContactTasksByProviderParams) ([]*ContactTask, error)
	// cadence_filter: '' = no filter (Go zero value), 'has_cadence' = non-empty cadence,
	// 'no_cadence' = NULL or empty string (defensive; CHECK constraint prevents empty strings)
	// followup_filter: '' = no filter, 'has_followup' = pending follow-up exists, 'no_followup' = no pending follow-up
	ListContacts(ctx context.Context, arg ListContactsParams) ([]*Contact, error)
	ListContactsSorted(ctx context.Context, arg ListContactsSortedParams) ([]*Contact, error)
	// Lists contacts that have a cadence set (used for Todoist sync reconciliation).
	ListContactsWithCadence(ctx context.Context, limit int32) ([]*Contact, error)
	// Lists contacts that have a contact_by date set (used for testing mode filtering).
	// Returns contacts ordered by contact_by (soonest first).
	ListContactsWithContactBy(ctx context.Context, limit int32) ([]*Contact, error)
	ListDueSyncStates(ctx context.Context, nextSyncAt pgtype.Timestamptz) ([]*ExternalSyncState, error)
	ListEnabledSyncStates(ctx context.Context) ([]*ExternalSyncState, error)
	ListEnrichmentsBySource(ctx context.Context, arg ListEnrichmentsBySourceParams) ([]*ContactEnrichment, error)
	// List events by Google account within a date range
	ListEventsByAccountAndDateRange(ctx context.Context, arg ListEventsByAccountAndDateRangeParams) ([]*CalendarEvent, error)
	// List calendar events involving a specific contact
	ListEventsForContact(ctx context.Context, arg ListEventsForContactParams) ([]*CalendarEvent, error)
	ListExternalContactsBySource(ctx context.Context, arg ListExternalContactsBySourceParams) ([]*ExternalContact, error)
	ListExternalContactsForCRMContact(ctx context.Context, crmContactID pgtype.UUID) ([]*ExternalContact, error)
	// Find completed follow-up tasks where the Todoist close call failed and needs retry
	ListFollowUpsWithPendingClose(ctx context.Context) ([]*ContactTask, error)
	ListIdentitiesBySource(ctx context.Context, arg ListIdentitiesBySourceParams) ([]*ExternalIdentity, error)
	ListIdentitiesForContact(ctx context.Context, contactID pgtype.UUID) ([]*ExternalIdentity, error)
	// List all managed tasks for a provider (for reconciliation)
	ListManagedContactTasks(ctx context.Context, provider string) ([]*ListManagedContactTasksRow, error)
	// List non-sensitive credential info for all credentials of a provider
	ListOAuthCredentialStatuses(ctx context.Context, provider string) ([]*ListOAuthCredentialStatusesRow, error)
	// List all OAuth credentials for a provider
	ListOAuthCredentials(ctx context.Context, provider string) ([]*OauthCredential, error)
	// Lists contacts whose contact_by date is before today (overdue).
	// Returns contacts ordered by how overdue they are (most overdue first).
	ListOverdueContacts(ctx context.Context, arg ListOverdueContactsParams) ([]*Contact, error)
	// List past events that haven't updated last_contacted yet
	ListPastEventsNeedingUpdate(ctx context.Context, arg ListPastEventsNeedingUpdateParams) ([]*CalendarEvent, error)
	ListRecentSyncLogs(ctx context.Context, limit int32) ([]*ExternalSyncLog, error)
	ListSyncLogsByState(ctx context.Context, arg ListSyncLogsByStateParams) ([]*ExternalSyncLog, error)
	ListSyncStates(ctx context.Context) ([]*ExternalSyncState, error)
	ListTags(ctx context.Context) ([]*Tag, error)
	ListUnmatchedExternalContacts(ctx context.Context, arg ListUnmatchedExternalContactsParams) ([]*ExternalContact, error)
	ListUnmatchedIdentities(ctx context.Context, arg ListUnmatchedIdentitiesParams) ([]*ExternalIdentity, error)
	// List upcoming calendar events for a specific contact
	ListUpcomingEventsForContact(ctx context.Context, arg ListUpcomingEventsForContactParams) ([]*CalendarEvent, error)
	// List upcoming events that have matched CRM contacts
	ListUpcomingEventsWithContacts(ctx context.Context, arg ListUpcomingEventsWithContactsParams) ([]*CalendarEvent, error)
	// Mark an event as having updated last_contacted for its contacts
	MarkLastContactedUpdated(ctx context.Context, id pgtype.UUID) error
	RemoveContactTag(ctx context.Context, arg RemoveContactTagParams) error
	// Replace source contact ID with target contact ID in calendar event matched_contact_ids array
	// Uses array_replace for efficient in-place replacement
	ReplaceContactInCalendarEvents(ctx context.Context, arg ReplaceContactInCalendarEventsParams) error
	// Lightweight query returning only IDs with search for navigation
	SearchContactIDs(ctx context.Context, arg SearchContactIDsParams) ([]pgtype.UUID, error)
	// Lightweight query returning only IDs with search and sorting for navigation
	SearchContactIDsSorted(ctx context.Context, arg SearchContactIDsSortedParams) ([]pgtype.UUID, error)
	SearchContacts(ctx context.Context, arg SearchContactsParams) ([]*Contact, error)
	SearchContactsSorted(ctx context.Context, arg SearchContactsSortedParams) ([]*Contact, error)
	SearchNotes(ctx context.Context, arg SearchNotesParams) ([]*Note, error)
	SetContactMethodPrimary(ctx context.Context, arg SetContactMethodPrimaryParams) error
	SoftDeleteContact(ctx context.Context, id pgtype.UUID) error
	SoftDeleteInteraction(ctx context.Context, id pgtype.UUID) error
	// Transfer connections where source is contact_a to use target instead
	// This handles the bidirectional relationship table
	TransferConnectionsAsContactA(ctx context.Context, arg TransferConnectionsAsContactAParams) error
	// Transfer connections where source is contact_b to use target instead
	TransferConnectionsAsContactB(ctx context.Context, arg TransferConnectionsAsContactBParams) error
	// Contact merge queries
	// These queries support merging one contact (source) into another (target)
	// Transfer contact methods from source to target contact
	TransferContactMethods(ctx context.Context, arg TransferContactMethodsParams) error
	// Transfer interactions from source to target contact (includes soft-deleted for audit trail)
	TransferInteractions(ctx context.Context, arg TransferInteractionsParams) error
	// Transfer notes from source to target contact
	TransferNotes(ctx context.Context, arg TransferNotesParams) error
	UnlinkIdentityFromContact(ctx context.Context, id pgtype.UUID) (*ExternalIdentity, error)
	UpdateContact(ctx context.Context, arg UpdateContactParams) (*Contact, error)
	// Updates just the contact_by field (for Todoist deadline sync).
	UpdateContactBy(ctx context.Context, arg UpdateContactByParams) error
	// Updates last_contacted, contact_by, and all direction timestamp fields (for mutual interactions)
	UpdateContactLastContacted(ctx context.Context, arg UpdateContactLastContactedParams) error
	// Updates last_contacted and contact_by only if the new date is later.
	// Also updates direction timestamp fields (this path is used by gcal, which is always mutual).
	// contact_by is recalculated from the new last_contacted date using the contact's existing cadence.
	// Cadence day mappings: weekly=7, biweekly=14, monthly=30, quarterly=90, biannual=180, annual=365
	UpdateContactLastContactedIfLater(ctx context.Context, arg UpdateContactLastContactedIfLaterParams) error
	UpdateContactMethodValue(ctx context.Context, arg UpdateContactMethodValueParams) (*ContactMethod, error)
	// Updates all direction fields + last_contacted + contact_by (for mutual interactions).
	// Uses forward-only semantics for automated sources; manual always updates.
	UpdateContactMutualFields(ctx context.Context, arg UpdateContactMutualFieldsParams) error
	// Updates only last_outreach_at (for outbound-only interactions).
	// Uses forward-only semantics: only updates if the new time is later.
	UpdateContactOutreachAt(ctx context.Context, arg UpdateContactOutreachAtParams) error
	// Updates last_contacted, last_interaction_at, last_response_at, and contact_by (for inbound interactions).
	// Uses forward-only semantics for automated sources; manual always updates.
	UpdateContactResponseFields(ctx context.Context, arg UpdateContactResponseFieldsParams) error
	// Update the external task ID (when creating a new Todoist task)
	UpdateContactTaskExternalID(ctx context.Context, arg UpdateContactTaskExternalIDParams) (*ContactTask, error)
	UpdateContactTaskMetadata(ctx context.Context, arg UpdateContactTaskMetadataParams) (*ContactTask, error)
	UpdateContactTaskState(ctx context.Context, arg UpdateContactTaskStateParams) (*ContactTask, error)
	UpdateExternalContactDuplicate(ctx context.Context, arg UpdateExternalContactDuplicateParams) error
	UpdateExternalContactMatch(ctx context.Context, arg UpdateExternalContactMatchParams) (*ExternalContact, error)
	UpdateIdentityMessageCount(ctx context.Context, arg UpdateIdentityMessageCountParams) (*ExternalIdentity, error)
	// Promote an outbound interaction to mutual when a reply arrives (in-place update)
	UpdateInteractionDirection(ctx context.Context, arg UpdateInteractionDirectionParams) (*Interaction, error)
	// Update the matched contact IDs for an event
	UpdateMatchedContacts(ctx context.Context, arg UpdateMatchedContactsParams) (*CalendarEvent, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (*Note, error)
	// Update only the token data (for token refresh)
	UpdateOAuthCredentialTokens(ctx context.Context, arg UpdateOAuthCredentialTokensParams) (*OauthCredential, error)
	UpdateSyncStateCursor(ctx context.Context, arg UpdateSyncStateCursorParams) error
	UpdateSyncStateEnabled(ctx context.Context, arg UpdateSyncStateEnabledParams) (*ExternalSyncState, error)
	UpdateSyncStateMetadata(ctx context.Context, arg UpdateSyncStateMetadataParams) (*ExternalSyncState, error)
	UpdateSyncStateNextSync(ctx context.Context, arg UpdateSyncStateNextSyncParams) error
	UpdateSyncStateStatus(ctx context.Context, arg UpdateSyncStateStatusParams) (*ExternalSyncState, error)
	UpdateSyncStateSuccess(ctx context.Context, arg UpdateSyncStateSuccessParams) (*ExternalSyncState, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (*Tag, error)
	// Insert or update a calendar event from Google Calendar
	// Note: last_contacted_updated is reset when matched_contact_ids changes (order-insensitive)
	// so newly matched contacts can be processed. Otherwise we preserve the processed state
	// to avoid duplicates.
	UpsertCalendarEvent(ctx context.Context, arg UpsertCalendarEventParams) (*CalendarEvent, error)
	// Insert or update a note for a contact by category (atomic operation for concurrent safety)
	// Note: This uses the unique index on (contact_id) WHERE category = 'notepad'
	UpsertContactNoteByCategory(ctx context.Context, arg UpsertContactNoteByCategoryParams) (*Note, error)
	// Upsert a contact task by external_task_id (Todoist task IDs are globally unique)
	UpsertContactTask(ctx context.Context, arg UpsertContactTaskParams) (*ContactTask, error)
	UpsertExternalContact(ctx context.Context, arg UpsertExternalContactParams) (*ExternalContact, error)
	UpsertIdentity(ctx context.Context, arg UpsertIdentityParams) (*ExternalIdentity, error)
	// Insert or update an OAuth credential
	UpsertOAuthCredential(ctx context.Context, arg UpsertOAuthCredentialParams) (*OauthCredential, error)
}

var _ Querier = (*Queries)(nil)
