// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tag.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const AddContactTag = `-- name: AddContactTag :exec
INSERT INTO contact_tag (contact_id, tag_id) VALUES ($1, $2)
ON CONFLICT (contact_id, tag_id) DO NOTHING
`

type AddContactTagParams struct {
	ContactID uuid.UUID `json:"contact_id"`
	TagID     uuid.UUID `json:"tag_id"`
}

func (q *Queries) AddContactTag(ctx context.Context, arg AddContactTagParams) error {
	_, err := q.db.Exec(ctx, AddContactTag, arg.ContactID, arg.TagID)
	return err
}

const CountContactTagsWithDeletedContact = `-- name: CountContactTagsWithDeletedContact :one
SELECT COUNT(*)
FROM contact_tag ct
JOIN contact c ON c.id = ct.contact_id
WHERE c.deleted_at IS NOT NULL
`

// CountContactTagsWithDeletedContact counts the contact_tag rows the migration
// SKIPS because their contact is soft-deleted, so the `--migrate-tags` summary can
// report the skip explicitly and the operator isn't misled when the migrated
// count doesn't match the raw contact_tag table.
func (q *Queries) CountContactTagsWithDeletedContact(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountContactTagsWithDeletedContact)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateTag = `-- name: CreateTag :one
INSERT INTO tag (name, color) VALUES ($1, $2) RETURNING id, name, color, created_at
`

type CreateTagParams struct {
	Name  string  `json:"name"`
	Color *string `json:"color"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (*Tag, error) {
	row := q.db.QueryRow(ctx, CreateTag, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return &i, err
}

const DeleteTag = `-- name: DeleteTag :exec
DELETE FROM tag WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteTag, id)
	return err
}

const GetContactTags = `-- name: GetContactTags :many
SELECT t.id, t.name, t.color, t.created_at FROM tag t
JOIN contact_tag ct ON ct.tag_id = t.id
WHERE ct.contact_id = $1
ORDER BY t.name ASC
`

func (q *Queries) GetContactTags(ctx context.Context, contactID uuid.UUID) ([]*Tag, error) {
	rows, err := q.db.Query(ctx, GetContactTags, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTag = `-- name: GetTag :one

SELECT id, name, color, created_at FROM tag WHERE id = $1
`

// Tag queries
func (q *Queries) GetTag(ctx context.Context, id uuid.UUID) (*Tag, error) {
	row := q.db.QueryRow(ctx, GetTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return &i, err
}

const GetTagByName = `-- name: GetTagByName :one
SELECT id, name, color, created_at FROM tag WHERE name = $1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (*Tag, error) {
	row := q.db.QueryRow(ctx, GetTagByName, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return &i, err
}

const ListContactTagsWithLiveContact = `-- name: ListContactTagsWithLiveContact :many
SELECT ct.contact_id, ct.tag_id, ct.created_at
FROM contact_tag ct
JOIN live_contact c ON c.id = ct.contact_id
ORDER BY ct.contact_id ASC, ct.tag_id ASC
`

// ListContactTagsWithLiveContact returns every contact_tag whose contact is NOT
// soft-deleted (the `crm-admin --migrate-tags` source set). Deleted contacts are
// skipped permanently — the assertion write path rejects a tombstoned subject
// node anyway. Ordered deterministically so the migration processes rows in a
// stable sequence.
func (q *Queries) ListContactTagsWithLiveContact(ctx context.Context) ([]*ContactTag, error) {
	rows, err := q.db.Query(ctx, ListContactTagsWithLiveContact)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ContactTag{}
	for rows.Next() {
		var i ContactTag
		if err := rows.Scan(&i.ContactID, &i.TagID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTags = `-- name: ListTags :many
SELECT id, name, color, created_at FROM tag ORDER BY name ASC
`

func (q *Queries) ListTags(ctx context.Context) ([]*Tag, error) {
	rows, err := q.db.Query(ctx, ListTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RemoveContactTag = `-- name: RemoveContactTag :exec
DELETE FROM contact_tag 
WHERE contact_id = $1 AND tag_id = $2
`

type RemoveContactTagParams struct {
	ContactID uuid.UUID `json:"contact_id"`
	TagID     uuid.UUID `json:"tag_id"`
}

func (q *Queries) RemoveContactTag(ctx context.Context, arg RemoveContactTagParams) error {
	_, err := q.db.Exec(ctx, RemoveContactTag, arg.ContactID, arg.TagID)
	return err
}

const UpdateTag = `-- name: UpdateTag :one
UPDATE tag SET
  name = $2,
  color = $3
WHERE id = $1
RETURNING id, name, color, created_at
`

type UpdateTagParams struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Color *string   `json:"color"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (*Tag, error) {
	row := q.db.QueryRow(ctx, UpdateTag, arg.ID, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return &i, err
}
