// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: test.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountContactsByNamePrefix = `-- name: CountContactsByNamePrefix :one
SELECT COUNT(*) FROM contact WHERE full_name LIKE $1 || '%'
`

func (q *Queries) CountContactsByNamePrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, CountContactsByNamePrefix, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountExternalContactsByDisplayNamePrefix = `-- name: CountExternalContactsByDisplayNamePrefix :one
SELECT COUNT(*) FROM external_contact
WHERE display_name LIKE $1 || '%'
  AND deleted_at IS NULL
`

func (q *Queries) CountExternalContactsByDisplayNamePrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, CountExternalContactsByDisplayNamePrefix, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountInteractionsByIDContactAndSource = `-- name: CountInteractionsByIDContactAndSource :one
SELECT COUNT(*) FROM interaction
WHERE id = $1 AND contact_id = $2 AND source = $3
`

type CountInteractionsByIDContactAndSourceParams struct {
	ID        pgtype.UUID `json:"id"`
	ContactID pgtype.UUID `json:"contact_id"`
	Source    string      `json:"source"`
}

// Test assertion — confirms exactly the expected interaction row exists
// for the (id, contact_id, source) tuple. Used by the raw_message
// end-to-end test to verify Stage 3 created the row the staging
// table's interaction_id points to.
func (q *Queries) CountInteractionsByIDContactAndSource(ctx context.Context, arg CountInteractionsByIDContactAndSourceParams) (int64, error) {
	row := q.db.QueryRow(ctx, CountInteractionsByIDContactAndSource, arg.ID, arg.ContactID, arg.Source)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountMessagesMessageByGuid = `-- name: CountMessagesMessageByGuid :one
SELECT COUNT(*) FROM messages_message WHERE guid = $1
`

// Test assertion — count rows with the given guid (typically 0 or 1
// under the partial unique index). Used by duplicate-detection tests.
func (q *Queries) CountMessagesMessageByGuid(ctx context.Context, guid string) (int64, error) {
	row := q.db.QueryRow(ctx, CountMessagesMessageByGuid, guid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountNonFinalRiverJobs = `-- name: CountNonFinalRiverJobs :one
SELECT COUNT(*) FROM river_job WHERE finalized_at IS NULL
`

// Additive-seed (crm-admin --seed) preflight: count queued/in-flight river_job
// rows (finalized_at IS NULL). An additive seed REFUSES if this is non-zero — it
// must not steal pre-existing queued work, and a drained queue is its
// precondition. (--reset-and-seed skips this — it WIPES river_job.) This is a
// queue-drain precondition, NOT a live-worker liveness claim (River 0.34 does not
// populate river_client, so no sound DB liveness signal exists).
func (q *Queries) CountNonFinalRiverJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, CountNonFinalRiverJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountRiverJobsByKind = `-- name: CountRiverJobsByKind :one
SELECT COUNT(*) FROM river_job WHERE kind = $1
`

// Test assertion — count ALL River jobs of the given kind (including
// finalized). When the test runs against a River client with active
// workers, jobs can be picked up and finalized between insert and
// assertion; counting by kind alone is timing-resilient. Cross-test
// pollution is bounded by DeleteRiverJobsByKindAny in test cleanup.
func (q *Queries) CountRiverJobsByKind(ctx context.Context, kind string) (int64, error) {
	row := q.db.QueryRow(ctx, CountRiverJobsByKind, kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountRiverJobsByKindUnfinalized = `-- name: CountRiverJobsByKindUnfinalized :one
SELECT COUNT(*) FROM river_job WHERE kind = $1 AND finalized_at IS NULL
`

// Test assertion — count unfinalized River jobs of the given kind.
// Used to verify ingest enqueues the expected number of aggregator
// jobs. River's own admin SQL is OK to query at the test boundary;
// production code never reads river_job directly.
func (q *Queries) CountRiverJobsByKindUnfinalized(ctx context.Context, kind string) (int64, error) {
	row := q.db.QueryRow(ctx, CountRiverJobsByKindUnfinalized, kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountRiverJobsBySourceArgForTest = `-- name: CountRiverJobsBySourceArgForTest :one
SELECT COUNT(*) FROM river_job
WHERE kind = 'sync_provider_account'
  AND (args->>'source') = $1::text
`

// Test-only count of sync_provider_account river_job rows whose args JSON
// source = @source. Used by sync-service tests to assert enqueue/dedup
// behavior without inlining raw SQL (core.md rule 2).
func (q *Queries) CountRiverJobsBySourceArgForTest(ctx context.Context, source string) (int64, error) {
	row := q.db.QueryRow(ctx, CountRiverJobsBySourceArgForTest, source)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const DeleteAllMacHosts = `-- name: DeleteAllMacHosts :execrows
DELETE FROM mac_host WHERE hostname NOT LIKE 'test-host-%'
`

// Test teardown — hard delete so the singleton index is empty for the
// next test. mac_host has no deleted_at column, so soft-delete is not
// an option.
//
// Excludes rows whose hostname starts with 'test-host-' (the
// messages_message_repository_test fixture prefix). Those rows are
// pre-revoked stand-ins used purely as FK targets by a parallel test
// package; wiping them mid-run breaks
// messages_message.mac_host_id FK inserts because Go runs test
// packages in parallel against the shared test DB.
func (q *Queries) DeleteAllMacHosts(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteAllMacHosts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteAllPairingTokens = `-- name: DeleteAllPairingTokens :execrows
DELETE FROM mac_host_pairing_token
`

func (q *Queries) DeleteAllPairingTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteAllPairingTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteCalendarEventsByGcalEventIdPrefix = `-- name: DeleteCalendarEventsByGcalEventIdPrefix :execrows
DELETE FROM calendar_event WHERE gcal_event_id LIKE $1 || '%'
`

func (q *Queries) DeleteCalendarEventsByGcalEventIdPrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteCalendarEventsByGcalEventIdPrefix, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteCalendarEventsByTitlePrefix = `-- name: DeleteCalendarEventsByTitlePrefix :execrows
DELETE FROM calendar_event WHERE title LIKE $1 || '%'
`

func (q *Queries) DeleteCalendarEventsByTitlePrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteCalendarEventsByTitlePrefix, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteContactsByNamePrefix = `-- name: DeleteContactsByNamePrefix :execrows

DELETE FROM contact WHERE full_name LIKE $1 || '%'
`

// Test data management queries
// These queries are used by the test API endpoints to seed and cleanup test data
func (q *Queries) DeleteContactsByNamePrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteContactsByNamePrefix, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteEventsBySource = `-- name: DeleteEventsBySource :execrows
DELETE FROM event WHERE source = $1
`

// Test teardown — drop event rows by source. Mirrors
// DeleteExternalIdentitiesBySource for the event log.
func (q *Queries) DeleteEventsBySource(ctx context.Context, source string) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteEventsBySource, source)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteExternalContactsByDisplayNamePrefix = `-- name: DeleteExternalContactsByDisplayNamePrefix :execrows
DELETE FROM external_contact WHERE display_name LIKE $1 || '%'
`

func (q *Queries) DeleteExternalContactsByDisplayNamePrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteExternalContactsByDisplayNamePrefix, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteExternalContactsBySourceForTest = `-- name: DeleteExternalContactsBySourceForTest :execrows
DELETE FROM external_contact WHERE source = $1
`

// Test teardown — hard-deletes ALL external_contact rows for a given
// source string. The known-IDs integration tests use this when they
// seed rows under a synthetic source value and need a targeted
// cleanup that ignores soft-delete state. Production code must never
// call this; it bypasses the tombstone contract and the
// crm_contact_id/match_status preservation rules.
func (q *Queries) DeleteExternalContactsBySourceForTest(ctx context.Context, source string) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteExternalContactsBySourceForTest, source)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteExternalContactsBySourceIDPrefix = `-- name: DeleteExternalContactsBySourceIDPrefix :execrows
DELETE FROM external_contact WHERE source_id LIKE $1 || '%'
`

func (q *Queries) DeleteExternalContactsBySourceIDPrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteExternalContactsBySourceIDPrefix, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteExternalIdentitiesBySource = `-- name: DeleteExternalIdentitiesBySource :execrows
DELETE FROM external_identity WHERE source = $1
`

// Test teardown — drop external_identity rows seeded by a test under
// a known source string (e.g., 'messages'). Used in raw_message ingest
// integration tests to ensure shared-DB cleanup is complete between
// runs.
func (q *Queries) DeleteExternalIdentitiesBySource(ctx context.Context, source string) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteExternalIdentitiesBySource, source)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteExternalIdentitiesBySourceID = `-- name: DeleteExternalIdentitiesBySourceID :execrows
DELETE FROM external_identity WHERE source_id = $1
`

func (q *Queries) DeleteExternalIdentitiesBySourceID(ctx context.Context, sourceID pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteExternalIdentitiesBySourceID, sourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteInteractionsByContactAndSource = `-- name: DeleteInteractionsByContactAndSource :execrows
DELETE FROM interaction WHERE contact_id = $1 AND source = $2
`

type DeleteInteractionsByContactAndSourceParams struct {
	ContactID pgtype.UUID `json:"contact_id"`
	Source    string      `json:"source"`
}

// Test teardown — drops interactions seeded by a test under the given
// (contact_id, source) pair. Scoped to the seeded contact so production
// data is never wiped.
func (q *Queries) DeleteInteractionsByContactAndSource(ctx context.Context, arg DeleteInteractionsByContactAndSourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteInteractionsByContactAndSource, arg.ContactID, arg.Source)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteRiverJobsByKindAny = `-- name: DeleteRiverJobsByKindAny :execrows
DELETE FROM river_job WHERE kind = ANY($1::text[])
`

// Test teardown — drop river_job rows whose kind is in the given
// array. Scoped to test-emitted kinds so we don't wipe production-
// shape rows on a shared DB. River doesn't expose a sqlc layer; this
// is the operator-test seam.
func (q *Queries) DeleteRiverJobsByKindAny(ctx context.Context, kinds []string) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteRiverJobsByKindAny, kinds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteRiverJobsBySourceArgForTest = `-- name: DeleteRiverJobsBySourceArgForTest :execrows
DELETE FROM river_job
WHERE kind = 'sync_provider_account'
  AND (args->>'source') = $1::text
`

// Test teardown only — hard-deletes sync_provider_account river_job rows
// whose args JSON source = @source. Mirrors the (source) JSONB path used
// by CountInFlightSyncJobs.
func (q *Queries) DeleteRiverJobsBySourceArgForTest(ctx context.Context, source string) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteRiverJobsBySourceArgForTest, source)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteSyncLogsBySourceForTest = `-- name: DeleteSyncLogsBySourceForTest :execrows
DELETE FROM external_sync_log WHERE source = $1
`

// Test teardown only — hard-deletes external_sync_log rows for a given
// source. external_sync_log carries its own source column (migration 011).
func (q *Queries) DeleteSyncLogsBySourceForTest(ctx context.Context, source string) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteSyncLogsBySourceForTest, source)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteSyncStatesBySourceForTest = `-- name: DeleteSyncStatesBySourceForTest :execrows
DELETE FROM external_sync_state WHERE source = $1
`

// Test teardown only — hard-deletes external_sync_state rows for a given
// source. Used by sync-service tests to scope per-source cleanup without
// inlining raw SQL into Go test code (core.md rule 2).
func (q *Queries) DeleteSyncStatesBySourceForTest(ctx context.Context, source string) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteSyncStatesBySourceForTest, source)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteTelegramMessagesByMessageIDs = `-- name: DeleteTelegramMessagesByMessageIDs :execrows
DELETE FROM telegram_message WHERE telegram_message_id = ANY($1::int[])
`

func (q *Queries) DeleteTelegramMessagesByMessageIDs(ctx context.Context, dollar_1 []int32) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteTelegramMessagesByMessageIDs, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteTelegramMessagesByPeerUserID = `-- name: DeleteTelegramMessagesByPeerUserID :execrows
DELETE FROM telegram_message WHERE peer_user_id = $1
`

func (q *Queries) DeleteTelegramMessagesByPeerUserID(ctx context.Context, peerUserID pgtype.Int8) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteTelegramMessagesByPeerUserID, peerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const GetInteractionSourceCheckDef = `-- name: GetInteractionSourceCheckDef :one
SELECT pg_get_constraintdef(c.oid)::text AS constraint_def
FROM pg_constraint c
WHERE c.conrelid = 'interaction'::regclass
  AND c.conname = 'interaction_source_check'
`

// Test assertion — returns the rendered definition of the
// interaction_source_check CHECK constraint via pg_get_constraintdef.
// Scoped by (conrelid, conname) because constraint names are NOT
// globally unique — scoping to the interaction relation avoids a future
// cross-table/-schema name collision. The descriptor-vs-CHECK agreement
// test parses the returned ARRAY[...] string literals to assert the
// live CHECK set equals the repository.InteractionSource* constants.
// Read-only catalog access; production code never calls this.
func (q *Queries) GetInteractionSourceCheckDef(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, GetInteractionSourceCheckDef)
	var constraint_def string
	err := row.Scan(&constraint_def)
	return constraint_def, err
}

const GetRiverJobStateByID = `-- name: GetRiverJobStateByID :one
SELECT state FROM river_job WHERE id = $1
`

// Test assertion — returns the river_job.state for a single job id. Used by
// rescue-on-crash polling to wait out River's async completer
// (running->completed lands after the worker returns). River exposes no
// production sqlc layer; this is the test-boundary seam, mirroring the
// existing CountRiverJobsByKind test query.
func (q *Queries) GetRiverJobStateByID(ctx context.Context, id int64) (RiverJobState, error) {
	row := q.db.QueryRow(ctx, GetRiverJobStateByID, id)
	var state RiverJobState
	err := row.Scan(&state)
	return state, err
}

const InsertRiverJobForTest = `-- name: InsertRiverJobForTest :exec
INSERT INTO river_job (
    args, kind, max_attempts, priority, queue, state,
    attempt, created_at, scheduled_at
) VALUES (
    $1, 'sync_provider_account', 3, 1, 'default', 'running',
    1, NOW(), NOW()
)
`

// Test-only seed of an in-flight sync_provider_account river_job row so
// the atomic-claim dedup path observes count>0. Mirrors the row a real
// enqueue would insert; the worker never runs in these tests.
func (q *Queries) InsertRiverJobForTest(ctx context.Context, args []byte) error {
	_, err := q.db.Exec(ctx, InsertRiverJobForTest, args)
	return err
}

const ResetSyntheticData = `-- name: ResetSyntheticData :exec

TRUNCATE TABLE
    calendar_event,
    comms_message,
    connection,
    contact,
    contact_enrichment,
    contact_method,
    contact_summary,
    contact_tag,
    contact_task,
    event,
    event_consumer_claim,
    external_contact,
    external_identity,
    external_sync_log,
    external_sync_state,
    interaction,
    mac_host,
    mac_host_pairing_token,
    meeting_note,
    messages_message,
    note,
    note_embedding,
    oauth_credential,
    phone_call,
    prompt_query,
    river_job,
    sync_staleness_breach,
    tag,
    telegram_channel_state,
    telegram_chat_config,
    telegram_message,
    telegram_session,
    telegram_update_state
RESTART IDENTITY CASCADE
`

// ============================================================================
// crm-admin --reset-and-seed support: a HARD wipe of every live data table
// so a staging instance can be reset to a known synthetic baseline. Preserves
// only schema_migrations (the migration ledger) + River's own internal tables
// (river_%); river_job IS wiped (stale jobs must not dereference wiped rows).
// The list is the NET-LIVE data-table set; a non-existent relation here aborts
// the TRUNCATE (so it must track the schema), and an omitted live data table is
// caught by the catalog guard in the reset integration test.
// ============================================================================
// HARD reset: truncate the complete live data-table closure in one statement.
// RESTART IDENTITY resets sequences; CASCADE is a no-op safety net because the
// list already names the full closure (it does NOT silently widen the wipe). Run
// ONLY by crm-admin --reset-and-seed (CRM_ENV != production, service stopped,
// --yes confirmed). The catalog guard in synthetic_reset_integration_test.go
// fails if a public table is added that is not in this list / schema_migrations /
// river_%.
func (q *Queries) ResetSyntheticData(ctx context.Context) error {
	_, err := q.db.Exec(ctx, ResetSyntheticData)
	return err
}

const SeedExternalSyncState = `-- name: SeedExternalSyncState :one
INSERT INTO external_sync_state
    (source, account_id, enabled, status, strategy, next_sync_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, source, account_id, enabled, status, strategy, last_sync_at, last_successful_sync_at, next_sync_at, sync_cursor, error_message, error_count, metadata, created_at, updated_at
`

type SeedExternalSyncStateParams struct {
	Source     string             `json:"source"`
	AccountID  pgtype.Text        `json:"account_id"`
	Enabled    bool               `json:"enabled"`
	Status     string             `json:"status"`
	Strategy   string             `json:"strategy"`
	NextSyncAt pgtype.Timestamptz `json:"next_sync_at"`
}

// Seeds an external_sync_state row at caller-supplied next_sync_at.
// Used by scheduler-exclusion tests to plant a push-strategy row whose
// next_sync_at is due, then assert ListDueAccounts skips it.
func (q *Queries) SeedExternalSyncState(ctx context.Context, arg SeedExternalSyncStateParams) (*ExternalSyncState, error) {
	row := q.db.QueryRow(ctx, SeedExternalSyncState,
		arg.Source,
		arg.AccountID,
		arg.Enabled,
		arg.Status,
		arg.Strategy,
		arg.NextSyncAt,
	)
	var i ExternalSyncState
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.AccountID,
		&i.Enabled,
		&i.Status,
		&i.Strategy,
		&i.LastSyncAt,
		&i.LastSuccessfulSyncAt,
		&i.NextSyncAt,
		&i.SyncCursor,
		&i.ErrorMessage,
		&i.ErrorCount,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const SeedMacHost = `-- name: SeedMacHost :one

INSERT INTO mac_host (hostname, daemon_version, protocol_version, api_key_hash)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type SeedMacHostParams struct {
	Hostname        string `json:"hostname"`
	DaemonVersion   string `json:"daemon_version"`
	ProtocolVersion int32  `json:"protocol_version"`
	ApiKeyHash      string `json:"api_key_hash"`
}

// Mac host test helpers — per .ai/rules/core.md rule 2 (no raw SQL in
// Go test fixtures), test setup uses these instead of pool.Exec.
// Inserts a host with caller-supplied hostname + bcrypted api_key_hash.
// Used by integration tests that need to bypass the pairing flow.
// RETURNING is the minimal id-only set so step-by-step migration tests
// that run this against earlier schemas (before columns added in later
// migrations exist) don't trip on the column expansion of RETURNING *.
func (q *Queries) SeedMacHost(ctx context.Context, arg SeedMacHostParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, SeedMacHost,
		arg.Hostname,
		arg.DaemonVersion,
		arg.ProtocolVersion,
		arg.ApiKeyHash,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const SeedPairingToken = `-- name: SeedPairingToken :one
INSERT INTO mac_host_pairing_token (token_hash, expires_at)
VALUES ($1, $2)
RETURNING id, token_hash, expires_at, consumed_at, consumed_host_id, created_at
`

type SeedPairingTokenParams struct {
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Inserts a pairing token with caller-supplied hash + expiry. Tests use
// this to seed expired tokens (cannot mint via the real Create path
// because the service enforces a forward-only TTL).
func (q *Queries) SeedPairingToken(ctx context.Context, arg SeedPairingTokenParams) (*MacHostPairingToken, error) {
	row := q.db.QueryRow(ctx, SeedPairingToken, arg.TokenHash, arg.ExpiresAt)
	var i MacHostPairingToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedHostID,
		&i.CreatedAt,
	)
	return &i, err
}

const SeedRevokedMacHost = `-- name: SeedRevokedMacHost :one
INSERT INTO mac_host (hostname, daemon_version, protocol_version, api_key_hash, api_key_revoked_at)
VALUES ($1, $2, $3, $4, NOW())
RETURNING id, hostname, daemon_version, protocol_version, last_heartbeat_at, permissions, source_health, cursor_epoch, api_key_hash, api_key_revoked_at, created_at, updated_at, api_key_rotated_at
`

type SeedRevokedMacHostParams struct {
	Hostname        string `json:"hostname"`
	DaemonVersion   string `json:"daemon_version"`
	ProtocolVersion int32  `json:"protocol_version"`
	ApiKeyHash      string `json:"api_key_hash"`
}

// Inserts a host that is already revoked (api_key_revoked_at = NOW()).
// Used by integration tests that only need a valid mac_host UUID as an
// FK target (e.g., messages_message.mac_host_id) and do NOT care about
// pairing or auth state. The singleton index idx_mac_host_singleton only
// applies to rows WHERE api_key_revoked_at IS NULL, so this helper can
// be called freely from parallel test packages without contending with
// the pairing-flow tests that hold the singleton slot.
func (q *Queries) SeedRevokedMacHost(ctx context.Context, arg SeedRevokedMacHostParams) (*MacHost, error) {
	row := q.db.QueryRow(ctx, SeedRevokedMacHost,
		arg.Hostname,
		arg.DaemonVersion,
		arg.ProtocolVersion,
		arg.ApiKeyHash,
	)
	var i MacHost
	err := row.Scan(
		&i.ID,
		&i.Hostname,
		&i.DaemonVersion,
		&i.ProtocolVersion,
		&i.LastHeartbeatAt,
		&i.Permissions,
		&i.SourceHealth,
		&i.CursorEpoch,
		&i.ApiKeyHash,
		&i.ApiKeyRevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApiKeyRotatedAt,
	)
	return &i, err
}

const SweepRiverJobsInCloneForTest = `-- name: SweepRiverJobsInCloneForTest :execrows
DELETE FROM river_job
WHERE current_database() LIKE 'personal\_crm\_test\_clone\_%' ESCAPE '\'
`

// Test setup — drop ALL river_job rows, but ONLY when connected to a
// per-package clone DB (current_database() matching the clone-name prefix).
// The rescue-on-crash test calls this to clear foreign-kind leftovers (e.g.
// interaction_recorder) created by earlier tests in the same per-package
// clone, which its live River client would otherwise fetch and churn on,
// widening the completer race. Fail-closed by construction: on a shared test
// DB or the dev DB the WHERE is false and it deletes nothing, so a manual
// no-tag run pointed at a real database can never wipe its queue. The prefix
// mirrors clonePrefix in internal/testdb (cannot import that build-tagged
// package from an untagged test file). EVERY underscore in the prefix is
// escaped so each is matched literally, not as a LIKE single-char wildcard —
// for a broad delete the guard must match the exact clone-name prefix, not a
// looser pattern.
func (q *Queries) SweepRiverJobsInCloneForTest(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, SweepRiverJobsInCloneForTest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SyntheticCountCalendarEventByGcalId = `-- name: SyntheticCountCalendarEventByGcalId :one
SELECT COUNT(*) FROM calendar_event
WHERE gcal_event_id = $1
`

// Settle Gate A (GCal decline terminal): count ALL calendar_event rows for the
// gcal id regardless of status/match. The cutover decline branch DELETES the
// row, so the decline test settles on this reaching 0. calendar_event has no
// deleted_at column (hard-delete table).
func (q *Queries) SyntheticCountCalendarEventByGcalId(ctx context.Context, gcalEventID string) (int64, error) {
	row := q.db.QueryRow(ctx, SyntheticCountCalendarEventByGcalId, gcalEventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const SyntheticCountContactMethodsByValueNormalizedPrefix = `-- name: SyntheticCountContactMethodsByValueNormalizedPrefix :one
SELECT COUNT(*) FROM contact_method cm
JOIN contact c ON c.id = cm.contact_id
WHERE cm.value_normalized LIKE $1 || '%'
  AND c.deleted_at IS NULL
`

// Harness setup collision detection (D5) — PRIMARY phone-band check. A seeded
// synthetic contact's phone lives ONLY as a contact_method (no external_identity
// until a later replay), and identity matching cross-matches via
// contact_method.value_normalized, so this is where the cross-namespace phone
// collision actually originates. Counts live (non-deleted-contact) contact_method
// rows whose normalized value shares the namespace's phone prefix. Caller passes
// a BARE prefix; '%' is appended here.
func (q *Queries) SyntheticCountContactMethodsByValueNormalizedPrefix(ctx context.Context, valueNormalizedPrefix pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, SyntheticCountContactMethodsByValueNormalizedPrefix, valueNormalizedPrefix)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const SyntheticCountContactsByIds = `-- name: SyntheticCountContactsByIds :one
SELECT COUNT(*) FROM contact WHERE id = ANY($1::uuid[])
`

// Cleanup assertion — count surviving contact rows for the given ids.
func (q *Queries) SyntheticCountContactsByIds(ctx context.Context, contactIds []pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, SyntheticCountContactsByIds, contactIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const SyntheticCountExternalIdentitiesByIdentifierPrefix = `-- name: SyntheticCountExternalIdentitiesByIdentifierPrefix :one
SELECT COUNT(*) FROM external_identity
WHERE identifier LIKE $1 || '%'
`

// Harness setup collision detection (D5): count external_identity rows whose
// normalized identifier shares the namespace's phone-digit prefix. Non-zero means
// another namespace already occupies this phone sub-block, so NewHarness re-salts.
// Caller passes a BARE prefix; '%' is appended here.
func (q *Queries) SyntheticCountExternalIdentitiesByIdentifierPrefix(ctx context.Context, identifierPrefix pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, SyntheticCountExternalIdentitiesByIdentifierPrefix, identifierPrefix)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const SyntheticCountLinkedCommsMessageByExternalId = `-- name: SyntheticCountLinkedCommsMessageByExternalId :one

SELECT COUNT(*) FROM comms_message
WHERE source = $1
  AND external_id = $2
  AND interaction_id IS NOT NULL
  AND deleted_at IS NULL
`

type SyntheticCountLinkedCommsMessageByExternalIdParams struct {
	Source     string `json:"source"`
	ExternalID string `json:"external_id"`
}

// Settle Gate A (seeded sender) — per-source-message linkage. Keyed on THIS
// replay's exact synthetic source id, so it is exact-to-this-replay (a prior
// same-contact interaction can't satisfy it early) AND idempotent (a re-replay
// of the same payload leaves the row linked, so the predicate stays true).
// gmail/gchat: the comms_message row for (source, external_id) has an
// interaction_id (the derived interaction landed).
func (q *Queries) SyntheticCountLinkedCommsMessageByExternalId(ctx context.Context, arg SyntheticCountLinkedCommsMessageByExternalIdParams) (int64, error) {
	row := q.db.QueryRow(ctx, SyntheticCountLinkedCommsMessageByExternalId, arg.Source, arg.ExternalID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const SyntheticCountLinkedMessagesMessageByGuid = `-- name: SyntheticCountLinkedMessagesMessageByGuid :one
SELECT COUNT(*) FROM messages_message
WHERE guid = $1
  AND interaction_id IS NOT NULL
  AND deleted_at IS NULL
`

// iMessage: the staging row for the guid has an interaction_id.
func (q *Queries) SyntheticCountLinkedMessagesMessageByGuid(ctx context.Context, guid string) (int64, error) {
	row := q.db.QueryRow(ctx, SyntheticCountLinkedMessagesMessageByGuid, guid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const SyntheticCountLinkedTelegramMessageByMessageId = `-- name: SyntheticCountLinkedTelegramMessageByMessageId :one
SELECT COUNT(*) FROM telegram_message
WHERE peer_user_id = $1
  AND telegram_message_id = $2
  AND interaction_id IS NOT NULL
  AND deleted_at IS NULL
`

type SyntheticCountLinkedTelegramMessageByMessageIdParams struct {
	PeerUserID        pgtype.Int8 `json:"peer_user_id"`
	TelegramMessageID int32       `json:"telegram_message_id"`
}

// telegram: the message row for (peer_user_id, telegram_message_id) has an
// interaction_id. Scoped by peer_user_id too — the peer band IS collision-checked
// at setup (resolveNamespace), whereas the message-id bucket is narrower and not
// checked; scoping by both means a colliding-message-id row in another namespace
// (necessarily a different peer band) can never satisfy this predicate early.
func (q *Queries) SyntheticCountLinkedTelegramMessageByMessageId(ctx context.Context, arg SyntheticCountLinkedTelegramMessageByMessageIdParams) (int64, error) {
	row := q.db.QueryRow(ctx, SyntheticCountLinkedTelegramMessageByMessageId, arg.PeerUserID, arg.TelegramMessageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const SyntheticCountMatchedExternalContactBySourceId = `-- name: SyntheticCountMatchedExternalContactBySourceId :one
SELECT COUNT(*) FROM external_contact
WHERE source_id = $1
  AND match_status = 'matched'
  AND crm_contact_id IS NOT NULL
  AND deleted_at IS NULL
`

// Settle Gate A (Mac-contact seeded): the external_contact row for the entity
// id exists linked to a CRM contact (match_status='matched').
func (q *Queries) SyntheticCountMatchedExternalContactBySourceId(ctx context.Context, sourceID string) (int64, error) {
	row := q.db.QueryRow(ctx, SyntheticCountMatchedExternalContactBySourceId, sourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const SyntheticCountProcessedCalendarEventByGcalId = `-- name: SyntheticCountProcessedCalendarEventByGcalId :one
SELECT COUNT(*) FROM calendar_event
WHERE gcal_event_id = $1
  AND $2::uuid = ANY(matched_contact_ids)
  AND last_contacted_updated = true
`

type SyntheticCountProcessedCalendarEventByGcalIdParams struct {
	GcalEventID string      `json:"gcal_event_id"`
	ContactID   pgtype.UUID `json:"contact_id"`
}

// gcal seeded: the calendar_event for the gcal id has the contact in
// matched_contact_ids AND last_contacted_updated=true (the attended interaction
// published). Idempotent: a re-replay leaves the row processed.
func (q *Queries) SyntheticCountProcessedCalendarEventByGcalId(ctx context.Context, arg SyntheticCountProcessedCalendarEventByGcalIdParams) (int64, error) {
	row := q.db.QueryRow(ctx, SyntheticCountProcessedCalendarEventByGcalId, arg.GcalEventID, arg.ContactID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const SyntheticCountStrandedMessagesMessageByGuid = `-- name: SyntheticCountStrandedMessagesMessageByGuid :one
SELECT COUNT(*) FROM messages_message
WHERE guid = $1
  AND matched_contact_id IS NULL
  AND deleted_at IS NULL
`

// Settle Gate A (iMessage unknown-sender): the staging row for the guid landed
// (processed) with matched_contact_id IS NULL.
func (q *Queries) SyntheticCountStrandedMessagesMessageByGuid(ctx context.Context, guid string) (int64, error) {
	row := q.db.QueryRow(ctx, SyntheticCountStrandedMessagesMessageByGuid, guid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const SyntheticCountStrandedTelegramMessagesByPeer = `-- name: SyntheticCountStrandedTelegramMessagesByPeer :one
SELECT COUNT(*) FROM telegram_message
WHERE peer_user_id = $1
  AND matched_contact_id IS NULL
  AND deleted_at IS NULL
`

// Settle Gate A (telegram unknown-sender): a message row exists for the peer
// with matched_contact_id IS NULL (the stranded/discovery-candidate state).
func (q *Queries) SyntheticCountStrandedTelegramMessagesByPeer(ctx context.Context, peerUserID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, SyntheticCountStrandedTelegramMessagesByPeer, peerUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const SyntheticCountTelegramBarePeerRowsInBand = `-- name: SyntheticCountTelegramBarePeerRowsInBand :one
SELECT (
  (SELECT COUNT(*) FROM external_contact ec
   WHERE ec.source = 'telegram'
     AND (CASE WHEN ec.source_id ~ '^[0-9]{1,18}$' THEN ec.source_id::bigint END)
           >= $1::bigint
     AND (CASE WHEN ec.source_id ~ '^[0-9]{1,18}$' THEN ec.source_id::bigint END)
           < $2::bigint
     AND ec.deleted_at IS NULL)
  +
  (SELECT COUNT(*) FROM external_identity ei
   WHERE ei.source = 'telegram'
     AND (CASE WHEN ei.source_id ~ '^[0-9]{1,18}$' THEN ei.source_id::bigint END)
           >= $1::bigint
     AND (CASE WHEN ei.source_id ~ '^[0-9]{1,18}$' THEN ei.source_id::bigint END)
           < $2::bigint)
)::bigint
`

type SyntheticCountTelegramBarePeerRowsInBandParams struct {
	BandStart int64 `json:"band_start"`
	BandEnd   int64 `json:"band_end"`
}

// Harness setup collision detection: count telegram external_contact +
// external_identity rows keyed by a BARE peer-id source_id that falls in this
// namespace's reserved peer band [band_start, band_end). A discovery/stranded
// replay creates these (source='telegram', source_id=<peer id>); a crashed prior
// run can leave them with no remaining telegram_message row, so the peer-band
// check on telegram_message alone would miss them. A non-zero count means the
// band is occupied → NewHarness re-salts.
//
// The cast is wrapped in a CASE that only evaluates source_id::bigint for
// all-digit values (bounded to 18 digits, safely under the int64 max): a bare
// WHERE `source_id ~ '...' AND source_id::bigint >= ...` is NOT safe because
// PostgreSQL may reorder the predicates and run the cast on a non-numeric
// source_id (other tests create telegram rows with text source ids like
// 'tg-discovery-upsert-*'), raising "invalid input syntax for type bigint". The
// CASE makes the cast conditional, so non-numeric rows yield NULL and fall out of
// the range comparison.
func (q *Queries) SyntheticCountTelegramBarePeerRowsInBand(ctx context.Context, arg SyntheticCountTelegramBarePeerRowsInBandParams) (int64, error) {
	row := q.db.QueryRow(ctx, SyntheticCountTelegramBarePeerRowsInBand, arg.BandStart, arg.BandEnd)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const SyntheticCountTelegramChatConfigInChatIdBand = `-- name: SyntheticCountTelegramChatConfigInChatIdBand :one
SELECT COUNT(*) FROM telegram_chat_config
WHERE telegram_chat_id >= $1
  AND telegram_chat_id < $2
`

type SyntheticCountTelegramChatConfigInChatIdBandParams struct {
	BandStart int64 `json:"band_start"`
	BandEnd   int64 `json:"band_end"`
}

// Harness setup collision detection: count telegram_chat_config rows whose
// telegram_chat_id falls in this namespace's reserved peer band [band_start,
// band_end) — group chat ids are drawn from that band. A non-zero count means a
// leftover config row occupies the band, so NewHarness re-salts.
func (q *Queries) SyntheticCountTelegramChatConfigInChatIdBand(ctx context.Context, arg SyntheticCountTelegramChatConfigInChatIdBandParams) (int64, error) {
	row := q.db.QueryRow(ctx, SyntheticCountTelegramChatConfigInChatIdBand, arg.BandStart, arg.BandEnd)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const SyntheticCountTelegramMessagesByChatAndMessageId = `-- name: SyntheticCountTelegramMessagesByChatAndMessageId :one
SELECT COUNT(*) FROM telegram_message
WHERE telegram_chat_id = $1
  AND telegram_message_id = $2
  AND deleted_at IS NULL
`

type SyntheticCountTelegramMessagesByChatAndMessageIdParams struct {
	TelegramChatID    int64 `json:"telegram_chat_id"`
	TelegramMessageID int32 `json:"telegram_message_id"`
}

// Group assertion: count telegram_message rows for (telegram_chat_id,
// telegram_message_id). Tests assert 0 for the untracked-by-size group case (the
// shouldTrackChat gate returns before UpsertMessage) and 1 for tracked.
func (q *Queries) SyntheticCountTelegramMessagesByChatAndMessageId(ctx context.Context, arg SyntheticCountTelegramMessagesByChatAndMessageIdParams) (int64, error) {
	row := q.db.QueryRow(ctx, SyntheticCountTelegramMessagesByChatAndMessageId, arg.TelegramChatID, arg.TelegramMessageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const SyntheticCountTelegramMessagesInPeerBand = `-- name: SyntheticCountTelegramMessagesInPeerBand :one
SELECT COUNT(*) FROM telegram_message
WHERE peer_user_id >= $1
  AND peer_user_id < $2
  AND deleted_at IS NULL
`

type SyntheticCountTelegramMessagesInPeerBandParams struct {
	BandStart pgtype.Int8 `json:"band_start"`
	BandEnd   pgtype.Int8 `json:"band_end"`
}

// Harness setup collision detection (D5): count live telegram_message rows whose
// peer_user_id falls in this namespace's reserved sub-block [band_start,
// band_end). A non-zero count means another namespace already occupies the band
// (probabilistic collision), so NewHarness re-salts the namespace or fails loudly
// rather than risking a cross-namespace cleanup wipe.
func (q *Queries) SyntheticCountTelegramMessagesInPeerBand(ctx context.Context, arg SyntheticCountTelegramMessagesInPeerBandParams) (int64, error) {
	row := q.db.QueryRow(ctx, SyntheticCountTelegramMessagesInPeerBand, arg.BandStart, arg.BandEnd)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const SyntheticCountUnfinalizedMessagingAggregateJobs = `-- name: SyntheticCountUnfinalizedMessagingAggregateJobs :one
SELECT COUNT(*) FROM river_job
WHERE finalized_at IS NULL
  AND kind = 'messaging_aggregate_for_contact'
  AND (args->>'source') = $1::text
  AND (args->>'contact_id') = ANY($2::text[])
`

type SyntheticCountUnfinalizedMessagingAggregateJobsParams struct {
	Source     string   `json:"source"`
	ContactIds []string `json:"contact_ids"`
}

// Settle Gate B (part 2): the messaging_aggregate_for_contact job keys on
// (contact_id, source) in its args, NOT event_id, so it is invisible to the
// event-scoped Gate B query above. Counts unfinalized aggregate jobs for this
// replay's contacts + source (mirrors CountRematchDispatcherJobsByContact).
func (q *Queries) SyntheticCountUnfinalizedMessagingAggregateJobs(ctx context.Context, arg SyntheticCountUnfinalizedMessagingAggregateJobsParams) (int64, error) {
	row := q.db.QueryRow(ctx, SyntheticCountUnfinalizedMessagingAggregateJobs, arg.Source, arg.ContactIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const SyntheticCountUnfinalizedRiverJobsForEventsByContacts = `-- name: SyntheticCountUnfinalizedRiverJobsForEventsByContacts :one

SELECT COUNT(*) FROM river_job
WHERE finalized_at IS NULL
  AND (args->>'event_id') IN (
    SELECT id::text FROM event
    WHERE (payload->>'contact_id') = ANY($1::text[])
  )
`

// ============================================================================
// Synthetic seed toolkit (internal/synthetic) test-only support queries.
// All synthetic-package DB access routes through these sqlc bindings (via
// repository/synthetic_support.go) so the package never inlines raw SQL.
// ============================================================================
// Settle Gate B (part 1): counts unfinalized river_job rows whose target
// event (args->>'event_id') was causally produced by one of this replay's
// contacts. Every contact-bearing event payload carries a scalar
// payload->>'contact_id' (interaction.recorded, calendar.attended/declined,
// email.received/sent, message.*, task.*, contact_methods.added, ...), so a
// single contact_id projection covers all cascade kinds generically — not a
// fixed kind list. Scoped to this replay's contacts (NOT a global kind count)
// so concurrent unrelated jobs on the shared test DB never block the gate.
func (q *Queries) SyntheticCountUnfinalizedRiverJobsForEventsByContacts(ctx context.Context, contactIds []string) (int64, error) {
	row := q.db.QueryRow(ctx, SyntheticCountUnfinalizedRiverJobsForEventsByContacts, contactIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const SyntheticCountUnmatchedCalendarEventByGcalId = `-- name: SyntheticCountUnmatchedCalendarEventByGcalId :one
SELECT COUNT(*) FROM calendar_event
WHERE gcal_event_id = $1
  AND matched_contact_ids = '{}'
`

// Settle Gate A (GCal unknown-attendee): the calendar_event for the gcal id
// exists with an empty matched_contact_ids array. calendar_event has no
// deleted_at column (hard-delete table), so no soft-delete filter.
func (q *Queries) SyntheticCountUnmatchedCalendarEventByGcalId(ctx context.Context, gcalEventID string) (int64, error) {
	row := q.db.QueryRow(ctx, SyntheticCountUnmatchedCalendarEventByGcalId, gcalEventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const SyntheticCountUnmatchedExternalContactByEmailPrefix = `-- name: SyntheticCountUnmatchedExternalContactByEmailPrefix :one
SELECT COUNT(*) FROM external_contact
WHERE source = 'gcal_attendee'
  AND source_id LIKE $1 || '%'
  AND match_status = 'unmatched'
  AND deleted_at IS NULL
`

// Settle/assert (GCal unmatched-attendee import candidate): the GCal provider
// stores an unmatched attendee as an external_contact with source='gcal_attendee'
// and source_id = the NORMALIZED (lowercased/trimmed) attendee email, which for a
// synthetic unknown attendee carries the 'synth-<ns>-' prefix. Counts those
// unmatched candidates for this namespace. Caller passes a BARE prefix; '%'
// appended here.
func (q *Queries) SyntheticCountUnmatchedExternalContactByEmailPrefix(ctx context.Context, sourceIDPrefix pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, SyntheticCountUnmatchedExternalContactByEmailPrefix, sourceIDPrefix)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const SyntheticCountUnmatchedExternalContactBySourceId = `-- name: SyntheticCountUnmatchedExternalContactBySourceId :one
SELECT COUNT(*) FROM external_contact
WHERE source_id = $1
  AND match_status = 'unmatched'
  AND deleted_at IS NULL
`

// Settle Gate A (Mac-contact unknown-sender): the external_contact row for the
// entity id exists with match_status='unmatched'.
func (q *Queries) SyntheticCountUnmatchedExternalContactBySourceId(ctx context.Context, sourceID string) (int64, error) {
	row := q.db.QueryRow(ctx, SyntheticCountUnmatchedExternalContactBySourceId, sourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const SyntheticDeleteCommsMessagesByExternalIdPrefix = `-- name: SyntheticDeleteCommsMessagesByExternalIdPrefix :execrows
DELETE FROM comms_message WHERE external_id LIKE $1 || '%'
`

// Cleanup step 4: comms_message rows whose external_id is ns-prefixed.
// Caller passes a BARE prefix; '%' is appended here.
func (q *Queries) SyntheticDeleteCommsMessagesByExternalIdPrefix(ctx context.Context, externalIDPrefix pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, SyntheticDeleteCommsMessagesByExternalIdPrefix, externalIDPrefix)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SyntheticDeleteContactMethodsByContactIds = `-- name: SyntheticDeleteContactMethodsByContactIds :execrows
DELETE FROM contact_method WHERE contact_id = ANY($1::uuid[])
`

// Cleanup step 11: contact_method by contact.
func (q *Queries) SyntheticDeleteContactMethodsByContactIds(ctx context.Context, contactIds []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, SyntheticDeleteContactMethodsByContactIds, contactIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SyntheticDeleteContactTasksByContactIds = `-- name: SyntheticDeleteContactTasksByContactIds :execrows
DELETE FROM contact_task WHERE contact_id = ANY($1::uuid[])
`

// Cleanup step 10: contact_task has no deleted_at; hard delete by contact.
func (q *Queries) SyntheticDeleteContactTasksByContactIds(ctx context.Context, contactIds []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, SyntheticDeleteContactTasksByContactIds, contactIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SyntheticDeleteContactTasksByIds = `-- name: SyntheticDeleteContactTasksByIds :execrows
DELETE FROM contact_task WHERE id = ANY($1::uuid[])
`

// Todoist replay cleanup: delete the contact_task rows the replay's reconcile
// created (the before/after diff from SyntheticListContactTaskIdsByProvider).
func (q *Queries) SyntheticDeleteContactTasksByIds(ctx context.Context, taskIds []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, SyntheticDeleteContactTasksByIds, taskIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SyntheticDeleteContactsByIds = `-- name: SyntheticDeleteContactsByIds :execrows
DELETE FROM contact WHERE id = ANY($1::uuid[])
`

// Cleanup step 13: contact by tracked id. A true DELETE (not soft) so
// ON DELETE CASCADE fires for contact_enrichment (and any cascade FK).
func (q *Queries) SyntheticDeleteContactsByIds(ctx context.Context, contactIds []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, SyntheticDeleteContactsByIds, contactIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SyntheticDeleteEventConsumerClaimsByEventIds = `-- name: SyntheticDeleteEventConsumerClaimsByEventIds :execrows
DELETE FROM event_consumer_claim WHERE event_id = ANY($1::uuid[])
`

// Cleanup step 1: claims for this replay's events (by tracked event id).
func (q *Queries) SyntheticDeleteEventConsumerClaimsByEventIds(ctx context.Context, eventIds []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, SyntheticDeleteEventConsumerClaimsByEventIds, eventIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SyntheticDeleteEventsByIds = `-- name: SyntheticDeleteEventsByIds :execrows
DELETE FROM event WHERE id = ANY($1::uuid[])
`

// Cleanup step 3: events by tracked id (NOT by source — that would wipe
// other tests' rows sharing the source value on the shared DB).
func (q *Queries) SyntheticDeleteEventsByIds(ctx context.Context, eventIds []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, SyntheticDeleteEventsByIds, eventIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SyntheticDeleteExternalIdentitiesByIdentifierPrefix = `-- name: SyntheticDeleteExternalIdentitiesByIdentifierPrefix :execrows
DELETE FROM external_identity WHERE identifier LIKE $1 || '%'
`

// Cleanup step 8: identities whose normalized identifier shares an ns-scoped
// prefix. MatchOrCreate for GCal attendee / external_contact email matching
// creates identities with source_id NULL keyed by the synthetic IDENTIFIER (e.g.
// 'synth-<ns>-...@synthetic.example'), which a source_id-prefix delete MISSES.
// Deleting by the identifier prefix catches both the source_id-NULL and
// source_id-set synthetic identities BEFORE the contact delete (external_identity
// survives contact delete via ON DELETE SET NULL, so it would otherwise pollute
// future matching). Called once with the 'synth-<ns>-' string prefix (email/
// handle identities) and once with the namespace's normalized phone-digit prefix
// ('+1<area>55501...') — synthetic phones are now ns-scoped via the per-namespace
// area code (factory.phoneFor), so phone identities no longer leak. Caller passes
// a BARE prefix; '%' appended.
func (q *Queries) SyntheticDeleteExternalIdentitiesByIdentifierPrefix(ctx context.Context, identifierPrefix pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, SyntheticDeleteExternalIdentitiesByIdentifierPrefix, identifierPrefix)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SyntheticDeleteExternalIdentitiesBySourceIdPrefix = `-- name: SyntheticDeleteExternalIdentitiesBySourceIdPrefix :execrows
DELETE FROM external_identity WHERE source_id LIKE $1 || '%'
`

// Cleanup step 8 (backstop): catches any ns-prefixed source_id rows the
// identifier-prefix delete missed. Caller passes a BARE prefix; '%' appended.
func (q *Queries) SyntheticDeleteExternalIdentitiesBySourceIdPrefix(ctx context.Context, sourceIDPrefix pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, SyntheticDeleteExternalIdentitiesBySourceIdPrefix, sourceIDPrefix)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SyntheticDeleteInteractionsByIds = `-- name: SyntheticDeleteInteractionsByIds :execrows
DELETE FROM interaction WHERE id = ANY($1::uuid[])
`

// Cleanup step 2: interactions by tracked id.
func (q *Queries) SyntheticDeleteInteractionsByIds(ctx context.Context, interactionIds []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, SyntheticDeleteInteractionsByIds, interactionIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SyntheticDeleteMacHostById = `-- name: SyntheticDeleteMacHostById :execrows
DELETE FROM mac_host WHERE id = $1
`

// Cleanup step 14: the seeded revoked synthetic mac_host by id.
func (q *Queries) SyntheticDeleteMacHostById(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, SyntheticDeleteMacHostById, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SyntheticDeleteMessagesMessageByGuidPrefix = `-- name: SyntheticDeleteMessagesMessageByGuidPrefix :execrows
DELETE FROM messages_message WHERE guid LIKE $1 || '%'
`

// Cleanup step 5: messages_message rows whose guid is ns-prefixed.
// Caller passes a BARE prefix; '%' is appended here.
func (q *Queries) SyntheticDeleteMessagesMessageByGuidPrefix(ctx context.Context, guidPrefix pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, SyntheticDeleteMessagesMessageByGuidPrefix, guidPrefix)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SyntheticDeleteNotesByContactIds = `-- name: SyntheticDeleteNotesByContactIds :execrows
DELETE FROM note WHERE contact_id = ANY($1::uuid[])
`

// Cleanup step 12: note by contact.
func (q *Queries) SyntheticDeleteNotesByContactIds(ctx context.Context, contactIds []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, SyntheticDeleteNotesByContactIds, contactIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SyntheticDeleteTelegramChatConfigsByChatIds = `-- name: SyntheticDeleteTelegramChatConfigsByChatIds :execrows
DELETE FROM telegram_chat_config WHERE telegram_chat_id = ANY($1::bigint[])
`

// Cleanup: delete the group telegram_chat_config rows a group replay created, by
// the exact tracked chat ids (telegram_chat_config has no namespace column —
// keyed only by telegram_chat_id).
func (q *Queries) SyntheticDeleteTelegramChatConfigsByChatIds(ctx context.Context, chatIds []int64) (int64, error) {
	result, err := q.db.Exec(ctx, SyntheticDeleteTelegramChatConfigsByChatIds, chatIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SyntheticDeleteTelegramExternalContactsByPeerIds = `-- name: SyntheticDeleteTelegramExternalContactsByPeerIds :execrows
DELETE FROM external_contact
WHERE source = 'telegram' AND source_id = ANY($1::text[])
`

// Cleanup: telegram discovery candidate external_contact rows are keyed by
// source='telegram', source_id = the BARE peer user id (not an ns-prefixed
// string), so the ns-prefix external_contact delete misses them. A stranded /
// unknown-sender replay that crosses the discovery threshold upserts one; delete
// them by the exact tracked peer ids (string form).
func (q *Queries) SyntheticDeleteTelegramExternalContactsByPeerIds(ctx context.Context, peerIds []string) (int64, error) {
	result, err := q.db.Exec(ctx, SyntheticDeleteTelegramExternalContactsByPeerIds, peerIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SyntheticDeleteTelegramExternalIdentitiesByPeerIds = `-- name: SyntheticDeleteTelegramExternalIdentitiesByPeerIds :execrows
DELETE FROM external_identity
WHERE source = 'telegram' AND source_id = ANY($1::text[])
`

// Cleanup: MatchPeer creates an external_identity for an unmatched telegram peer
// keyed by source='telegram', source_id = the BARE peer user id. The synthetic
// handle is normalized to 'synth_<ns>_<n>' (underscores), which the ns-prefix
// ('synth-<ns>-') identifier delete does NOT match, so clear these by the exact
// tracked peer ids before the contact delete (external_identity survives contact
// delete via ON DELETE SET NULL and would otherwise pollute future matching).
func (q *Queries) SyntheticDeleteTelegramExternalIdentitiesByPeerIds(ctx context.Context, peerIds []string) (int64, error) {
	result, err := q.db.Exec(ctx, SyntheticDeleteTelegramExternalIdentitiesByPeerIds, peerIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const SyntheticListContactTaskIdsByProvider = `-- name: SyntheticListContactTaskIdsByProvider :many
SELECT id FROM contact_task WHERE provider = $1
`

// Todoist replay: snapshot the set of contact_task ids for a provider so the
// replay can diff before/after its (globally-scoped) reconcile and track the
// rows it created — even for cadence-bearing contacts it did not seed — so
// cleanup removes exactly those rows and never strands a task on an unrelated
// contact in the shared test DB.
func (q *Queries) SyntheticListContactTaskIdsByProvider(ctx context.Context, provider string) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, SyntheticListContactTaskIdsByProvider, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SyntheticListEventIdsBySourceAndSourceIdPrefix = `-- name: SyntheticListEventIdsBySourceAndSourceIdPrefix :many
SELECT id FROM event
WHERE source = $1::text
  AND source_id LIKE $2 || '%'
`

type SyntheticListEventIdsBySourceAndSourceIdPrefixParams struct {
	Source         string      `json:"source"`
	SourceIDPrefix pgtype.Text `json:"source_id_prefix"`
}

// Cleanup event-id capture (part 2): adapter-direct root events that carry NO
// CRM contact id (raw_message.* / external_contact.upserted roots, and
// unknown/pending replays that touch no seeded contact). Keyed by the
// synthetic (source, source_id-prefix) the adapter wrote. The UNION of this
// and SyntheticListEventIdsForContacts is the cleanup event set — leaving a
// root event behind would make a later same-namespace replay dedup on the
// (source, source_id) unique and skip inline ingest (idempotency break).
// Caller passes a BARE prefix; the '%' is appended here (matches the existing
// Delete*ByPrefix conventions).
func (q *Queries) SyntheticListEventIdsBySourceAndSourceIdPrefix(ctx context.Context, arg SyntheticListEventIdsBySourceAndSourceIdPrefixParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, SyntheticListEventIdsBySourceAndSourceIdPrefix, arg.Source, arg.SourceIDPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SyntheticListEventIdsForContacts = `-- name: SyntheticListEventIdsForContacts :many
SELECT id FROM event
WHERE (payload->>'contact_id') = ANY($1::text[])
`

// Cleanup event-id capture (part 1): every event.id whose payload references
// one of this replay's contacts. Covers the full non-prefixed cascade
// (interaction.recorded uses interaction.ID as source_id, calendar.attended
// uses an internal ref, etc.) generically via payload->>'contact_id'.
func (q *Queries) SyntheticListEventIdsForContacts(ctx context.Context, contactIds []string) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, SyntheticListEventIdsForContacts, contactIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TestCountAllRows = `-- name: TestCountAllRows :one
SELECT (xpath('/row/c/text()',
    query_to_xml(format('SELECT COUNT(*) AS c FROM %I', $1::text), false, true, '')))[1]::text::bigint
`

// Reset integration test only: count ALL rows in a single table by name. Used by
// the clone-DB reset test to assert each wiped table is empty after the reset and
// that schema_migrations survives. The table name is validated against the wiped
// list by the test before it reaches here; format() with %I quotes the
// identifier so it can never be an injection vector.
func (q *Queries) TestCountAllRows(ctx context.Context, tableName string) (int64, error) {
	row := q.db.QueryRow(ctx, TestCountAllRows, tableName)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const TestInsertExternalSyncStateMarker = `-- name: TestInsertExternalSyncStateMarker :exec
INSERT INTO external_sync_state (source, account_id)
VALUES ('synthetic_test', 'reset-marker')
`

// Reset test only: a marker row in external_sync_state (a sync-cursor table the
// reset wipes so staging cannot re-sync real data).
func (q *Queries) TestInsertExternalSyncStateMarker(ctx context.Context) error {
	_, err := q.db.Exec(ctx, TestInsertExternalSyncStateMarker)
	return err
}

const TestInsertNonFinalRiverJob = `-- name: TestInsertNonFinalRiverJob :exec
INSERT INTO river_job (kind, queue, state, args, metadata, priority, max_attempts)
VALUES ('synthetic_test_marker', 'default', 'available', '{}'::jsonb, '{}'::jsonb, 1, 1)
`

// Reset/additive-seed test only: plant ONE queued (non-finalized) river_job so a
// test can assert the additive --seed preflight REFUSES while --reset-and-seed
// PROCEEDS (it wipes river_job). Minimal valid row: River requires kind, queue,
// state, args, metadata; finalized_at stays NULL (the unfinalized signal).
func (q *Queries) TestInsertNonFinalRiverJob(ctx context.Context) error {
	_, err := q.db.Exec(ctx, TestInsertNonFinalRiverJob)
	return err
}

const TestInsertOAuthCredentialMarker = `-- name: TestInsertOAuthCredentialMarker :exec
INSERT INTO oauth_credential
    (provider, account_id, access_token_encrypted, encryption_nonce)
VALUES ('synthetic_test', 'reset-marker', '\x00'::bytea, '\x00'::bytea)
`

// Reset test only: a marker row in oauth_credential (the table whose preservation
// would re-introduce real PII on re-sync). Proves the reset wipes it.
// The token columns are bytea (encrypted-at-rest); dummy bytes are fine for a
// marker that is never decrypted.
func (q *Queries) TestInsertOAuthCredentialMarker(ctx context.Context) error {
	_, err := q.db.Exec(ctx, TestInsertOAuthCredentialMarker)
	return err
}

const TestInsertTagMarker = `-- name: TestInsertTagMarker :exec
INSERT INTO tag (name) VALUES ('synthetic-reset-marker')
`

// Reset test only: a marker row in tag (a standalone table the harness does not
// touch).
func (q *Queries) TestInsertTagMarker(ctx context.Context) error {
	_, err := q.db.Exec(ctx, TestInsertTagMarker)
	return err
}

const TestInsertTelegramSessionMarker = `-- name: TestInsertTelegramSessionMarker :exec
INSERT INTO telegram_session (session_data_encrypted, encryption_nonce, phone_number)
VALUES ('\x00'::bytea, '\x00'::bytea, 'reset-marker')
`

// Reset test only: a marker row in telegram_session (the Telegram auth session
// the reset wipes). session_data_encrypted + encryption_nonce are NOT NULL bytea.
func (q *Queries) TestInsertTelegramSessionMarker(ctx context.Context) error {
	_, err := q.db.Exec(ctx, TestInsertTelegramSessionMarker)
	return err
}

const TestListContactBucketsByNamePrefix = `-- name: TestListContactBucketsByNamePrefix :many
SELECT
    c.id,
    c.cadence,
    c.last_contacted,
    (SELECT COUNT(*) FROM contact_method cm WHERE cm.contact_id = c.id) AS method_count
FROM contact c
WHERE c.full_name LIKE $1 || '%'
  AND c.deleted_at IS NULL
`

type TestListContactBucketsByNamePrefixRow struct {
	ID            pgtype.UUID        `json:"id"`
	Cadence       pgtype.Text        `json:"cadence"`
	LastContacted pgtype.Timestamptz `json:"last_contacted"`
	MethodCount   int64              `json:"method_count"`
}

// Profile coverage test only: list the namespace's contacts (by full_name
// prefix) with the bucket-defining columns + a method count, so the test can
// assert the catalog produced ≥1 overdue (cadence + last_contacted in the past),
// ≥1 never-contacted (cadence + NULL last_contacted), and ≥1 no-method contact —
// proving the cadence/no-method states SURVIVE (a settling replay would
// overwrite last_contacted). Caller passes a BARE prefix; '%' appended.
func (q *Queries) TestListContactBucketsByNamePrefix(ctx context.Context, namePrefix pgtype.Text) ([]*TestListContactBucketsByNamePrefixRow, error) {
	rows, err := q.db.Query(ctx, TestListContactBucketsByNamePrefix, namePrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*TestListContactBucketsByNamePrefixRow{}
	for rows.Next() {
		var i TestListContactBucketsByNamePrefixRow
		if err := rows.Scan(
			&i.ID,
			&i.Cadence,
			&i.LastContacted,
			&i.MethodCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TestListPublicTables = `-- name: TestListPublicTables :many
SELECT table_name::text FROM information_schema.tables
WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
ORDER BY table_name
`

// Reset integration test only: enumerate every base table in the public schema
// so the catalog guard can assert each is in the wiped list, is schema_migrations,
// or matches the river_% allowlist. Read-only catalog access.
func (q *Queries) TestListPublicTables(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, TestListPublicTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var table_name string
		if err := rows.Scan(&table_name); err != nil {
			return nil, err
		}
		items = append(items, table_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
