// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: test.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const CountContactsByNamePrefix = `-- name: CountContactsByNamePrefix :one
SELECT COUNT(*) FROM contact WHERE full_name LIKE $1 || '%'
`

func (q *Queries) CountContactsByNamePrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, CountContactsByNamePrefix, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountExternalContactsByDisplayNamePrefix = `-- name: CountExternalContactsByDisplayNamePrefix :one
SELECT COUNT(*) FROM external_contact WHERE display_name LIKE $1 || '%'
`

func (q *Queries) CountExternalContactsByDisplayNamePrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, CountExternalContactsByDisplayNamePrefix, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const DeleteContactsByNamePrefix = `-- name: DeleteContactsByNamePrefix :execrows

DELETE FROM contact WHERE full_name LIKE $1 || '%'
`

// Test data management queries
// These queries are used by the test API endpoints to seed and cleanup test data
func (q *Queries) DeleteContactsByNamePrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteContactsByNamePrefix, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteExternalContactsByDisplayNamePrefix = `-- name: DeleteExternalContactsByDisplayNamePrefix :execrows
DELETE FROM external_contact WHERE display_name LIKE $1 || '%'
`

func (q *Queries) DeleteExternalContactsByDisplayNamePrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteExternalContactsByDisplayNamePrefix, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const DeleteExternalContactsBySourceIDPrefix = `-- name: DeleteExternalContactsBySourceIDPrefix :execrows
DELETE FROM external_contact WHERE source_id LIKE $1 || '%'
`

func (q *Queries) DeleteExternalContactsBySourceIDPrefix(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	result, err := q.db.Exec(ctx, DeleteExternalContactsBySourceIDPrefix, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
